### PR TITLE
Ceph validate and update

### PR DESCRIPTION
**Pull request by badone**
[ceph] Validate and update the existing plugin 

For issue #496

### CODE REVIEW

**Comment by badone** [comment]
Groan :(

I have no idea how the foreman commit got in there.

**Comment by bmr-cymru** [comment]
Just do `git rebase -i` and remove it from the list of commits that appears. Then do a `git push --force` to update the pull request.

You'll need to do a rebase anyway to get rid of those two merge commits (merge commits are absolutely forbidden in sos master).

While you're doing that you might as well make the line for commit b697262 into 'e' (edit) so you can make the subject line something more descriptive like: "[ceph] update ceph mon, report and health commands".

**Comment by bmr-cymru** [comment]
I.e. commit b697262 and commit 9c9ec43 should be 'pick'ed and 'squash'ed respectively, and the 2nd merge (commit b69d1b0) should be squashed into commit b65da1f.

For the final patch I would suggest changing the subject to "[ceph] add calamari and rados config and logs" - the current subject is too long and wraps on a standard terminal.

**Comment by bmr-cymru** [comment]
I think we got this all merged in the two recent ceph patches, right? If not please re-open.

Thanks!

**Pull request closed without merging**
