### PR TITLE
[plugins, logs] Apply --since option to journal logs

### PR DESCRIPTION
**Pull request by pmoravec**
journalctl / add_journal should apply --since command line option
the same way like collecting logfiles / add_copy_spec does.

Resolves: #1848

Signed-off-by: Pavel Moravec <pmoravec@redhat.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [X] If this commit closes an existing issue, is the line `Closes: #ISSUENUMBER` included in an independent line?
- [X] If this commit resolves an existing pull request, is the line `Resolves: #PRNUMBER` included in an independent line?

### CODE REVIEW

**Comment by BryanQuigley** [comment]
Can we  simplify the logs plugin first, see #1822?  I think I do fix this in that.

**Comment by pmoravec** [comment]
Ah, I haven't checked that PR.

That PR fixes something from this one, but I lack there:
- `add_journal` called on a unit (say, `chronyd` from that plugin) does not respect `--since` and collects also older log entries
- I still see `journalctl_--no-pager_--catalog_--boot[|_-1]` that also do not respect `--since`

I *think* if your PR moves the `since = self.get_option("since")` to `add_journal` as `since = since or self.get_option("since")`, my concerns would be resolved - going to check this now.

**Comment by BryanQuigley** [comment]
>add_journal called on a unit (say, chronyd from that plugin) does not respect --since and collects also older log entries
Hmm.. do we want to have to be explicit in the plugin that we want --since applied?  I guess I can't see where that would go poorly - except with specifying boots.  

>I still see journalctl_--no-pager_--catalog_--boot[|_-1] that also do not respect --since
I'm happy to add that if it's somehow better, but I don't understand the point of specifing boots if you will override it with since.

**Comment by pmoravec** [comment]
> > add_journal called on a unit (say, chronyd from that plugin) does not respect --since and collects also older log entries
> Hmm.. do we want to have to be explicit in the plugin that we want --since applied?  I guess I can't see where that would go poorly - except with specifying boots.

I dont understand here. With my proposal, `--since` (if used) will be applied to journal units. If some plugin wants to ignore this option, it can call `add_journal(since="19700101")` which supersets the `--since` cmdline option.

> 
> > I still see journalctl_--no-pager_--catalog_--boot[|_-1] that also do not respect --since
> I'm happy to add that if it's somehow better, but I don't understand the point of specifing boots if you will override it with since.

Two use cases:
- I am interested in logs since some time, regardless if it was current or previous boot
- I know something bad happened yesterday, got rebooted the system, needs RCA but dont need much historical logs - so I can use `--since` with 2 days ago. `this` and `last` boot will ensure I got logs since past 2 days, regardless it was before or after the recent reboot (assuming no more reboots happened).

**Comment by BryanQuigley** [comment]
I'm convinced on moving to since to apply by default for all plugins journal - as you said a plugin can override it. Happy to approve just that bit - or incorporate it into the other PR.

**Comment by pmoravec** [comment]
I am glad for the consensus. I prefer if you update your PR to have it merged altogether, but can build on top of your commit.

**Comment by pmoravec** [comment]
Closing in favour of #1822 .

**Pull request closed without merging**
