### PR TITLE
[powerpc] Add support to collect DLPAR and LPM related logs

### PR DESCRIPTION
**Pull request by sourabhjains**
This patch updates powerpc plugin to collect
Dynamic Resource Manager (drmgr) log files
i.e. /var/log/drmgr and /var/log/drmgr.0.
In addition, it also adds ctsanp command to collect the information
about the Reliable Scalable Cluster Technology (RSCT) components.

Signed-off-by: Sourabh Jain <sourabhjain@linux.ibm.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?

### CODE REVIEW

**Comment by bmr-cymru** [comment]
If these logs can grow to potentially large sizes it would be better to split them out into a separate `add_copy_specs()` call, and to implement the `log_size` and `all_logs` options. Since the plugin is specific to IBM Power though I'll leave that decision to you. Otherwise the changes look good.

**Comment by hegdevasant** [comment]
Hello Bryn,

These files wont' grow that big. So I think its fine to run under add_copy_specs().

I've reviewed patch and it looks good to me. Sourabh will fix coding style issue and will send v2.

-Vasant

**Comment by hegdevasant** [comment]
V2 looks good to me.

Looks good.

Reviewed-by: Vasant Hegde <hegdevasant@linux.vnet.ibm.com>

**Comment by hegdevasant** [comment]
Commit looks good.

Thanks!

-Vasant

**Pull request closed without merging**
