### PR TITLE
[sapnw] Add check if saphostctrl is not present

### PR DESCRIPTION
**Pull request by pmoravec**
Resolves: #614

Just add test if "inst_out = self.get_cmd_output_now" does not return
None before opening the output file and executing the subsequent loop.

db_out is already checked this way.

Signed-off-by: Pavel Moravec <pmoravec@redhat.com>

### CODE REVIEW

**Comment by bmr-cymru** [comment]
I would split the (horribly long) `setup()` method into three functions:

`_get_instances()`
`_get_databases()`
`setup()`

Move all the instances stuff into the first & just return if the output is empty and the db stuff into the 2nd. Leave 'sapconf' in `setup()` (but since you're editing it anyway might as well remove both the pointless check for `/usr/bin/sapconf` and the `/usr/bin` in the subsequent `add_cmd_output()`. Both are unnecessary and it is policy that we do not use absolute paths for any binaries in standard PATH locations (because it breaks if the distro decided to move that to `/bin` or whatever).

**Comment by pmoravec** [comment]
Updated, also rebased with #608 / commit 24fb011755e655127b7e09f4c02275539666b4b2 included.

I did also some minor changes to inserted empty lines, that should bring more code clarity / readability.

**Comment by battlemidget** [comment]
@pmoravec can you fix the merge conflicts and I'll get it merged?

**Comment by pmoravec** [comment]
@battlemidget This PR has been committed already: 10059897ceb0755bab844011f11ea6c6af8794ae (conflicts are due to subsequent commit 1f83971 fixing a typo in the 1005989, I guess). Worth closing PR?

**Pull request closed without merging**
