### PR TITLE
[juju] dont restart juju-db service

### PR DESCRIPTION
**Pull request by pmoravec**
sosreport shouldnt restart a service. It can only collect it's status
to notify user in case the service is stopped.

Resolves: #1653

Signed-off-by: Pavel Moravec <pmoravec@redhat.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?

### CODE REVIEW

**Comment by slashdd** [comment]
As an fyi. Canonical is currently working on a new juju plugin to address this bug and do a good rewrite of the plugin to support upcoming features.

**Comment by dnegreira** [comment]
Hi,
We are currently working on refactoring the juju plugin and separating it in several modules, one of the refactoring is indeed dropping this weird behavior. I hope to have the plugin ready in the next few days.

**Comment by dnegreira** [comment]
Hi,

PR is done here: https://github.com/sosreport/sos/pull/1670

**Comment by pmoravec** [comment]
OK dropping this PR in favour of #1670. Thanks for pointing and the rework!

**Pull request closed without merging**
