### PR TITLE
Collect clock source for non-RT kernels

### PR DESCRIPTION
**Pull request by portante**
When doing performance analysis is would be nice to know clock source on RT kernels.

### CODE REVIEW

**Comment by bmr-cymru** [comment]
To be honest I've never really liked these being hidden away in kernelrt - a long time ago there were concerns about the inconsistencies in this information between RHEL4/5/6 (and the rt/non-rt variants) but I think today that's largely historical and we can forget about it.

How about moving these to a single "time" or "clocksource" plugin? (I can think of a few other things that'd belong in a general "time" module, beyond what we already collect in the general and ntp plugins).

**Comment by portante** [comment]
Sounds good to me.

Do you want to do that refactoring as part of this patch?  Or after?

**Comment by bmr-cymru** [comment]
I think we might as well get it all done together - or at least in a short series - we're a little overdue for a release and it would be good to have this in before that happens.

**Comment by bmr-cymru** [comment]
Thanks - I've edited your commit message slightly & pushed to master. We can do a split into a separate time/clock/whatever plugin at a future time - I got to thinking about this some more and if we're going to go ahead with it there are a few other time related anomalies we should clean up at the same time.

**Comment by portante** [comment]
"... there are a few other time related anomalies we should clean up at the same time."

Pun intended?  ;)

Thanks for merging.

**Comment by bmr-cymru** [comment]
Haha - for once, no :-)

Cheers,

**Pull request closed without merging**
