### PR TITLE
create plugin to collect Red Hat Access Insights config and logs

### PR DESCRIPTION
**Pull request by jcrafts**

### CODE REVIEW

**Comment by battlemidget** [comment]
Thanks for the PR, but please follow the contributer guidelines.

**Comment by bmr-cymru** [comment]
See [here](http://github.com/sosreport/sos/wiki/Contribution-Guidelines). There are also a couple of code style & standard nits that need fixing. The house style for multi-line lists in method calls is:

```python
    self.some_method([
        "this method",
        "takes a list",
        "as argument"
    ])
```

Log files should be collected respecting the global `all_logs` and `log_size` options - see the [Plugin Author's Guide](https://github.com/sosreport/sos/wiki/How-to-Write-a-Plugin) and the [Plugin Options](https://github.com/sosreport/sos/wiki/Plugin-options) documentation.

**Comment by jcrafts** [comment]
Is it preferred to have a new commit with these changes, or to overwrite the original?

**Comment by battlemidget** [comment]
Force push over the original is preferred

**Comment by bmr-cymru** [comment]
yep :+1:

Make your changes and then a `git push --force` will force-update the branch without losing any of the pull request metadata.

**Pull request closed without merging**
