### PR TITLE
[utilities] remove unused hashlib import

### LINKED ISSUE #720: Remove hashlib import from sos/utilities.py since
With the removal of the hashing functions from sos/utilities.py there is no need to import hashlib.  The hashing was removed in the following commit: https://github.com/sosreport/sos/commit/6038fdf8617319a13b0b42f3283ec2066d54b283

$ gendiff sos/ .org
diff -up sos/sos/utilities.py.org sos/sos/utilities.py
--- sos/sos/utilities.py.org	2016-01-12 09:26:50.865294298 -0500
+++ sos/sos/utilities.py	2016-01-12 09:26:58.959233725 -0500
@@ -18,7 +18,6 @@ import os
 import re
 import inspect
 from subprocess import Popen, PIPE, STDOUT
-import hashlib
 import logging
 import fnmatch
 import errno

### PR DESCRIPTION
**Pull request by Akasurde**
Fixes #720 
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

### CODE REVIEW

**Comment by battlemidget** [comment]
ack

**Comment by bmr-cymru** [comment]
Thanks Abhijeet! Shane spotted this the other day but you beat him to an upstream submission, so you get the credit :-)

Could you please re-do the commit message to comply with the [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines) and I'll be able to merge this?

The only thing that needs to be done is for the subject to follow the `'[subsystem] description of change'` format, for example:

```
    [utilities] remove unused hashlib import
```

You can make the change and then fix the original commit with `git commit --amend` before updating the branch in the pull request using `git push --force`.

**Comment by bmr-cymru** [comment]
Adding final ack subject to commit message fixup.

**Comment by battlemidget** [comment]
@Akasurde please force push a new commit message conforming to our https://github.com/sosreport/sos/wiki/Contribution-Guidelines

**Comment by bmr-cymru** [comment]
Thanks!

**Pull request merged**
