### PR TITLE
[dnf] New dnf plugin

### PR DESCRIPTION
**Pull request by psachin**
Added dnf plugin to collect:
- dnf.conf file from /etc/dnf/
- dnf logs from /var/log/
- dnf version info
- dnf history
- List installed dnf plugins

Signed-off-by: Sachin Patil <sacpatil@redhat.com>

### CODE REVIEW

**Comment by bmr-cymru** [comment]
Thanks for the pull request - I've added some review comments to the commit. Once you have addressed those you should amend the commit and do a forced update to the branch in order to preserve the pull request history:

```
$ git commit --amend
$ git push --force
```

**Comment by psachin** [comment]
Done. Please see the changes

**Comment by bmr-cymru** [comment]
Thanks for turning around the review comments so quickly! This looks good now (although I think we can add the extras listing back in) - one minor point I forgot to mention is that we normally include a vim modeline in the files to auto-set tabstop, expandtabs etc. but that's no problem I can add it in when I merge.

**Comment by psachin** [comment]
Thanx Bryn. Sure I wanted to add extras...but capturing 'Available packages' doesn't makes any sense. If you want I can add vim modeline?  but I use Emacs and I totally forgot to add the line.

**Comment by bmr-cymru** [comment]
> If you want I can add vim modeline? but I use Emacs and I totally forgot to add the line.

No problem - we have a standard one we use that matches our coding standard. If you'd like to submit a suggestion for an equivalent Emacs setting I'd be happy to merge that into all the source files (and finally fix issue #243 properly..)

**Comment by bmr-cymru** [comment]
Doing `list extras` is fine - it gives the correct information _if_ there are packages installed that are not present in the repos. Here's some output from an f23 machine of mine that has an upstream (manual install) `sos` package, some `kernel` packages that have expired from the repo and a 3rd-party `plexmediaserver` package:

```
$ sudo dnf list extras
Last metadata expiration check performed 0:36:09 ago on Thu Feb 18 13:57:50 2016.
Extra Packages
freeimage.x86_64                                                                 3.17.0-3.fc23                                                                  @updates-testing
kernel.x86_64                                                                    4.3.3-301.fc23                                                                 @updates        
kernel.x86_64                                                                    4.3.4-300.fc23                                                                 @updates        
kernel-core.x86_64                                                               4.3.3-301.fc23                                                                 @updates        
kernel-core.x86_64                                                               4.3.4-300.fc23                                                                 @updates        
kernel-debug-devel.x86_64                                                        4.3.3-301.fc23                                                                 @updates        
kernel-debug-devel.x86_64                                                        4.3.4-300.fc23                                                                 @updates        
kernel-modules.x86_64                                                            4.3.3-301.fc23                                                                 @updates        
kernel-modules.x86_64                                                            4.3.4-300.fc23                                                                 @updates        
plexmediaserver.x86_64                                                           0.9.12.13.1464-4ccd2ca                                                         @@commandline   
sos.noarch                                                                       3.2-1.fc23                                                                     @System       
```

**Comment by psachin** [comment]
Cool. Let me add 'list extra' and send you a quick PR

**Comment by bmr-cymru** [comment]
:+1: 

No need for a new PR though - just add or amend your commits (it's fine to add that in a separate commit) and then update the branch. If you re-write the old commit with `--amend` then you'll need to use `git push --force` to update this PR.

**Comment by psachin** [comment]
yep

**Comment by psachin** [comment]
Added 'list extra'

**Comment by bmr-cymru** [comment]
Thanks - merged with a couple of minor edits. I am in two minds currently whether to leave the history list optional - comparing to the existing `yum` plugin this was always collected by default.

**Pull request closed without merging**
