### PR TITLE
[redis] Added new plugin for Redis

### LINKED ISSUE #667: [redis] Add new plugin
Redis is an open source, in-memory data structure store, used as a database, cache and message broker.

- collect `/var/log/redis/redis.log`
- collect useful command output (TBD) http://redis.io/commands

### PR DESCRIPTION
**Pull request by Akasurde**
Fixes #667 

Patch adds plugin to collect details related to Redis -
in-memory data structure store.

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

### CODE REVIEW

**Comment by bmr-cymru** [comment]
@lyarwood could also use your take on this - as you filed the original redis feature request.

Cheers,

**Comment by lyarwood** [comment]
:+1:  LGTM aside from the commit message, can you squash the message into a series of bullet points as your references to separate patches is slightly confusing.

**Comment by bmr-cymru** [comment]
Yes, as @lyarwood says: you need to edit your commit message so that it makes logical sense in context - when you wrote it it was separate patches but this will all be a single commit in master. Right now it is confusing.

**Comment by bmr-cymru** [comment]
Normally you only do the:

```
v2:
    * fixed something
    * added something
v3:
    * did something else
```

Style when you are submitting new versions of patches to a mailing list. There's no need to do that for GitHub pulls.

**Comment by lyarwood** [comment]
:+1: LGTM

**Comment by Akasurde** [comment]
Ping

**Comment by bmr-cymru** [comment]
Will be merged with the next batch.

**Comment by bmr-cymru** [comment]
Merged in commit 7d1b9afc9c55652a0d5076bfec59cb34cd2efc95.

**Pull request closed without merging**
