### PR TITLE
[sos_extras] Allow obfuscation in sos_extras configs

### PR DESCRIPTION
**Pull request by pmoravec**
Resolves: #3768

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [X] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?
- [X] Are all passwords or private data gathered by this PR [obfuscated](https://github.com/sosreport/sos/wiki/How-to-Write-a-Plugin#how-to-prevent-collecting-passwords)?

### CODE REVIEW

**Comment by pmoravec** [comment]
Limitations:
- different globs for files/cmds to collect (`/path/to/file.log*`) and to obfuscate in (`/path/to/file.log.*`) - this is user unfriendly
- no way to express space in either RE (to search or to replace)
- example line `*:/path/to/files(.*) pass:\\s*(.*) \1********` should have `\s` instead of `\\s` but that would raise `W605 invalid escape sequence '\s'` :(

Worth to discuss:
- particular syntax

**Comment by TurboTurtle** [comment]
I'm torn on this.

On the one hand, it is useful functionality and I can see the practicality. On the other, we don't really want to encourage using sos_extras as an _alternative_ to plugin development. It's chiefly meant to serve as a function of "I need this right away while a plugin is being updated or developed which is either currently happening or I am about to open a request for".

**Comment by pmoravec** [comment]
The request comes from a customer having some logs written to an unusual customized location that `sos` will never collect. But the logfile is important for troubleshooting. Like, e.g. `/var/log/httpd/access_log`  is moved to `/var/log/httpd/my_custom_access_log`.

The httpd access log is just ilustrative example. I will check if we can't (or even shouldn't) parse some config file that specifies such custom logfiles, and collect the custom logfiles automatically.

**Comment by pmoravec** [comment]
I understand (and mostly agree). I will close the PR as going against the original intention of `sos_extras`.

**Pull request closed without merging**
