### PR TITLE
[networking] collect socket stat from each namespace

### PR DESCRIPTION
**Pull request by stuggi**
added command to collect 'ss -lnp' within each namespace

Signed-off-by: Martin Schuppert <mschuppert@redhat.com>

### CODE REVIEW

**Comment by bmr-cymru** [comment]
You're missing a DCO (Signed-off-by) - please refer to the [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines).

For a change list this you should also include an explanation of why it is desirable/necessary. We already collect netstat, ethtool, and link statistics (including all open sockets with process identities), so an explanation of why collecting listening socket information on a per-namespace basis is needed should be included in comments, the commit message, or the pull request.

**Comment by stuggi** [comment]
Thanks Bryn. For analyse OpenStack issues it is really useful to see what process serves what service inside the router/dhcp namespace, like is metadata proxy running or not. Right now we collect the information on ip,routes and iptables, but not the information on the services inside.

**Comment by bmr-cymru** [comment]
That doesn't explain why `netstat -neopa` is insufficient; that shows every active socket, the process that is bound to it, and the socket addresses (for UNIX domain sockets this is the path, for others the appropriate IP address family type).

If there is something specific in the  `ss` output please explain what it is - if it is just a preference for the `ss` formatting then that is not a good enough reason to add this.

Your commit is still missing a DCO.

**Comment by stuggi** [comment]
Sorry for the delay. The issue is not using netstat or ss, what we miss (if I am not wrong) is to collect the information within the namespaces. 
Assuming a system with

~~~
# ip netns
qdhcp-c026ee53-a02a-4ee3-aec6-f11fa6b64a68
qrouter-912d2fba-71ad-4b56-a771-66ef4eaa3471
~~~

Where we have dnsmasq service on 10.0.0.2:53 inside:

~~~
# ip netns exec qdhcp-c026ee53-a02a-4ee3-aec6-f11fa6b64a68 netstat -neopa
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name     Timer
tcp        0      0 10.0.0.2:53             0.0.0.0:*               LISTEN      0          36126      4372/dnsmasq         off (0.00/0/0)
tcp6       0      0 fe80::f816:3eff:fe98:53 :::*                    LISTEN      0          36128      4372/dnsmasq         off (0.00/0/0)
udp        0      0 10.0.0.2:53             0.0.0.0:*                           0          36125      4372/dnsmasq         off (0.00/0/0)
udp        0      0 0.0.0.0:67              0.0.0.0:*                           0          36119      4372/dnsmasq         off (0.00/0/0)
udp6       0      0 fe80::f816:3eff:fe98:53 :::*                                0          36127      4372/dnsmasq         off (0.00/0/0)
~~~

We do not have that information from `netstat -neopa` not running inside the namespace. Makes sense?

**Comment by bmr-cymru** [comment]
Merged in commit d576f79f451692fee9ea36a2a4aab4422b9a95c7.

**Pull request closed without merging**
