### PR TITLE
[containers_common] Gather container digests

### PR DESCRIPTION
**Pull request by badone**
It can be useful to have the digest for each container image for
verifying exact binary compatibility, etc.

Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [x] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [x] Is the subject and message clear and concise?
- [x] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [x] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [ ] If this commit closes an existing issue, is the line `Closes: #ISSUENUMBER` included in an independent line?
- [ ] If this commit resolves an existing pull request, is the line `Resolves: #PRNUMBER` included in an independent line?

### CODE REVIEW

**Comment by badone** [comment]
I added this as an additional command as it can create pretty wide output that has the normal wrapping issues and I reasoned it may be a good idea to leave the existing command as is where wrapping is less of an issue.

**Review by TurboTurtle — COMMENTED** [review]
So this will capture the command for _only_ non-root users given to the containers_common plugin via `-k containers_common.rootlessusers=foo`.

I think this should also then be added to the `podman` plugin, where we get the info as root as well.

**Comment by badone** [comment]
> So this will capture the command for _only_ non-root users given to the containers_common plugin via `-k containers_common.rootlessusers=foo`.
> 
> I think this should also then be added to the `podman` plugin, where we get the info as root as well.

I see. Let me look into this.

**Comment by badone** [comment]
@TurboTurtle How's that?

**Review by TurboTurtle — APPROVED** [review]

**Review by pmoravec — APPROVED** [review]

**Comment by badone** [comment]
Thanks.

**Pull request closed without merging**
