### PR TITLE
[atomic] Remove atomic policy

### PR DESCRIPTION
**Pull request by jcastill**
RHEL Atomic Host is RHEL7 only, and we since
we don't ship sos 4.* in RHEL 7, we can drop
this policy.

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [X] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?

### CODE REVIEW

**Comment by pmoravec** [comment]
Generally ACK, but isn't also `AtomicHost` class plugin (whole `sos/report/plugins/atomichost.py`) obsolete..?

**Comment by jcastill** [comment]
I thought about removing it as well, but then I doubted because we've never removed a plugin as far as I know, and I didn't know if there's a corner case where we could still get this plugin to work. But if you think there's no such case, I'll update the PR removing it as well.

**Comment by pmoravec** [comment]
Per https://access.redhat.com/solutions/4813941 , Atomic Host is EOL and on RHEL7 only.

@TurboTurtle, any thought about removing plugin?

**Comment by TurboTurtle** [comment]
I'll defer to you on removal of the plugin, but given the history of Atomic Host I don't have any concerns about removing it personally.

**Review by TurboTurtle — APPROVED** [review]

**Review by pmoravec — APPROVED** [review]

**Pull request merged**
