### PR TITLE
Fix various warnings from lgtm.com

### PR DESCRIPTION
**Pull request by pmoravec**
Most of issues reported in https://lgtm.com/projects/g/sosreport/sos/alerts/?mode=tree are fixed by the series of commits.

Unresolved ones (so far):

- Both errors https://lgtm.com/projects/g/sosreport/sos/alerts/?mode=list&severity=error sound like a false alarm (trying to fix it though)
- `else:` at https://github.com/sosreport/sos/blob/master/sos/plugins/__init__.py#L517 also false alarm
- calling child class methods in parent class constructor (https://lgtm.com/projects/g/sosreport/sos/alerts/?mode=tree&ruleFocus=10030085) - not sure how to resolve those

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?

### CODE REVIEW

**Comment by bmr-cymru** [comment]
This pull request **introduces 2 alerts** and **fixes 40** when merging 1834e7ff4ab40ac05fbe67fe6cce6bc332f12366 into d579fb745de0130132beea214edf85e597ffc54d - [view on LGTM.com](https://lgtm.com/projects/g/sosreport/sos/rev/pr-cbccc52b0c720c3bbfe450cfe52315a9d4d7a1aa)

**new alerts:**

* 2 for Unused import

**fixed alerts:**

* 20 for Unused import
* 4 for Module is imported with &#39;import&#39; and &#39;import from&#39;
* 4 for Variable defined multiple times
* 3 for Unreachable code
* 3 for Implicit string concatenation in a list
* 2 for Nested loops with same variable
* 1 for Module is imported more than once
* 1 for Comparison using is when operands support \_\_eq\_\_
* 1 for Unused local variable
* 1 for &#39;import \*&#39; may pollute namespace

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by bmr-cymru** [comment]
This pull request **fixes 40 alerts** when merging 5bf4424d1385304dc2223384a8697043dc974622 into 33054e81f50d501f1352028a5c4b44f785d7d9b7 - [view on LGTM.com](https://lgtm.com/projects/g/sosreport/sos/rev/pr-a379a93d4f88ee100b33cb93e42cf7833c4a7286)

**fixed alerts:**

* 20 for Unused import
* 4 for Module is imported with &#39;import&#39; and &#39;import from&#39;
* 4 for Variable defined multiple times
* 3 for Unreachable code
* 3 for Implicit string concatenation in a list
* 2 for Nested loops with same variable
* 1 for Module is imported more than once
* 1 for Comparison using is when operands support \_\_eq\_\_
* 1 for Unused local variable
* 1 for &#39;import \*&#39; may pollute namespace

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by BryanQuigley** [comment]
Didn't realize I was reviewing the whole 10 commits.  I like the comma change and removing XML so far.

Unfortunately the XML removal causes a regression (see travis). Lots of errors in collect().

**Comment by pmoravec** [comment]
The Travic CI build passed - see https://travis-ci.org/sosreport/sos/builds/490104168?utm_source=github_status&utm_medium=notification .

**Comment by bmr-cymru** [comment]
Merged with thanks ;-)

**Pull request closed without merging**
