### PR TITLE
Improved Foreman plugin, dropped Katello

### PR DESCRIPTION
**Pull request by lzap**
New option was added `-g` to skip collecting of generic resources (firewall, selinux, cpu, memory).

https://github.com/theforeman/foreman/blob/develop/script/foreman-debug

Since `katello-debug` is now part of `foreman-debug` (as a plugin), there is no need of separate sosreport plugin.

https://github.com/Katello/katello/blob/master/deploy/script/katello-debug.sh

@iNecas @ehelms to confirm please, thanks.

### CODE REVIEW

**Comment by bmr-cymru** [comment]
Patch is fine but please check the [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines) for patch header format.

I can rewrite the commit message for you if you're happy for me to add a Signed-off-by for you.

**Comment by lzap** [comment]
Re our discussion on foreman/katello and Satellite/Capsule, I think we need to add more packages. Here are our deployments types. We have new packages for Satellite 6.1 (patches are still pending review) which are adding `foreman-debug` and `katello-debug` (requres `foreman-debug`) subpackage.

Therefore I think we can change this to only check for `foreman-debug` package. If this one is present, than we can run the collection. It will be present on: Foreman, Katello upstream installs, Satellite 6 main node, Satellite 6 Capsule node.

Should I file a new PR for this?

I am fine with you correcting the commit message. Thanks!

**Comment by lzap** [comment]
* I think we need to add more packages* should be *I think we need to change "foreman" to "foreman-debug" package requirement.

**Comment by lzap** [comment]
Let me do brand new PR, I need to reclone sos repo, must have been renamed or something.

**Comment by bmr-cymru** [comment]
The tree was renamed from "sosreport" to "sos" last year (to make usable tarballs with GitHub's release mechanisms) but there should be redirects in place so push/pull etc. work.

I think we can handle it all in this one but np if you want to file a clean one.

**Comment by lzap** [comment]
Yeah that broke my "hub" tool integration, its a CLI to issue PRs. Nevermind. Filed a clean one against my new clone: https://github.com/sosreport/sos/pull/489

**Comment by bmr-cymru** [comment]
Thanks!

**Pull request closed without merging**
