### PR TITLE
[man] update to the location of presets

### PR DESCRIPTION
**Pull request by twoflowers**
updated the directory location for presets

Resolves: #3826

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [x] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [x] Is the subject and message clear and concise?
- [x] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [x] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [x] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?
- [x] Are all passwords or private data gathered by this PR [obfuscated](https://github.com/sosreport/sos/wiki/How-to-Write-a-Plugin#how-to-prevent-collecting-passwords)?

### CODE REVIEW

**Review by jcastill — APPROVED** [review]
LGTM just make sure you sign the commit and push again. 
For the other issue with ubuntu-24.04 - I think @arif-ali has re-started the job, so it may have been a transient issue.

**Comment by arif-ali** [comment]
That DCO check is a bit weird, there's a Signed-off-by, but the check is still failing

@TurboTurtle @pmoravec any thoughts on that?

**Review by arif-ali — APPROVED** [review]

**Review by pmoravec — APPROVED** [review]

**Comment by pmoravec** [comment]
No idea why the DCO check could fail..

**Comment by bmr-cymru** [comment]
The DCO check is kinda strict - the committer and signoff don't match in this case:

> Commit sha: [1130abb](https://github.com/sosreport/sos/pull/3829/commits/1130abb0f49cf99dc9c6b91bbe38ab8c33c8c601), Author: Thomas Martin, Committer: Thomas Martin; Expected "Thomas Martin [twoflowers@users.noreply.github.com](mailto:twoflowers@users.noreply.github.com)", but got "Tom Martin [thomas.r.martin@gmail.com](mailto:thomas.r.martin@gmail.com)".

https://github.com/sosreport/sos/pull/3829/checks?check_run_id=32378856825

**Review by TurboTurtle — APPROVED** [review]

**Comment by bmr-cymru** [comment]
fwiw there are still some instances of the old `/var` paths in the tree after this PR. Three in the sos-collect man page and one in the policies package:

```
$ git grep '\/var\/lib' | grep -v plugin
man/en/sos-collect.1:saved in JSON-formatted files under /var/lib/sos collect/<GROUP>.
man/en/sos-collect.1:Note that sos collect will only write group definitions to /var/lib/sos collect/
man/en/sos-collect.1:sos-collector will write a JSON-formatted file with name GROUP to /var/lib/sos collect/
sos/collector/clusters/openstack.py:INVENTORY = "/var/lib/mistral/overcloud/tripleo-ansible-inventory.yaml"
sos/collector/clusters/openstack.py:    /var/lib/mistral/overcloud/tripleo-ansible-inventory.yaml. Similarly, the
sos/policies/__init__.py:            or the default location at ``/var/lib/sos/presets``.
sos/policies/distros/redhat.py:    container_authfile = '/var/lib/kubelet/config.json'
```

**Comment by jcastill** [comment]
Thanks for the heads up @bmr-cymru . I've opened #3832 to deal with the rest of old references.

**Pull request merged**
