### PR TITLE
[scsi] lsscsi command options "-H" and "-i" 

### PR DESCRIPTION
**Pull request by NitinYewale**
---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [] Is the subject and message clear and concise?
- [] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?

### CODE REVIEW

**Comment by bmr-cymru** [comment]
Please follow the [contributor guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines) for patch formatting: the subject needs to be in `[<component>] change description` format, and all contributions require a DCO ("Signed-off-by") in the commit body (the Signed-off-by should be as made by `git commit -s`, and not intended further into the text)..

**Comment by bmr-cymru** [comment]
Thanks for filing a pull request. I don't really have an objection to adding these commands, although note that we do already capture some of this information in the form of `/sys` files. For hosts, refer to `sys/class/scsi_host` in the report:

```
# tree sys/class/scsi_host/
sys/class/scsi_host/
├── host0 -> ../../devices/pci0000:00/0000:00:17.0/ata1/host0/scsi_host/host0
├── host1 -> ../../devices/pci0000:00/0000:00:17.0/ata2/host1/scsi_host/host1
├── host2 -> ../../devices/pci0000:00/0000:00:17.0/ata3/host2/scsi_host/host2
├── host3 -> ../../devices/pci0000:00/0000:00:17.0/ata4/host3/scsi_host/host3
└── host4 -> ../../devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.2/host4/scsi_host/host4
```

The SCSI host attributes themselves are not currently captured from `/sys`: they are present in the report in the `sos_commands/scsi/udevadm_info_-a_.sys.class.scsi_host.hostN` files.

And we can add additional paths and attributes here if required.

For the `-i` addition, I think it would be better to replace the original `lsscsi` command: it is only adding one extra field, and we can force the file name to remain as `lsscsi` by using `suggested_filename` if desired:

```
# lsscsi 
[0:0:0:0]    disk    ATA      SanDisk SD7SB7S5 1001  /dev/sda 
[4:0:0:0]    disk    Canon    MG4200 series    0104  /dev/sdb 
```
vs:

```
# lsscsi -i
[0:0:0:0]    disk    ATA      SanDisk SD7SB7S5 1001  /dev/sda   -
[4:0:0:0]    disk    Canon    MG4200 series    0104  /dev/sdb   Canon_MG4200_series_960049-0:0
```

Note that the WWID information is also present in the `sos_commands/block/udevadm_info_-a_.<device>` files captured by the `block` plugin:

```
# grep wwid sos_commands/block/udevadm_info_-a_.dev.sda
    ATTRS{wwid}=="t10.ATA     SanDisk SD7SB7S512G1001                 163056402595        "
```

**Comment by bmr-cymru** [comment]
(although I am not sure why `udev` and `lsscsi` don't agree about the ATA SCSI ID in the above output :-) ).

**Comment by pmoravec** [comment]
@NitinYewale , could you please comment Bryn's feedback and incorporate relevant changes to your PR/commit?

Thanks.

**Comment by NitinYewale** [comment]
Hello,

Thank you for looking into this.

I agree that `lsscsi -H` may not be helpful, however adding `-i` gives WWID, hctl and sd names at the same place which helps to map these parameters with each other quickly.

Thank you,
Nitin Yewale

**Comment by pmoravec** [comment]
(sorry for not keeping @NitinYewale as the author of the commit; wrong merge strategy used that time)

**Pull request closed without merging**
