### PR TITLE
[kubernetes] add kube-system-log-files option, collect some kubelet files

### PR DESCRIPTION
**Pull request by champtar**
2 small enhancements to the kubernetes plugin

I'm open to proposal for another name than `kube-system-log-files`:
```
The following plugin options are available:
 kubernetes.all            on              collect all namespace output separately
 kubernetes.describe       on              collect describe output of all resources
 kubernetes.podlogs        on              capture stdout/stderr logs from pods
 kubernetes.podlogs-filter                 only collect logs from pods matching this pattern
 kubernetes.kube-system-log-files off             copy some kube-system pod logs without using the API
```

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [X] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?
- [X] Are all passwords or private data gathered by this PR [obfuscated](https://github.com/sosreport/sos/wiki/How-to-Write-a-Plugin#how-to-prevent-collecting-passwords)?

### CODE REVIEW

**Comment by pmoravec** [comment]
No secrets in newly collected data? (the env file: cant it contain some password?)?

Re the option name: I would prefer something shorter due to the alignment, what about `kube-system-logs` (still too long) or simply `kubelogs`?

I dont know kubernetes, so I evaluate the PR just from `sos` perspective.

**Comment by champtar** [comment]
> No secrets in newly collected data? (the env file: cant it contain some password?)?

On a kubeadm install, both files have chmod 644, and the parents folders have 755, so hopefully no secrets (I also looked at the docs but could have missed something)

> Re the option name: I would prefer something shorter due to the alignment, what about `kube-system-logs` (still too long) or simply `kubelogs`?

will change to `kubelogs`, I can't find something short and self descriptive, but the long description is displayed right next to it

> I dont know kubernetes, so I evaluate the PR just from `sos` perspective.

**Review by TurboTurtle — COMMENTED** [review]
Code looks fine, pending the PEP8 failure for line 100 (just needs to be shortened).

Before I ack however - is there a reason we shouldn't just be collecting these regularly? I.E. not gated behind an option and just a default collection by the plugin?

**Comment by champtar** [comment]
> Code looks fine, pending the PEP8 failure for line 100 (just needs to be shortened).
> 
> Before I ack however - is there a reason we shouldn't just be collecting these regularly? I.E. not gated behind an option and just a default collection by the plugin?

Default kube log rotation is 10MB per file and keep 5 files, we collect 4 containers,
so that's 200MB uncompressed. Also it's redundant with podlogs option when API is working.

**Review by TurboTurtle — APPROVED** [review]

**Pull request merged**
