### PR TITLE
[openvswitch] Adding 6wind commands

### PR DESCRIPTION
**Pull request by jjansky1**
This adds the 6wind's commands to openvswitch plugin.

Backporting #2242 into legacy-3.9.

Related: #2248
Related: #2242
Resolves: #2484
Resolves: #2248

Signed-off-by: Jan Jansky <jjansky@redhat.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [ ] If this commit closes an existing issue, is the line `Closes: #ISSUENUMBER` included in an independent line?
- [X] If this commit resolves an existing pull request, is the line `Resolves: #PRNUMBER` included in an independent line?

### CODE REVIEW

**Comment by jjansky1** [comment]
As #2242 was closed in favor of #2248 and #2248 is not moving at all i am proposing new PR with implemented recommendation from @pmoravec. Please review this PR and if it will be merged please close also #2248.

@valleedelisle can you please verify if commit is adding what you wanted?

**Review by pmoravec — APPROVED** [review]
As far as I checked, proper backport of both upstream PRs - ack.

**Review by TurboTurtle — APPROVED** [review]

**Comment by valleedelisle** [comment]
This looks good to me but unfortunately, I don't have an environment anymore to test this.

**Comment by TurboTurtle** [comment]
Merged into `legacy-3.9` via f1a46c3

**Pull request closed without merging**
