### PR TITLE
[chrony] add chrony plugin

### LINKED ISSUE #539: [chrony] add chrony plugin
Chronyd (as an alternative to ntpd daemon) configuration should be gathered by sos.

### PR DESCRIPTION
**Pull request by pmoravec**
Resolves #539

Authored by Justin Stephenson @ Red Hat

Signed-off-by: Pavel Moravec <pmoravec@redhat.com>

### CODE REVIEW

**Comment by battlemidget** [comment]
ACK, i'd like to get the Ubuntu version included as well.

**Comment by pmoravec** [comment]
Re Ubuntu version: Sure, np. Is there something specific to it or just adding ", DebianPlugin, UbuntuPlugin" twice is enough?

**Comment by battlemidget** [comment]
@pmoravec i'll need to install it and see what it needs, if the paths are the same it would just be a matter of adding those plugin classes

**Comment by bmr-cymru** [comment]
Can you get permission for a DCO from Justin? That's the point of the S-o-b lines - to certify that you wrote (or handled) the original code.

Just `commit --amend` and `push --force`.

**Comment by bmr-cymru** [comment]
You can also use `--author` with the amend to set the correct authorship information in git.

**Comment by battlemidget** [comment]
LGTM I can add the Ubuntu specifics later

**Comment by bmr-cymru** [comment]
Merged as commit b6e6a4d1ce4beae74cb0123bd7c48d0828d120ec.

**Pull request closed without merging**
