### PR TITLE
[man]:Remove ticket-number option in man page

### PR DESCRIPTION
**Pull request by mamatha4**
This patch is to delete ticket-number option
in man page for sosreport

ticket-number option is not supporting in sosreport
so remove it from man page
Note: ticket-number option is not there in help message

Signed-off-by: Mamatha Inamdar <mamatha4@linux.vnet.ibm.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [ ] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [ ] Is the subject and message clear and concise?
- [ ] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [ ] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [ ] If this commit closes an existing issue, is the line `Closes: #ISSUENUMBER` included in an independent line?
- [ ] If this commit resolves an existing pull request, is the line `Resolves: #PRNUMBER` included in an independent line?

### CODE REVIEW

**Comment by pmoravec** [comment]
Good catch; I think it is worth removing some relicts of `ticket_number` in code as well?

    $ grep ticket -rn sos
    sos/policies/distros/suse.py:28:        self.ticket_number = ""
    sos/policies/distros/debian.py:20:    ticket_number = ""
    sos/policies/distros/debian.py:31:        self.ticket_number = ""
    sos/policies/distros/redhat.py:53:        self.ticket_number = ""
    $

Just assignments that are never used.. (interesting that LGTM does not detect the above dummy assignemnts..?)

**Comment by mamatha4** [comment]
Thanks for the review,
ok, I searched only "ticket-number" in sos and updated man page
Thanks for the update.. will remove ticket_number in code and send new version of patch set

**Comment by mamatha4** [comment]
After removing ticket_number in code, We are observing LGTM errors

**Comment by pmoravec** [comment]
LGTM didnt run its tests as it detected merge conflits; per https://github.com/mamatha4/sos/tree/manpage-update , your branch is 271 commits behind sosreport:master.

Could you please merge the changes or fast forward (though ff might fail, if some of the 271 commits is in conflict with the new 2 commits)? Or optionally, do the same manually via reseting your branch to current sos master, and then adding the two commits?

**Comment by pmoravec** [comment]
No need to close the PR :) Anyway, I opened mine for the same and mention yours credit. (@TurboTurtle , if/when you will merge the PR, let replace my name by @mamatha4 if possible)

**Comment by mamatha4** [comment]
Sorry by mistake I deleted branch instead of resetting and PR got closed.. thanks for the PR #2375

**Pull request closed without merging**
