### PR TITLE
Work to fix issue 337

### PR DESCRIPTION
**Pull request by sferich888**
This should get the conversation started on what is the best approach to fixing the missing global timeout option.

### CODE REVIEW

**Comment by pmoravec** [comment]
I think you need to pass the option settings to Plugin class. "self._timeout" in sos.py is some different object than "self._timeout" in Plugin class :)

**Comment by bmr-cymru** [comment]
Please call your pulls something meaningful, so that other users don't have to go elsewhere to find out what "issue 337" actually means.

**Comment by bmr-cymru** [comment]
There is a `pep8` error and multiple test suite failures. It's a lot easier to test this stuff locally with the `pep8` command and `python-nose` than to go all around the houses to have Travis do it for you.

Also, if you are going to work on a major, long-standing issue, it is a really good idea to let the other sos developers know that (in the issue) so that you can coordinate with them and avoid either duplicative work, or setting off in a direction that isn't favoured.

**Comment by bmr-cymru** [comment]
Your commit is called " Work to fix issue 337"? Really? Once again: [contributor guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines).

**Comment by bmr-cymru** [comment]
There were a lot of fixes needed for this identified during review. We will be releasing 3.4 next month: I would like to include this change but the PR has not been updated to reflect review comments since August last year.

Please push an updated HEAD for this branch if you would like to see this included in the release.

**Comment by bmr-cymru** [comment]
We will be releasing 3.4 next month: I would like to include this change but the PR has not been updated to reflect review comments since October last year. The branch is also currently failing QE.

Please push an updated HEAD for this branch if you would like to see this included in the release.

**Comment by bmr-cymru** [comment]
No response in > 12 months: closing.

**Pull request closed without merging**
