### PR TITLE
[cleaner] Remove binary files by default

### PR DESCRIPTION
**Pull request by TurboTurtle**
Binary files generally speaking cannot be obfuscated, and as such we
should remove them from archives being obfuscated by default so that
sensitive data is not mistakenly included in an obfuscated archive.

This commits adds a new `--keep-binary-files` option that if used will
keep any encountered binary files in the final archive. The default
option of `false` will ensure that encountered binary files are removed.

The number of removed binary files per archive is reported when
obfuscation is completed for that archive.

Closes: #2478
Resolves: #2524

Signed-off-by: Jake Hunsaker <jhunsake@redhat.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [x] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [x] Is the subject and message clear and concise?
- [x] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [x] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [x] If this commit closes an existing issue, is the line `Closes: #ISSUENUMBER` included in an independent line?
- [x] If this commit resolves an existing pull request, is the line `Resolves: #PRNUMBER` included in an independent line?

### CODE REVIEW

**Comment by BryanQuigley** [comment]
Quick thoughts...
I would just do - anything with .tar anywhere in it.  (We don't care what kind..)

Also, the .journal / .journal~ files. 

Binary data can still be written to files identified as text.

**Comment by TurboTurtle** [comment]
Updated the regex list for auto-removal. Refined the exception handling to just `UnicodeDecodeError` for failure to read binary data from a text file.

**Comment by TurboTurtle** [comment]
Noticed the new option wasn't exposed via `collect` - now it is

**Review by pmoravec — APPROVED** [review]
ACK with two minor comments:

- `file_is_binary` is worth having a short explanation that read() method on text file (`open(..'tr')`) fails for binary content - it took me a while to get this.
- worth mentioning this change in default behaviour in release notes of 4.2?

**Comment by TurboTurtle** [comment]
> ACK with two minor comments:
> 
> * `file_is_binary` is worth having a short explanation that read() method on text file (`open(..'tr')`) fails for binary content - it took me a while to get this.

Ack, I'll add a comment before merge.

> * worth mentioning this change in default behaviour in release notes of 4.2?

Oh, absolutely.

**Pull request merged**
