### PR TITLE
[nvme] Added few new spec paths in this plugin

### PR DESCRIPTION
**Pull request by ajaymohite25**
Added few new spec paths in this plugin
---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [X] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?

### CODE REVIEW

**Comment by arif-ali** [comment]
Can you rebase, and only have your commit please

**Comment by jcastill** [comment]
These are two different plugins, and while related, do we really need a single commit for them? Wouldn't it be better two commits and two PRs? From the storage point of view I don't think it makes sense to group them.

**Comment by ajaymohite25** [comment]
> Can you rebase, and only have your commit please

I am working on it, actually i pulled out this branch from it, so somehow the 2 commits happed, will see i might delete this PR and create fresh branch form master...

**Comment by arif-ali** [comment]
> > Can you rebase, and only have your commit please
> 
> I am working on it, actually i pulled out this branch from it, so somehow the 2 commits happed, will see i might delete this PR and create fresh branch form master...

I think you accidentally added the commit from #3503 into this. You should be able to rebase with `main` and should be able to push to your branch

**Pull request closed without merging**
