### PR TITLE
[foreman] Fix invalid yaml files

### LINKED ISSUE #1876: [foreman] Fix YAML files collected syntax
For YAML, valid values are alphanumeric or should  start with an underscore. 

Foreman Plugin replaces senstive data values with ******* which is an invalid yaml value. So the yaml files collected are not valid YAMLs. Plugin should replace sensitive data with something which yaml considers as a valid value. 

Invalid YAML files corrected currenlty
```
for i in $(find /var/tmp/sosreport-sat65-2019-12-04-sgpzxhy/etc/foreman* -name "*.yaml" -o -name "*yml" ); do echo "`/syntax-check/yaml_check.py $i`   $i"; done | egrep invalid
invalid   /var/tmp/sosreport-sat65-2019-12-04-sgpzxhy/etc/foreman/database.yml
invalid   /var/tmp/sosreport-sat65-2019-12-04-sgpzxhy/etc/foreman/plugins/katello.yaml
invalid   /var/tmp/sosreport-sat65-2019-12-04-sgpzxhy/etc/foreman/settings.yaml
invalid   /var/tmp/sosreport-sat65-2019-12-04-sgpzxhy/etc/foreman-installer/scenarios.d/foreman.yaml
invalid   /var/tmp/sosreport-sat65-2019-12-04-sgpzxhy/etc/foreman-installer/scenarios.d/foreman-proxy-content-answers.yaml
invalid   /var/tmp/sosreport-sat65-2019-12-04-sgpzxhy/etc/foreman-installer/scenarios.d/foreman-proxy-content.yaml
invalid   /var/tmp/sosreport-sat65-2019-12-04-sgpzxhy/etc/foreman-installer/scenarios.d/katello-answers.yaml
invalid   /var/tmp/sosreport-sat65-2019-12-04-sgpzxhy/etc/foreman-installer/scenarios.d/katello.yaml
invalid   /var/tmp/sosreport-sat65-2019-12-04-sgpzxhy/etc/foreman-installer/scenarios.d/capsule-answers.yaml
invalid   /var/tmp/sosreport-sat65-2019-12-04-sgpzxhy/etc/foreman-installer/scenarios.d/capsule.yaml
invalid   /var/tmp/sosreport-sat65-2019-12-04-sgpzxhy/etc/foreman-installer/scenarios.d/satellite-answers.yaml
invalid   /var/tmp/sosreport-sat65-2019-12-04-sgpzxhy/etc/foreman-installer/scenarios.d/satellite.yaml
invalid   /var/tmp/sosreport-sat65-2019-12-04-sgpzxhy/etc/foreman-installer/scenarios.d/last_scenario.yaml
invalid   /var/tmp/sosreport-sat65-2019-12-04-sgpzxhy/etc/foreman-proxy/settings.d/dns_nsupdate.yml
invalid   /var/tmp/sosreport-sat65-2019-12-04-sgpzxhy/etc/foreman-proxy/settings.d/dns_nsupdate_gss.yml
invalid   /var/tmp/sosreport-sat65-2019-12-04-sgpzxhy/etc/foreman-proxy/settings.d/puppet_proxy_legacy.yml
invalid   /var/tmp/sosreport-sat65-2019-12-04-sgpzxhy/etc/foreman-proxy/settings.d/puppet_proxy_puppet_api.yml
invalid   /var/tmp/sosreport-sat65-2019-12-04-sgpzxhy/etc/foreman-proxy/settings.d/puppet_proxy_ssh.yml
invalid   /var/tmp/sosreport-sat65-2019-12-04-sgpzxhy/etc/foreman-proxy/settings.d/puppetca_token_whitelisting.yml
invalid   /var/tmp/sosreport-sat65-2019-12-04-sgpzxhy/etc/foreman-proxy/settings.d/realm_freeipa.yml
invalid   /var/tmp/sosreport-sat65-2019-12-04-sgpzxhy/etc/foreman-proxy/settings.d/remote_execution_ssh.yml
invalid /var/tmp/sosreport-sat65-2019-12-04-sgpzxhy/etc/foreman-proxy/settings.yml
```

### PR DESCRIPTION
**Pull request by Rohan21Lobo**
Fixes #1876

Signed-off-by: Rohan Arora <roarora@redhat.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [ X] Is the subject and message clear and concise?
- [ X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [ X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [ X] If this commit closes an existing issue, is the line `Closes: #ISSUENUMBER` included in an independent line?
- [ ] If this commit resolves an existing pull request, is the line `Resolves: #PRNUMBER` included in an independent line?

### CODE REVIEW

**Comment by Rohan21Lobo** [comment]
Separated conf regex and still used ******* to maintain consistency with overall sosreport.

Can changer over all for yaml|yml|conf if recommended.

**Comment by bmr-cymru** [comment]
Similar comment to #1880 - completely understand the desire to have correct syntax in the captured YAML files, but it's not clear to me that we really need to change the substitution string, rather than the structure of the modification (to preserve it as a string in YAML syntax)?

If we are going to introduce a new substitution string then I think we should aim to make it standard across all plugins as far as each configuration format allows.

**Comment by Rohan21Lobo** [comment]
I am good with replacing the sensitive data in YAML with quoted stars 
```
"********"
```
Single or double? YAML adheres escape sequence in double quotes but it should not mater whatever quotes we use since we are replacing everything inside it with *s. 
@pmoravec @bmr-cymru  Thoughts?

**Comment by pmoravec** [comment]
Double quotes sounds good but whatever will constitute a valid yaml file is fine for me.

**Comment by Rohan21Lobo** [comment]
Repushed with *******s 
@pmoravec @bmr-cymru  Please review

**Pull request closed without merging**
