### PR TITLE
[snappy] new plugin to show snappy info

### PR DESCRIPTION
**Pull request by BryanQuigley**
Adds a new plugin that lists information about snappy, including:
 * all installed snaps with version info (snap list --all)
 * Snappy's own version info (snap --version)
 * status info and logs for the snapd daemon
 * List snappy system changes (snap changes)

Signed-off-by: Bryan Quigley <bryan.quigley@canonical.com>

### CODE REVIEW

**Comment by battlemidget** [comment]
ack from me, thanks @BryanQuigley

**Comment by bmr-cymru** [comment]
Ack to the plugin code - thanks. Not sure about `snappy` in Fedora - I can have a quick look around though.

**Comment by BryanQuigley** [comment]
I checked with Fedora 25 and Debian stretch and both work as expected so modified to include them.

**Comment by bmr-cymru** [comment]
WFM on f24:

```
# sosreport -v --batch -o snappy --build

sosreport (version 3.4)

This command will collect system configuration and diagnostic
information from this Fedora system. An archive containing the collected
information will be generated in /var/tmp/sos.U1PC8E.

For more information on the Fedora Project visit:

  https://fedoraproject.org/

The generated archive may contain data considered sensitive and its
content should be reviewed by the originating organization before being
passed to any third party.

No changes will be made to system configuration.


 Setting up archive ...
[archive:TarFileArchive] initialised empty FileCacheArchive at '/var/tmp/sos.U1PC8E/sosreport-localhost.localdomain-20170427172902'
[sos.sosreport:setup] executing 'sosreport -v --batch -o snappy --build'
 Setting up plugins ...
[plugin:snappy] added cmd output 'systemctl status snapd.service'
[plugin:snappy] added cmd output 'snap list --all'
[plugin:snappy] added cmd output 'snap --version'
[plugin:snappy] added cmd output 'snap changes'
[plugin:snappy] added cmd output 'journalctl --no-pager  --unit snapd'
 Running plugins. Please wait ...

  Running 1/1: snappy...        
[plugin:snappy] collecting output of 'systemctl status snapd.service'
[plugin:snappy] collecting output of 'snap list --all'
[plugin:snappy] collecting output of 'snap --version'
[plugin:snappy] collecting output of 'snap changes'
[plugin:snappy] collecting output of 'journalctl --no-pager  --unit snapd'


sosreport build tree is located at : /var/tmp/sosreport-localhost.localdomain-20170427172902
```

**Pull request merged**
