### PR TITLE
[openstack_ansible] Add OpenStack-Ansible plugin

### PR DESCRIPTION
**Pull request by major**
This patch adds a plugin to retrieve configuration content, Ansible
inventory, and cached facts from OpenStack-Ansible deployment nodes.

Signed-off-by: Major Hayden <major@mhtx.net>

### CODE REVIEW

**Comment by cloudnull** [comment]
Very nice addition! I think this would be fantastic to get into the hands of OSA operators.

**Comment by BjoernT** [comment]
Please add the old legacy directories too, at least /etc/rpc_deploy

**Comment by bmr-cymru** [comment]
Curious more than anything, but the only mention of "ansible" in this plugin, is in the name?

Would "openstack_deploy" be a better name, or is there some possibility of a non-ansible backed component taking that name?

Only asking as currently the plugin looks a bit strange to the uninitiated and may cause confusion with other users of Ansible or OpenStack.

**Comment by major** [comment]
Hey @bmr-cymru, thanks for taking a look. The project itself is called OpenStack-Ansible:

* https://github.com/openstack/openstack-ansible
* http://docs.openstack.org/developer/openstack-ansible/

I'm happy to rename it to something else if that helps.

**Comment by bmr-cymru** [comment]
@major that's fine then - thanks for the links. I was mostly curious as I was expecting to get another pull request around this time for a new plugin for "Ansible Ansible" (arrived as PR #931). Since this one has the "Openstack" prefix (and takes that name from the upstream project) there's no conflict here, even if it looks odd to the uninitiated.

**Comment by bmr-cymru** [comment]
Couple of minor issues (I can fix these up when I merge):

* `profiles` member commented out
* `files` member missing required `,` for a 1-member tuple

**Pull request closed without merging**
