### PR TITLE
Fix dc-connect winbind logfile path for samba plugin

### PR DESCRIPTION
**Pull request by gd**
Guenther

Signed-off-by: Guenther Deschner <gd@samba.org>

### CODE REVIEW

**Comment by battlemidget** [comment]
@gd thank you for the PR! Do you mind amending that commit message to contact the plugin in this format:

```
[samba] Fix dc-connect winbind logfile path
```

This is from our https://github.com/sosreport/sos/wiki/Contribution-Guidelines#submitting-pull-requests. I'm +1 otherwise though

**Comment by gd** [comment]
Oh sure, I wasn't aware of that guideline. I ammended the commit message and repushed.

**Comment by pmoravec** [comment]
+1

**Comment by bmr-cymru** [comment]
👍

**Pull request merged**
