### PR TITLE
[processor.py] Added cpuid command http://www.etallen.com/cpuid.html

### PR DESCRIPTION
**Pull request by jirka-h**
Hello, 

I propose to add output of cpuid utility to sosreport. The source code of cpuid utility can be found here: http://www.etallen.com/cpuid.html

It provides the details about CPU which no other utility in sosreport does. cpuid is provided as package in the most Linux distributions. 

Thanks for considering it.
Jirka

### CODE REVIEW

**Comment by bmr-cymru** [comment]
Please follow the [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines):

* Subject format
* Commit message
* Signed-off-by

**Comment by pmoravec** [comment]
:thumbsup: maybe it makes sense to squeeze the two simple commits into one.

**Comment by jirka-h** [comment]
What would be the best way to squeeze the commits into one? It seems like it would be best to delete this PR and create a new one instead with one commit instead?

**Comment by battlemidget** [comment]
Just rebase and squash one commit into the other and force push the update to your branch.

**Comment by jirka-h** [comment]
Thanks for the hint. I have used 

git reset --soft HEAD~2
git commit

to squash the commits.

**Comment by bmr-cymru** [comment]
Thanks, that works - you should check out `git rebase -i` some time though - it'll allow you to do that plus waaaay more (re-order commits, amend arbitrary commits, split and combine commits etc.).

**Comment by jirka-h** [comment]
I'm just reading the documentaion for git rebase

**Comment by bmr-cymru** [comment]
Merged in commit fe3f9864c380e1bcd211368b75d9a27ad694a0a9

**Pull request closed without merging**
