### PR TITLE
[openstack_neutron] Code refactor

### PR DESCRIPTION
**Pull request by psachin**
- Removed openstack_neutron.Networking.get_interface_name() as it was
  exact copy of networking.get_eth_interfaces()
- Renamed get_eth_interfaces() to get_interface_name(). This sounds more generic
  considering networking.Networking as base class for networking

- Suggestion: Instead of importing Networking class from networking.py, we can make Networking as base class and import it from plugins instead.

Signed-off-by: Sachin Patil <psachin@redhat.com>

### CODE REVIEW

**Comment by bmr-cymru** [comment]
Looks good - @lyarwood does this conflict with any of your current work? If not I'll go ahead and merge.

**Comment by lyarwood** [comment]
@bmr-cymru  Yeah the Neutron changes conflict, 267af536 just dropped get_interface_name from the Neutron plugin entirely.

**Comment by bmr-cymru** [comment]
@psachin  @lyarwood 

What's the status of this PR now? Is it obsolete following the changes from commit 267af53, or does it just need rebasing to the new plugin?

If the merge commit in the comment from May addresses this, that's fine, but it will need to be rebased and force-pushed - no merge commits are allowed in the master branch.

**Comment by psachin** [comment]
@bmr-cymru @lyarwood 

As `get_interface_name` is completely dropped in 267af53, there is no point in merging. We should close this PR

**Comment by bmr-cymru** [comment]
Thanks all.

**Pull request closed without merging**
