### PR TITLE
[openstack] New Ironic plugin.

### PR DESCRIPTION
**Pull request by lyarwood**
https://wiki.openstack.org/wiki/Ironic

Signed-off-by: Lee Yarwood <lyarwood@redhat.com>

### CODE REVIEW

**Comment by battlemidget** [comment]
Here are the packages for ironic

```
ironic-api/vivid-updates 2015.1.0-0ubuntu1 all
  Openstack bare metal provisioning service - API

ironic-common/vivid-updates 2015.1.0-0ubuntu1 all
  Openstack bare metal provisioning service - daemons

ironic-conductor/vivid-updates 2015.1.0-0ubuntu1 all
  Openstack bare metal provisioning service - conductor

python-ironic/vivid-updates 2015.1.0-0ubuntu1 all
  Openstack bare metal provisioning service - Python library

python-ironicclient/vivid 0.3.1-0ubuntu1 all
  Python bindings for the Ironic API
```

**Comment by bmr-cymru** [comment]
Subject should be like:

```
[openstack_ironic] add new plugin
```

Also a line or two of outline in the commit body is helpful; people may be reading at a terminal and it should be easy to succinctly describe what the plugin supports (esp. if it's got to have such a tantalising name..).

**Comment by lyarwood** [comment]
@bmr-cymru @battlemidget this should be ready for review now.

**Comment by battlemidget** [comment]
:+1: lgtm thanks

**Pull request closed without merging**
