### PR TITLE
[saphana] add SAP HANA plugin

### PR DESCRIPTION
**Pull request by lmiccini**
proposing a plugin to collect basic info about SAP HANA.

Signed-off-by: Luca Miccini <lmiccini@redhat.com>

### CODE REVIEW

**Comment by bmr-cymru** [comment]
@lmiccini not really; HANA users still have the `rm` command. From a support point of view you cannot ever assume that a given path will exist. That's why you have to code defensively for file system operations.

**Comment by lmiccini** [comment]
@bmr-cymru I almost forgot about this pull request... I added a couple of checks, hopefully is more robust now.

**Comment by bmr-cymru** [comment]
@lmiccini great, thanks for the very quick turnaround! No need to rebase again - I'll do a final one before I merge (it's trivial anyway since the patch adds a new plugin).

**Comment by lmiccini** [comment]
@bmr-cymru thank you for your feedback :+1:

**Comment by bmr-cymru** [comment]
Sorry it was a bit asynchronous :8ball:

**Comment by bmr-cymru** [comment]
Closed in commit e768bf71c96317bc64b643ab9262cb88f1d9058c.

**Pull request closed without merging**
