### PR TITLE
[memcached] Collect from memcached using the tool

### PR DESCRIPTION
**Pull request by arif-ali**
---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [x] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [x] Is the subject and message clear and concise?
- [x] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [x] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [ ] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?
- [ ] Are all passwords or private data gathered by this PR [obfuscated](https://github.com/sosreport/sos/wiki/How-to-Write-a-Plugin#how-to-prevent-collecting-passwords)?

### CODE REVIEW

**Review by TurboTurtle — APPROVED** [review]
LGTM, though it seems strange to me that `memcached-tool` wouldn't be in $PATH when included as a packaged executable (whereas if you were installing from source, totally understandable).

**Comment by arif-ali** [comment]
> LGTM, though it seems strange to me that `memcached-tool` wouldn't be in $PATH when included as a packaged executable (whereas if you were installing from source, totally understandable).

It's in the path for rocky8/rocky9 (which I just tested) which I am presume will be the case for RH based systems but it is not for ubuntu. So, happy to change that for the `RedHatPlugin` if you prefer

**Comment by TurboTurtle** [comment]
> > LGTM, though it seems strange to me that `memcached-tool` wouldn't be in $PATH when included as a packaged executable (whereas if you were installing from source, totally understandable).
> 
> It's in the path for rocky8/rocky9 (which I just tested) which I am presume will be the case for RH based systems but it is not for ubuntu. So, happy to change that for the `RedHatPlugin` if you prefer

Didn't need to change, was just making an observation that I am surprised that the Ubuntu packaging wouldn't drop it in $PATH.

Either way though, this looks good to me.

**Comment by arif-ali** [comment]
> 
> Didn't need to change, was just making an observation that I am surprised that the Ubuntu packaging wouldn't drop it in $PATH.
> 
> Either way though, this looks good to me.

It looked more elegant, and less code.

Reading up on it, apparently it can cause a pause on the cache gathering/setting if this tool is run, so that could be the reason for not adding it to the $PATH. Maybe a warning is at hand here, wdyt?

**Comment by TurboTurtle** [comment]
If it can cause an interruption to normal operation I think we'd ideally gate it behind a plugin option, but there isn't much else this plugin collects and I doubt that the general use case for support folks would be well served without this info. Maybe a warning would suffice, let's dig in a little bit.

Is there any indication on how likely a pause or how long the pause could be (full duration of the command, or is it very brief at the beginning of execution), or for that matter is it _any_ time this command is run, or only for specific sub commands like `dump`?

**Comment by arif-ali** [comment]
Reading up on this if we run `star sizes` then there could be issues as per https://github.com/memcached/memcached/wiki/Commands#stats-sizes. As we're not passing that command, we should be ok.

So I think, this should be good to go

**Pull request merged**
