### PR TITLE
Capture more of modprobe.d and initrd.img

### PR DESCRIPTION
**Pull request by mfoliveira**
This user with an unbootable system had a problematic module option
in `/lib/modprobe.d/something.conf` that got in `/boot/initrd.img-*`.

The sosreport didn't reveal it because it didn't capture `/lib/modprobe.d`
(just `/etc/modprobe.d`) nor `lsinitramfs` on Ubuntu.

These patches improves that in the `kernel` and `boot` plugins.

Thanks!

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [x] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [x] Is the subject and message clear and concise?
- [x] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [x] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [-] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?

### CODE REVIEW

**Review by TurboTurtle — APPROVED** [review]
LGTM

**Comment by mfoliveira** [comment]
Hi @TurboTurtle , thanks for reviewing!

Just following up -- does this PR needs a 2nd reviewer/approval per the [Contribution Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines#maintainers)?

I'd be happy to mention Pavel if that's needed; just trying to save a ping if it's not (e.g., single reviewer would be acceptable for this PR as well).

P.S.: Sorry if you were already / are going to get back to this later anyway.

Thanks!

**Comment by TurboTurtle** [comment]
Yep, this needs a second maintainer ack. Pavel is out this week, so one of the Debian/Ubuntu maintainers could also provide the second ack. From a code change this is fine and straightforward, but since is a Deb/Ubuntu focused changed according to the commit messages, I'd like to have a second set of eyes as a sanity check before merging.

**Comment by BryanQuigley** [comment]
I haven't found why there is a [difference](https://wiki.debian.org/Initrd).. but on on Debian the initrd symlink does not exist in boot, it's in /, so.
lsinitramfs -l /initrd.img

Otherwise looks good.

**Comment by mfoliveira** [comment]
> I haven't found why there is a [difference](https://wiki.debian.org/Initrd).. but on on Debian the initrd symlink does not exist in boot, it's in /, so. lsinitramfs -l /initrd.img
> 
> Otherwise looks good.

@BryanQuigley 

Thanks!  I added `lsinitramfs -l /initrd.img`.

I actually figured this symlink existed in my system, but was broken (apparently due to a release upgrade).
So I also added `ls -l /initrd.img /boot/initrd.img` so to also document that, as it'd be helpful for boot issues.

The commit message has been updated to reflect both points in text and testing.

**Review by BryanQuigley — APPROVED** [review]
LGTM

**Pull request merged**
