### PR TITLE
[IBM] Remove unneeded policies

### PR DESCRIPTION
**Pull request by BryanQuigley**
These policies haven't done anything since
IndependentPlugin was made a more common default.

Closes: #2470
Resolves: #2474

Signed-off-by: Bryan Quigley <code@bryanquigley.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [X] If this commit closes an existing issue, is the line `Closes: #ISSUENUMBER` included in an independent line?
- [X] If this commit resolves an existing pull request, is the line `Resolves: #PRNUMBER` included in an independent line?

### CODE REVIEW

**Comment by BryanQuigley** [comment]
Wait for feedback in Issue before merging.

**Comment by TurboTurtle** [comment]
We'll also want to removing the tagging classes from `sos/report/plugins/__init__.py`.

**Comment by bmr-cymru** [comment]
Can we be a bit more precise about the language in the commit message? The commits are not removing any of the IBM *policies* (which would concern me, if we did not have agreement from the groups that submitted them), they are just deleting the IBM-specific tagging classes that they define.

I think the commit subject should be something like "[plugins,policy] remove IBM policy tagging classes".

Also, if you are going to delete those classes then you also need to remove the references to them from the corresponding policy class to avoid breaking stuff:

```python
class PowerKVMPolicy(RedHatPolicy):
    distro = "PowerKVM"
    vendor = "IBM"
    vendor_url = "http://www-03.ibm.com/systems/power/software/linux/powerkvm"

    def __init__(self, sysroot=None):
        super(PowerKVMPolicy, self).__init__(sysroot=sysroot)
        self.valid_subclasses = [PowerKVMPlugin, RedHatPlugin]
```

```python
class ZKVMPolicy(RedHatPolicy):
    distro = "IBM Hypervisor"
    vendor = "IBM Hypervisor"
    vendor_url = "http://www.ibm.com/systems/z/linux/IBMHypervisor/support/"

    def __init__(self, sysroot=None):
        super(ZKVMPolicy, self).__init__(sysroot=sysroot)
        self.valid_subclasses = [ZKVMPlugin, RedHatPlugin]
```

One concern I have with making changes to this area is that I don't think any of us have access to an environment where we can test these changes on the systems they affect. I would suggest trying to reach out to someone at IBM to find out if the policies are still relevant/used in the corresponding products, and if so to get these changes tested before the next release. If they aren't being used any more then we might as well cull the whole thing.

**Comment by BryanQuigley** [comment]
Sorry, I could have been more clear - my first comment was we should wait some time to see if we hear back from IBM per #2470.

This commit does fully remove the IBM policy classes you mention. The links are one of the few changes they make and they have been broken for some time.

**Comment by bmr-cymru** [comment]
IBM always contributed to sos more via the mailing list than via GitHub. I think it would be courteous to reach out to them and get positive confirmation that this is no longer used before deleting it. The archives give some email addresses to try, and failing that me or @TurboTurtle should be able to find a contact.

Afaik the products still exist and although they have not been keeping the upstream maintenance up on these I think removing support is one place where it's better to ask for permission than forgiveness.

If there's no response from anyone at IBM after sending that notice then it's appropriate to just drop it.

**Comment by TurboTurtle** [comment]
I've been attempting to find an up to date contact internally, no responses yet. I'll try again and send a devel list email as well later today/tomorrow to see if we can drum something up.

**Review by TurboTurtle — APPROVED** [review]

**Pull request closed without merging**
