### PR TITLE
[license] update FSF address

### PR DESCRIPTION
**Pull request by sandrobonazzola**
Resolve issue #886

Change-Id: I0496cf4f4dbee33a8a6c52b2b6a1a3271834fb6f
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>

### CODE REVIEW

**Comment by bmr-cymru** [comment]
Hah! Well done! 👍 This was actually on my list for this week, so thank you for saving me from some very dull work... ;-)

**Comment by bmr-cymru** [comment]
Please use the `[component] short description of change` format for your commit message - for this type of change the `component` is `global`.

Also, I'm a bit confused by the "Change-Id" in your commit? If it's a git commit hash (unless it's referencing an already upstream commit, e.g. to note a regression), it is best not to include those in commit messages as they may change via rebasing before the code is merged). That said, this doesn't seem to match any known commit ID, and Google has not heard of it - it's probably best to just drop it from the message.

Anyway: appreciate your taking the time to do this, I'll get this merged as soon as those minor nits are done.

**Comment by bmr-cymru** [comment]
Actually - don't worry about it, I can sort it out when I merge the changes (I'll keep the commit author the same, of course).

Cheers,

**Comment by sandrobonazzola** [comment]
ok, so nothing on my side, feel free to merge whenever you want :-)

**Comment by bmr-cymru** [comment]
Merged in commit  24dc8e52db20bf3333c9a6e1262a7c309473549f:

```
commit 24dc8e52db20bf3333c9a6e1262a7c309473549f
Author: Sandro Bonazzola <sbonazzo@redhat.com>
Date:   Mon May 22 14:41:49 2017 +0200

    [global] update FSF address
    
    Resolve issue #886
    
    Change-Id: I0496cf4f4dbee33a8a6c52b2b6a1a3271834fb6f
    Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>
```

Thanks again for taking this on!

**Pull request closed without merging**
