### PR TITLE
[crypto] collect more configs and commands

### PR DESCRIPTION
**Pull request by pmoravec**
Commands:
    fips-mode-setup --check
    update-crypto-policies --show
    update-crypto-policies --is-applied

Files:
    /etc/system-fips
    /etc/crypto-policies/*

Resolves: #1448

Signed-off-by: Pavel Moravec <pmoravec@redhat.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?

### CODE REVIEW

**Comment by tomato42** [comment]
(assuming that `*` in file specification means also contents of subdirectories and contents of files pointed by symbolic links)

r+ as the Crypto QE

**Comment by bmr-cymru** [comment]
> (assuming that * in file specification means also contents of subdirectories and contents of files pointed by symbolic links)

A `*` is treated as a shell-like glob (using the Python `glob.glob` module).

**Comment by bmr-cymru** [comment]
That said, this:

```python
    self.add_copy_spec([
        ...
        "/etc/crypto-policies/*"
    ])
```

Makes no sense. The trailing `*` does nothing since `/etc/crypto-policies/` would already collect the entire directory tree.

**Comment by tomato42** [comment]
and what about symbolic links?

**Comment by bmr-cymru** [comment]
It wouldn't be a very good tree copy without them. Refer to the plugin and archive modules for details.

Anyway, it's easy for you to verify things like this by just running the plugin - if you give `-o crypto` then only that plugin will be active, saving time on the run.

```
  Starting 1/1   crypto          [Running: crypto]
[plugin:crypto] collecting path '/etc/crypto-policies/state'
[plugin:crypto] collecting path '/etc/crypto-policies/local.d'
[plugin:crypto] collecting path '/etc/crypto-policies/back-ends'
[plugin:crypto] collecting path '/proc/crypto'
[plugin:crypto] collecting path '/etc/crypto-policies/config'
[plugin:crypto] collecting path '/proc/sys/crypto/fips_enabled'
[plugin:crypto] collecting output of 'fips-mode-setup --check'
[plugin:crypto] collecting output of 'update-crypto-policies --show'
[plugin:crypto] collecting output of 'update-crypto-policies --is-applied'
```

Yielding:

```# tree sosreport-localhost-2018-10-25-xaoebbc/etc/crypto-policies/
sosreport-localhost-2018-10-25-xaoebbc/etc/crypto-policies/
├── back-ends
│   ├── bind.config -> ../../../usr/share/crypto-policies/DEFAULT/bind.txt
│   ├── gnutls28.config -> ../../../usr/share/crypto-policies/DEFAULT/gnutls28.txt
│   ├── gnutls.config -> ../../../usr/share/crypto-policies/DEFAULT/gnutls.txt
│   ├── java.config -> ../../../usr/share/crypto-policies/DEFAULT/java.txt
│   ├── krb5.config -> ../../../usr/share/crypto-policies/DEFAULT/krb5.txt
│   ├── nss.config -> ../../../usr/share/crypto-policies/DEFAULT/nss.txt
│   ├── openssh.config -> ../../../usr/share/crypto-policies/DEFAULT/openssh.txt
│   └── openssl.config -> ../../../usr/share/crypto-policies/DEFAULT/openssl.txt
├── config
└── state
    └── current
```

And the referents in `/usr`:

```
# ls sosreport-localhost-2018-10-25-xaoebbc/usr/share/crypto-policies/DEFAULT/
bind.txt  gnutls28.txt  gnutls.txt  java.txt  krb5.txt  nss.txt  openssh.txt  openssl.txt
```

**Pull request closed without merging**
