### PR TITLE
[plugins] Allow filtering log files by mtime

### PR DESCRIPTION
**Pull request by pmoravec**
`add_copy_spec` method extended by maxage and minage parameters.

If maxage (or minage) is specified, only the files with mtime
not older than (or not newer than, respectively) than the given
number of hours are collected.

Resulting list of files (optionally such filtered) is still ordered
by mtime from newest to oldest (to still fulfill #1082).

Resolves: #284

Signed-off-by: Pavel Moravec <pmoravec@redhat.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?

### CODE REVIEW

**Comment by BryanQuigley** [comment]
Haven't tested this yet, but I love the maxage concept.

It could let us drastically simplify (and maybe merge Debian/Ubuntu <> Red Hat) for the logs plugin (and my current proposed #1519). The problem I have with the current log_days is it really only can apply to systemd systems.  This would allow that variable to apply to all (albeit imperfectly).

What's the use case for minage?  
Did you check all uses for a positional argument to tailit= ?  We have call that do positional or the new style.

**Comment by pmoravec** [comment]
Use case for minage: cant imagine *now*, but theoretically we might not be interested in some very verbose huge logs by a program that got mad and started to log tons of stuff recently - and we would be interested in bit older logs only (though this will need some support from command line / plugin args, if someone will require it). Anyway if there are objections to minage, I am fine to drop it from the PR.

Havent checked wrt tailit but dont see an issue..?

**Comment by BryanQuigley** [comment]
Yea if we don't have a usecase for minage now, I'd drop it.  If you are thinking you want to implement the the commandline/plugin args next though - then we can leave it obviously...

tailit, Right now it is:
add_copy_spec(self, copyspecs, sizelimit=None, tailit=True)

so someone could write it like this
self.add_copy_spec("somelog", sizelimit, True)

If anyone did the above and didn't specify tailit=True, it's going to have an issue with the order change.
add_copy_spec(self, copyspecs, sizelimit=None, maxage=None, inage=None, tailit=True)

I did a quick once over and didn't see any issues, but you really would want to check the every add_copy_spec run, or the easy way out and put the new age bits after tailit.

**Comment by pmoravec** [comment]
OK, `minage` does not have usage atm so I am dropping it.

All places where `tailit` is set to nondefault `False` set it via `tailit=False`, so no regression should happen. And I think it makes sense to group size+age limit options together among the method arguments, and even then have the `tailit` option. So I am leaving the positional ordering as is. Anyway, good point, havent realized this.

**Comment by bmr-cymru** [comment]
This is only doing filtering by file `mtime` - i.e. accept or reject a whole file at a time. The original issue is asking for something slightly different - to be able to collect log data for a span of time. This seem to implement the fallback proposed, but not the actual per-line timestamp filtering:

* Try to filter log time stamps for specified time range
* On failure to match or other error fall back to inode mtime

Maybe it's enough but it's not the full scope of the original request (I think it was forked from an RHBZ, but I don't have it to hand).

**Comment by bmr-cymru** [comment]
The patch looks OK, but am I right that nothing is using it right now? What is the intent here - to leave it to plugin authors (in which case, having this in 3.7 won't change anything), or to plumb this through to a command line option?

I would like to see in-file filtering, but I think we can add that later by expanding the definition of `maxage` (e.g. if it's an integer, it's log days, if it's a string that parses as a date then it's an absolute start time or offset).

**Comment by pmoravec** [comment]
Yep, no usage in plugins now, just the option for further changes.

I agree with the future extension as well.

**Comment by pmoravec** [comment]
Closing in favour of #1678.

**Pull request closed without merging**
