### PR TITLE
[qpid] Add port and SSL related options

### PR DESCRIPTION
**Pull request by pmoravec**
See issue #634 for details.

See commit message in the newest/latest commit for the extension.

### CODE REVIEW

**Comment by battlemidget** [comment]
Question, could we use something like shlex.split for the arguments? I'm not particularly fond of relying on the string formatting for each command

**Comment by battlemidget** [comment]
@pmoravec ping

**Comment by pmoravec** [comment]
Sorry @battlemidget for no response so far - stuck on some other tasks, will reply / update PR within few days.

**Comment by pmoravec** [comment]
Updated though not using directly shlex.

Both commits on this branch (6ddf569 and 0bfcfb0) are worth committing to upstream - first is a fix of a smaller issue not deserving its own PR.

**Comment by battlemidget** [comment]
ack

**Comment by bmr-cymru** [comment]
:+1:

**Pull request closed without merging**
