### PR TITLE
[systemd] collect journalctl --disk-usage

### PR DESCRIPTION
**Pull request by pmoravec**
Resolves: #750

Signed-off-by: Pavel Moravec <pmoravec@redhat.com>

### CODE REVIEW

**Comment by bmr-cymru** [comment]
Why in `[systemd]`?

**Comment by pmoravec** [comment]
systemd since journalctl belongs to systemd and systemd-journald is assumed to write to the journal.

I was in doubts if to add to logs or here as well, since it is a size of _log_ journal (where also rsyslog writes). So if there is a strong argument for logs, no problem to change.

**Comment by bmr-cymru** [comment]
Yeah, don't worry - I had the same doubt (that's why I didn't Just Do It last week..).

So, having thought about it some more, I am most inclined to see this as part of the `logs` plugin - that is what we are measuring here after all.

That said, I think today it doesn't matter _that_ much since our plugin organisation / data model is wanting in lots of other ways.

Logically though I do think `logs` wins over systemd (or to make things even worse: a new plugin named `journald` perhaps? :-) ).

**Comment by bmr-cymru** [comment]
subject needs fixing for `[logs]` vs. `[systemd]` ;)

Force push the branch if you have time, otherwise I'll fixup when I rebase..

**Comment by bmr-cymru** [comment]
Merged in commit 28c87cdb311bafa194a1d2d8df2421b2a80323a7

**Pull request closed without merging**
