### PR TITLE
[networking] Collect plotnetcfg output if the tool is installed.

### PR DESCRIPTION
**Pull request by lyarwood**
The plotnetcfg tool [1] has recently been packaged for Fedora
and provides a useful method of visualising complex host
network toplogies. In the case of Openstack hosts this includes
Openvswitch devices, flows etc.

The resulting file can be used to generate a PDF visualising
this with the following command :

`cat plotnetcfg.output | dot -Tpdf > output.pdf`

[1] https://github.com/jbenc/plotnetcfg

Signed-off-by: Lee Yarwood <lyarwood@redhat.com>

### CODE REVIEW

**Comment by bmr-cymru** [comment]
pep8 complaint need fixing:

```
$ pep8 sos
sos/plugins/networking.py:179:1: E302 expected 2 blank lines, found 1
```

**Comment by bmr-cymru** [comment]
Aside from that I don't have any major objections beyond "it's one more thing in the already overcrowded & overcomplex networking module".

There's no need to conditionalise on `self.is_installed()` though - we run commands speculatively where it's just a case of "may or may not be present". You only need to test for presence if something must be done differently is something is/isn't there.

**Comment by j47997** [comment]
On 22/05/15 12:26, Bryn M. Reeves wrote:
> Aside from that I don't have any major objections beyond "it's one more thing in the already overcrowded & overcomplex networking module".

I'd still like a mode in the tool to collect and display info from a
legacy sosreport; we will have plenty of them in the forseeable future.
-- 
Cheers,
  Jeremy

**Comment by lyarwood** [comment]
@bmr-cymru ack thanks, moved this up to the base class setup method.

**Comment by battlemidget** [comment]
+1

**Comment by bmr-cymru** [comment]
"I'd still like a mode in the tool to collect and display info from a legacy sosreport"

I'd still like to see that for *current* sosreports ;-)

When we have something that works for today's reports adding support for reading legacy reports (at least 2.x) shouldn't be too big a job.

**Comment by bmr-cymru** [comment]
Fixed in commit 806267fbfef16d7c1e28553e116767e7fa167318.

**Pull request closed without merging**
