### PR TITLE
[pacemaker] Collect user-defined logfile

### PR DESCRIPTION
**Pull request by pmoravec**
/etc/sysconfig/pacemaker or /etc/default/pacemaker can specify pacemaker's
logfile that sos should collect.
    
Resolves: #1002.
    
Signed-off-by: Pavel Moravec <pmoravec@redhat.com>

### CODE REVIEW

**Comment by pmoravec** [comment]
I would appreciate a review/feedback from @battlemidget or anybody else from Ubuntu/Debian world, wrt. the `/etc/default/pacemaker` change.

**Comment by battlemidget** [comment]
Hey @pmoravec taking a look now

**Comment by kgaillot** [comment]
The files use shell-style variable assignment syntax, so I'd recommend tweaking the RE:

    '^\s*PCMK_logfile=['"]?(\S+)['"]?\s*(\s#.*)?$'

i.e. no space allowed around the equals sign; value may be unquoted, single-quoted, or double-quoted; and line may have whitespace and comment at end.

That's still not comprehensive, but short of a shell parser, it would be difficult to cover much more. It doesn't strictly match the quotes, and it assumes there is no whitespace in the value, but those are reasonable assumptions in practice, and missing the extremely rare exceptions isn't a big deal.

**Comment by pmoravec** [comment]
Thanks for suggestion. I wanted to update my PR accordingly, but the RE seems invalid - quotation marks used to delimit the RE itself are used within the RE as well.

Neither below option works well:

        pattern = '^\s*PCMK_logfile=[\'"]?(\S+)[\'"]?\s*(\s#.*)?$'

or

        pattern = "^\s*PCMK_logfile=['\"]?(\S+)['\"]?\s*(\s#.*)?$"

or

        pattern = '^\s*PCMK_logfile="?(\S+)"?\s*(\s#.*)?$'
        pattern = pattern + "^\s*PCMK_logfile='?(\S+)'?\s*(\s#.*)?$"

When I test those options against `/etc/sysconfig/pacemaker` with content:

    PCMK_logfile=/var/log/messages
    PCMK_logfile='/var/log/audit/audit.log'
    PCMK_logfile="/var/log/dmesg"

some "pacemaker logfile" was missing in either case.

Any quick advice?

**Comment by kgaillot** [comment]
Oh, right, with python REs, it's always best to enclose them in r"""..."""

If that doesn't fix the search issue, maybe try [^'"\s] instead of \S

**Comment by battlemidget** [comment]
From a data collection standpoint on Ubuntu/Debian this works for me. +1

**Comment by pmoravec** [comment]
Thanks for feedback, @battlemidget and @kgaillot .

PR updated wrt. regexp and new code to remove leading and trailing quotation marks from the value of `PCMK_logfile` variable. This implementation will not collect logfiles with trailing or leading quotation mark in the filename. Like:

    PCMK_logfile=/var/log/pacemaker.log"

(that logfile `/var/log/pacemaker.log"` wont be collected as `sos` will try to collect `/var/log/pacemaker.log` instead)

But I think this implementation is acceptable, since:

- implementing more precise syntax check / quotemark removal would be more complex and error-prone
- I dont expect a user to specify log filename with leading or trailing quotemark
- I would rather expect such a log specification to be invalid syntax

**Comment by bmr-cymru** [comment]
> But I think this implementation is acceptable, since:

Agreed; were this to become a problem for any reason I think the solution would be to develop Python code to allow us to evaluate the shell syntax properly (i.e. take as input a file in shell notation, and produce as output a Python object that can be inspected to discover the contained variables and their values).

That isn't that drastic a piece of work but it's beyond the scope of this PR and likely unwarranted at this time.

**Comment by kgaillot** [comment]
Looks good to me. The only thing I'm not sure about is whether the backlashes that are part of the pattern need to be escaped themselves (e.g. \\s instead of \s). Alternatively if you used r"""^\s...""" you wouldn't need to escape anything.

'^\s*PCMK_logfile=[\'\"]?(\S+)[\'\"]?\s*(\s#.*)?$'

**Comment by pmoravec** [comment]
Re regexp used: I have tested the current r.e. (though so far on py2 only but dont expect different behaviour) and it catched both variants of quote marks properly. I put the '\' there rather for the sake of completeness / clarity to denote I mean the next character does not have a semantic/escape meaning.

The `"""` is also a (good) option, sure.

**Pull request closed without merging**
