### PR TITLE
[perccli] Add new plugin

### PR DESCRIPTION
**Pull request by vikas-goel**
PowerEdge RAID Controller management
https://www.dell.com/support/kbdoc/en-us/000177280/how-to-use-the-poweredge-raid-controller-perc-command-line-interface-cli-utility-to-manage-your-raid-controller

Signed-off-by: Vikas Goel <vikas.goel@gmail.com>

plugin-run

plugin-events

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [X] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?

### CODE REVIEW

**Comment by vikas-goel** [comment]
@TurboTurtle , @pmoravec ,
Please review

**Review by pmoravec — APPROVED** [review]
The JSON format request like `perccli64 show ctrlcount J` sounds strange to me and I can't verify its correctness, but I believe it is OK - ACK.

**Review by TurboTurtle — APPROVED** [review]

**Comment by TurboTurtle** [comment]
Just had a quick thought - can the 'file' in this case be directed to `/dev/stdout`, so that we can get everything in one collection?

If not, then this is fine as is.

**Comment by vikas-goel** [comment]
> Just had a quick thought - can the 'file' in this case be directed to `/dev/stdout`, so that we can get everything in one collection?
> 
> If not, then this is fine as is.

That's a nice suggestion. The code is updated accordingly.

**Review by pmoravec — APPROVED** [review]

**Review by TurboTurtle — APPROVED** [review]

**Pull request merged**
