### PR TITLE
[networking] Add netplan data collection for Ubuntu.

### PR DESCRIPTION
**Pull request by slashdd**
Netplan is a YAML network configuration abstraction for various
backends (NetworkManager, networkd). It reads network configuration
from /etc/netplan/*.yaml.

Related documents:
https://wiki.ubuntu.com/Netplan
https://wiki.ubuntu.com/Netplan/Design

Signed-off-by: Eric Desrochers <eric.desrochers@canonical.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [x] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [x] Is the subject and message clear and concise?
- [x] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [x] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?

### CODE REVIEW

**Comment by slashdd** [comment]
I previously did #1153 for the same thing but by mistake I have uploaded another commit for a different PR in the same branch, so I have decided to close #1153 and have created a new PR to fix the confusion around it.

**Comment by slashdd** [comment]
For a second I thought I did a typo and remove the "," via b943f54 and then put it back via 3e6cd7b

**Comment by battlemidget** [comment]
@slashdd can you squash these commits into a single one and force push to this PR?

**Comment by slashdd** [comment]
@battlemidget sorry for the late reply, I just did the rebase/squash and push.

**Comment by daxtens** [comment]
Hi,

Is there anything else that needs to be done for this to be merged? It looks like @slashdd has rebased and squashed as requested.

Regards,
Daniel

**Comment by bmr-cymru** [comment]
Time: we have about 100 pull requests to get through before the next release.

**Comment by daxtens** [comment]
Thank you!!

**Comment by bmr-cymru** [comment]
Np, thanks for the PR - and sorry for the delay, we've been tied up on other projects since 3.5.

**Pull request closed without merging**
