### PR TITLE
openstack-nova: Add nova-status upgrade check output

### PR DESCRIPTION
**Pull request by lyarwood**
nova-status upgrade check [1] is a tool that preforms release specific
checks ahead of an upgrade.

[1] https://docs.openstack.org/nova/latest/cli/nova-status.html

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [x] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [x] Is the subject and message clear and concise?
- [x] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [x] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [x] If this commit closes an existing issue, is the line `Closes: #ISSUENUMBER` included in an independent line?
- [x] If this commit resolves an existing pull request, is the line `Resolves: #PRNUMBER` included in an independent line?

### CODE REVIEW

**Comment by pmoravec** [comment]
Generally, ACK. Just how often do you require "the Nova deployment is ready for an upgrade" information? Shall not it be enabled by a plugin option only? Or does it provide valuable information also for troubleshooting issues other than (preparing of) upgrade?

**Comment by TurboTurtle** [comment]
I don't think we need to gate this behind a plugin option if it's not a burdensome collection.

**Review by TurboTurtle — APPROVED** [review]

**Review by pmoravec — APPROVED** [review]
ACK then.

**Comment by lyarwood** [comment]
On Mon, 8 Mar 2021 at 21:46, Pavel Moravec <notifications@github.com> wrote:

> Generally, ACK. Just how often do you require "the Nova deployment is
> ready for an upgrade" information? Shall not it be enabled by a plugin
> option only? Or does it provide valuable information also for
> troubleshooting issues other than (preparing of) upgrade?
>

Yeah apologies I didn't really call this out in the commit but it is useful
outside the context of a pending upgrade, for example after an upgrade
ensuring all of our online data migrations have completed once the new
version is running etc.

Happy to respin to include the above if required.

Thanks,

Lee

**Pull request closed without merging**
