### PR TITLE
[Plugin] Add tagging class for openEuler distro

### PR DESCRIPTION
**Pull request by marsCatXdu**
I'm planning to do more works on add support for openEuler distribution, including making some plugins and improve existing openEuler policy. Adding this tagging class for the first step.

openEuler has made some projects that not published on other distros yet, like iSulad, A-Tune, stratovirt , etc. So I think make a tagging might be necessary

Signed-off-by: lijingwei <lijingwei@uniontech.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [ ] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?

### CODE REVIEW

**Comment by marsCatXdu** [comment]
The check "packit/rpm-build-fedora-rawhide-s390x" have ran for more than 5 hours, is that right?

**Comment by TurboTurtle** [comment]
You'll also want to add the new tagging class to `valid_subclasses` within the openEuler policy, e.g. like we do with Red Hat here:

https://github.com/sosreport/sos/blob/main/sos/policies/distros/redhat.py#L63

**Comment by marsCatXdu** [comment]
> You'll also want to add the new tagging class to `valid_subclasses` within the openEuler policy, e.g. like we do with Red Hat here:
> 
> https://github.com/sosreport/sos/blob/main/sos/policies/distros/redhat.py#L63

Done.

**Review by TurboTurtle — APPROVED** [review]

**Pull request merged**
