### PR TITLE
[iscsi] Enable plugin for Ubuntu and Debian

### PR DESCRIPTION
**Pull request by karibou**
Signed-off-by: Louis Bouchard <louis.bouchard@canonical.com>

### CODE REVIEW

**Comment by bmr-cymru** [comment]
Acked, thanks

**Comment by bmr-cymru** [comment]
Ugh, sorry - I missed a bug when I looked at this earlier:

```python
class RedHatIscsi(Iscsi, RedHatPlugin):

    def setup(self):
        super(RedHatIscsi, self).setup()
        packages = ('iscsi-initiator-utils',)


class DebianIscsi(Iscsi, DebianPlugin, UbuntuPlugin):

    def setup(self):
        super(DebianIscsi, self).setup()
        packages = ('open-iscsi',)
```

The assignment to `packages` is broken: this is a class property, so it needs to be assigned with class scope. It also may be evaluated by the superclass `setup()` method so any assignment to it must come before the call to the constructor (all of a class's members should be initialised before `super().setup()` is called).

You can fix this by just moving the assignment of `packages` from `setup()` to the class itself - Python allows overwriting member variable like this from a subclass.

**Comment by bmr-cymru** [comment]
I'll park this for now & come back to it when you've had a chance to fix that.

**Comment by karibou** [comment]
Hello,

Just forced updated the branch with your requested fix.

Kind regards,

...Louis

**Comment by bmr-cymru** [comment]
Looks good, thanks! 👍

**Pull request merged**
