### PR TITLE
[azure] Added  RHEL plugin and collecting conf.

### PR DESCRIPTION
**Pull request by tanaka-takayoshi**
Added supporting RedHatPlugin.
Added colleting /etc/waagent.conf.

### CODE REVIEW

**Comment by bmr-cymru** [comment]
@tanaka-takayoshi thanks for submitting the pull request. You need to add a "Signed-off-by" to your commit message, as per the [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines).

You can modify your commit with `git commit --amend` and then update the branch in the pull request with `git push --force`.

**Comment by tanaka-takayoshi** [comment]
@bmr-cymru  Thanks. I updated the comment.

**Comment by bmr-cymru** [comment]
@tanaka-takayoshi thanks! 👍

**Comment by tanaka-takayoshi** [comment]
@bmr-cymru It's not merged. Are there any problems around this PR?

**Comment by pmoravec** [comment]
@tanaka-takayoshi I see the commit:

https://github.com/sosreport/sos/commit/af990ea220008a34e599f279ac7aef57cf640ed7

in upstream (cf. in https://github.com/sosreport/sos/blob/master/sos/plugins/azure.py).

In sos project, we do not formally close PRs as "Merged" but as "Closed", cf. with e.g. https://github.com/sosreport/sos/issues/950 as an example.

**Comment by tanaka-takayoshi** [comment]
@bmr-cymru I see. Thanks a lot!

**Comment by bmr-cymru** [comment]
@pmoravec that's not quite correct. In the case that the original submitter's commit is both complete, and is up-to-date with respect to master, then the PR is closed as merged.

If the patch, or commit message needs to be edited, or rebased to current master, then the commit ID will change and the PR is "Closed" (via a Closes: or Resolves: tag in the commit message normally).

In this case the branch needed to be rebased anyway, and I also took the opportunity to add a "Resolves:" tag, hence the changed commit ID and "Closed" status.

Now that PR submitters can grant permission for the maintainers to push updates to the PR branch we could revise this, and have the committing maintainer re-push the branch - I'm not really convinced that this is a big advantage but if people think it makes a difference I'd be happy to consider it.

Note that the Author (and other fields, including original commit date) are preserved across the rebase - if you look at the commit for this PR you will see that it says " tanaka-takayoshi committed with bmr-cymru 8 days ago" - i.e. I am the "Committer" in git terms, but Tanaka remains the "Author" of the change.

**Comment by bmr-cymru** [comment]
We started doing it this way a few years ago, to avoid the need for submitters to slavishly rebase their branches just to fit in with the order in which maintainers were merging PRs.

**Pull request closed without merging**
