### PR TITLE
Add logs plugin to storage profile.

### PR DESCRIPTION
**Pull request by mulkieran**
Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by bmr-cymru** [comment]
Thanks for the patch. Could you rebase and edit the commit message to follow the (Formatting Guidelines)[https://github.com/sosreport/sos/wiki/Contribution-Guidelines]?

It should be something like:

```
[logs] add to storage profile
```

We'll likely merge the patch as-is for now as the use is obvious but longer term I think this highlights the need for a simple mechanism to declare a plugin as belonging to all profiles.

There's a simple, hacky, way to do that but I'm open to ideas for more elegant solutions.

**Comment by mulkieran** [comment]
Done!

That kind of thing feels a bit like it belongs in a configuration file.

```
all:
    logs
    ...

storage:
    md
    ...

my_special_profile:
    logs
    ...
```
but I may be wrong.

**Comment by mulkieran** [comment]
The reason I like the idea of a configuration file so much is that after learning about sosreport I had this idea that it would be nice if, say, a component in bugzilla or a repo in GitHub published its sosreport profile. The user could easily add it to their configuration file, run sosreport, and upload the result to Bugzilla bug or GitHub issue without having to think too much about it. And if they did want to think about their problem, the sosreport would give them a cogent hint about what the developers of the failing software thought was important. And if this idea seemed to work out well, it could be taken a step further and automated.

**Comment by bmr-cymru** [comment]
This is kinda the direction we are trying to move in - there are a few issues that discuss this and I expanded on it a bit more in some conference talks.

Long-term we would like to make plugins purely declarative (i.e. configuration rather than code) - supplemented with a core object model that provides an abstract view of the key system information.

This would allow projects to ship their own plugins (including profile declarations) without the risks and problems that have plagued previous attempts to ship sos plugins out-of-tree. It's very hard to make this work well when plugins can run arbitrary python code and have to interact with the rest of sos through a fairly large and complex interface.

This isn't about to appear in any release Real Soon Now but we've been discussing it a long time and I think it's a good direction for us to pursue.

**Comment by bmr-cymru** [comment]
Thanks! Rebased and merged as commit 07a688021410d32fc5f5ed4d9fb2a5495321cfa0.

**Pull request closed without merging**
