### PR TITLE
[cluster.py] The plugin was removed and split into multiple plugins

### PR DESCRIPTION
**Pull request by sbradley7777**
The cluster.py plugin was removed and split into multiple
different plugins because it was composed of multiple
components: dlm, gfs2, pacemaker, corosync, and cman.

Fixes: #587

Signed-off-by: Shane Bradley <sbradley@redhat.com>

### CODE REVIEW

**Comment by bmr-cymru** [comment]
We don't put the ".py" into plugin tags. I'd suggest something like:

```
[cluster] split into cman, corosync, dlm, gfs2 and pacemaker plugins
```

It's only 69 chars and describes what was done fairly well. The body obviously needs to give much more detail.

**Comment by sbradley7777** [comment]
Updated commit message.

**Comment by psachin** [comment]
In my opinion, we should add limit. If this PR is merged(assuming size limit is implemented), I can safely close #801

**Comment by bmr-cymru** [comment]
@pmoravec this will definitely want a release note...

**Comment by bmr-cymru** [comment]
Merged as commit e4ea92277db4fb04f8097b63bae0643ae4288004.

**Pull request closed without merging**
