### PR TITLE
[plugins] Add transport_url to protected keys

### PR DESCRIPTION
**Pull request by ppeereb1**
Signed-off-by: Paul Peereboom <paul.peereboom@duo.nl>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?

### CODE REVIEW

**Comment by pmoravec** [comment]
Why to obfuscate `transport_url`? Does not it hide some important IP address that sos should collect? Is it due to potential user:password credentials that can occur there?

Could you provide some example of line worth to obfuscate `trasport_url` value?

**Comment by ppeereb1** [comment]
Sure! It contains the rabbitmq password, example:
transport_url=rabbit://rabbit_user:f6eb2325b9acf413214f767230b01792@controller1:5672,rabbit_user:f6eb2325b9acf413214f767230b01792@controller2:5672,rabbit_user:f6eb2325b9acf413214f767230b01792@controller3:5672/

**Comment by pmoravec** [comment]
Thanks. While it would be better to hide just the password, that would require bit more complex regexp-fu and what I understood from @lyarwood , the IP address / hostname and port can be obtained from other logs. So it does not matter if we hide it as well.

**Comment by bmr-cymru** [comment]
Please squash your fixup commits into the main commit (use `git rebase -i` and the 'fixup' command).

**Comment by ppeereb1** [comment]
@bmr-cymru Yes, i've squashed  the commits

**Comment by bmr-cymru** [comment]
Merged in commit 1cd7711480deae0b12792411f21831d136c61c0c
```
commit 1cd7711480deae0b12792411f21831d136c61c0c
Author: Paul Peereboom <paul.peereboom@duo.nl>
Date:   Wed Jul 4 15:24:52 2018 +0200

    [plugins] Add transport_url to protected keys
    
    Signed-off-by: Paul Peereboom <paul.peereboom@duo.nl>
```

**Pull request closed without merging**
