### PR TITLE
[stratis] Add new plugin

### PR DESCRIPTION
**Pull request by TurboTurtle**
Adds a new plugin for the stratis storage manager

Signed-off-by: Jake Hunsaker <jhunsake@redhat.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [x] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [x] Is the subject and message clear and concise?
- [x] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [x] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?

### CODE REVIEW

**Comment by pmoravec** [comment]
Could we collect also for each pool

    stratis blockdev list <pool>
    stratis filesystem list <pool>

?

Here is the updated (and tested) code:

    class Stratis(Plugin, RedHatPlugin):
        '''Stratis Storage'''
    
        packages = ('stratis-cli', 'stratisd')
        services = ('stratisd',)
        profiles = ('storage',)
    
        def get_pool_names(self, pool_file):
            """Return a list of pool names from "stratis pool list" cmd output
               where the cmd output looks like:
               Name     Total Physical Size  Total Physical Used
               pool1                  3 GiB               60 MiB
               pool2                  3 GiB               60 MiB
            """
            out = []
            try:
                pool_out = open(pool_file).read()
            except IOError:
                return out
            for line in pool_out.splitlines()[1:]:
                out.append(line.split()[0])
            return out
    
        def setup(self):
            subcmds = [
                'filesystem list',
                'blockdev list',
                'daemon redundancy',
                'daemon version'
            ]
    
            self.add_cmd_output(["stratis %s" % subcmd for subcmd in subcmds])
            self.add_journal('stratisd')
    
            pool_file = self.get_cmd_output_now("stratis pool list")
            if pool_file:
                for pool in self.get_pool_names(pool_file):
                    self.add_cmd_output([
                        "stratis blockdev list "+pool,
                        "stratis filesystem list "+pool
                    ])
    
    # vim: set et ts=4 sw=4 :

**Comment by bmr-cymru** [comment]
```
    def get_pool_names(self, pool_file):
        """Return a list of pool names from "stratis pool list" cmd output
           where the cmd output looks like:
           Name     Total Physical Size  Total Physical Used
           pool1                  3 GiB               60 MiB
           pool2                  3 GiB               60 MiB
        """
        out = []
        try:
            pool_out = open(pool_file).read()
        except IOError:
            return out
        for line in pool_out.splitlines()[1:]:
            out.append(line.split()[0])
        return out
```

What's filtering out those column headers here? Does `stratis` support a `--noheadings` type option?

**Comment by bmr-cymru** [comment]
And what happens if the command returns no output?

**Comment by pmoravec** [comment]
Good point.

Surprisingly both `python2` and `python3` deal with the code well, since in both:

    >>> ''.splitlines()[1:]
    []

and also the particular code I suggest returns empty list as desired.

Anyway, maybe better not in relying to this and add a condition there - leaving that on @TurboTurtle .

**Comment by bmr-cymru** [comment]
No, I think it's fine. I hadn't had enough coffee to quell the paranoia this morning. ;-)

**Comment by TurboTurtle** [comment]
LGTM, I'll pull in the changes shortly.

We do seem to be doing a lot of "get this command output now and iterate over it" recently. I wonder if we should put something directly into `Plugin` to handle this so we don't have to keep re-writing it in plugins.

**Pull request closed without merging**
