### PR TITLE
[sosreport] Added error handling in Config Parsing

### LINKED ISSUE #613: Print meaningful error messages
Description:
I edited the /etc/sos.conf and forgot to assign "on" value to apache.log tunable and saved. On next run, I got an exception.
Actual result:
sudo sosreport -l
Traceback (most recent call last):
  File "/sbin/sosreport", line 23, in <module>
    main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 1228, in main
    sos = SoSReport(args)
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 528, in __init__
    self._read_config()
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 627, in _read_config
    self.config.readfp(open(config_file))
  File "/usr/lib64/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/usr/lib64/python2.7/ConfigParser.py", line 546, in _read
    raise e
ConfigParser.ParsingError: File contains parsing errors: /etc/sos.conf
	[line 17]: 'apache.log\n'

Expected result:
ConfigParser.ParsingError: File contains parsing errors: /etc/sos.conf
	[line 17]: 'apache.log\n' - missing value [on|off]

Steps to reproduce:
1. open /etc/sos.conf
2. add:
[plugins]
enable = apache
[tunables]
apache.log
3. save
4. sudo sosreport -l

### PR DESCRIPTION
**Pull request by Akasurde**
Fixes #613 
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

### CODE REVIEW

**Comment by battlemidget** [comment]
For some reason I thought we dropped the config file option.

**Comment by Akasurde** [comment]
@battlemidget What do you suggest on this ?

**Comment by bmr-cymru** [comment]
Nope - still there and I agree with @Akasurde - this has been fragile for a long time and has been spot-fixed a couple of times since I've been involved. If anything we will want to expand the configuration file support in future so I think this is an important and useful fix.

I didn't have time to properly look at the patch yesterday so didn't comment but in a quick look this morning I think the general structure is fine - I do think the exception handling around the `open()` needs tightening up: at least on some runtimes and platforms an `open()` may throw other errors than `IOError`, in particular, subclasses of OSError such as FileNotFoundError. There are some tricks that can be used to select an appropriate exception or we can use a blanket tuple like `(OSError, IOError)` (on more recent runtimes IOError is itself a type of OSError however listing both is harmless).

I'm not a massive fan of the "naked with" (a with without an `as` clause) style used on line 826 - imho it is costs more time to confusion than simply open-coding the cleanup but it's not a huge issue - I do think it warrants a comment however.

**Comment by Akasurde** [comment]
Totally agree. 
I will make following changes 

1. Add `OSError` in exception 
2. Add comment related to `with`

**Comment by bmr-cymru** [comment]
:+1:

**Comment by Akasurde** [comment]
Ping

**Pull request closed without merging**
