### PR TITLE
[conntrackd] added conntrack.py for conntrackd support

### PR DESCRIPTION
**Pull request by marcli**
This is to add support for conntrackd, it includes the config files and statistics

### CODE REVIEW

**Comment by bmr-cymru** [comment]
Thanks for the PR - please take a look at the [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines) - the plugin looks mostly fine, but you need to follow the commit and subject formatting rules (e.g. `[conntrackd] add new plugin`), and a DCO (Signed-off-by) is required for all commits.

Since you'll have to respin the branch anyway, there are a couple of minor nits with the current patch:

* No need to pass a one member list to `add_copy_spec()` - the method accepts a single string if there is only one file to collect, or a list of strings when there are multiple files.

* Nothing looks Red Hat specific here, so we should enable this for the other supported distros (netfilter's `conntrackd` is shipped in Debian, Ubuntu, and SuSE and is pretty standardised - we should be able to safely enable this for them all).

* Including a Copyright (C) line in new plugins is encouraged

Please don't push fixup patches or file new PRs for changes - just use `git rebase` or `git commit --amend` and then `git push --force` to update this request.

**Comment by pmoravec** [comment]
I suggest one local change (https://github.com/sosreport/sos/pull/920/files#r98172325) plus squashing the two commits into one - otherwise +1.

**Comment by marcli** [comment]
I have squashed the 2 commits to one now.
And I have implemented the changes, so it does not include the whole folder now just the one file, and also removed one of the commands it gathers input from.

**Comment by pmoravec** [comment]
:+1:

**Comment by pmoravec** [comment]
Hi @bmr-cymru, anything pending here or PR ready to commit/merge to upstream?

**Comment by bmr-cymru** [comment]
```
+# Copyright (C) 2007 Red Hat, Inc., Marcus Linden <mlinden@redhat.com>
```
I'll go ahead and update that copyright date when I merge this.

**Pull request closed without merging**
