### PR TITLE
[plugins:__init__] Fixing comment typo

### PR DESCRIPTION
**Pull request by muahdib69**
Signed-off-by: Raimund Sacherer <rsachere@redhat.com>
---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [X] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?

### CODE REVIEW

**Review by pmoravec — APPROVED** [review]
ACK to the code changes, just please follow DCO / https://github.com/sosreport/sos/wiki/Contribution-Guidelines (commit message syntax / signed-off / reference to this PR like "Resolves: #3158").

**Comment by muahdib69** [comment]
Hi Pavel, 

I thought if I do it as a draft that this commit would not be brought to your attention, my bad. I was fighting with the commits to get them ammended, to fix the commit message but I get this error: 

```
[rsachere@fedora sos]$ git commit --amend
[main c4c05184] [ceph_iscsi] Support tcmu-runner logs in subdirs.
 Date: Mon Mar 6 11:56:09 2023 +0100
 1 file changed, 1 insertion(+)
[rsachere@fedora sos]$ git push
To github.com:muahdib69/sos.git
 ! [rejected]          main -> main (non-fast-forward)
error: failed to push some refs to 'github.com:muahdib69/sos.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

and when I do a git pull, then my commit seems to be reverted, not sure how to fix this, maybe I cancel the pull request and start over? 

thanks

**Comment by pmoravec** [comment]
Sure, no problem, I just wanted to provide a feedback "you are going the right way" ;-) After the `git commit --amend` you should called `git push --force` - you will forcefully change history on github, but of your local branch only.

**Review by TurboTurtle — COMMENTED** [review]
Ack to the changes, but your commits needs a DCO, and the first commit should be prefixed with `[Plugin]` (note: the commit, not the PR title).

To add a DCO sign-off, you can use `git commit -s --amend`, then push with `git push --force`. You'll need to do this for both commits as we require a DCO in all commits.

**Comment by muahdib69** [comment]
Hi TurboTurtle, thank you, I think I adressed your issues just 2 minutes before you wrote your comment, I think both commits should be named correctly and they are signed off.

**Comment by TurboTurtle** [comment]
> Hi TurboTurtle, thank you, I think I adressed your issues just 2 minutes before you wrote your comment, I think both commits should be named correctly and they are signed off.

Ah, so you did. :)

**Review by TurboTurtle — APPROVED** [review]
LGTM

**Review by pmoravec — APPROVED** [review]

**Pull request merged**
