### PR TITLE
[kernel] Collect bpftool [map|prog] list in both formats

### PR DESCRIPTION
**Pull request by pmoravec**
Collect and store both maps and progs list in both human readable
and JSON formats.

Resolves: #1923

Signed-off-by: Pavel Moravec <pmoravec@redhat.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [X] If this commit closes an existing issue, is the line `Closes: #ISSUENUMBER` included in an independent line?
- [X] If this commit resolves an existing pull request, is the line `Resolves: #PRNUMBER` included in an independent line?

### CODE REVIEW

**Comment by pmoravec** [comment]
We stopped storing the JSON output in `e51d3e6` where I suspect some more regressions in other plugins can occur (I will review). Human readable output is newly required here.

This PR is in (trivially resolvable) merge conflict with #1907.

**Comment by pmoravec** [comment]
I added second commit that covers the remaining regression from e51d3e6 . Comparing whole commit e51d3e6, I found these changes:

Commands missing in archive (cf. with https://github.com/sosreport/sos/commit/e51d3e6#diff-51882d5ef2865aca0f013c1ea06e836b):
    -        lsblk_file = self.get_cmd_output_now("lsblk -f -a -l")
    +        lsblk = self.exec_cmd("lsblk -f -a -l")
    
    -        prog_file = self.get_cmd_output_now("bpftool -j prog list")
    +        prog_file = self.exec_cmd("bpftool -j prog list")
    
    -        map_file = self.get_cmd_output_now("bpftool -j map list")
    +        map_file = self.exec_cmd("bpftool -j map list")
    
    -        ip_netns_file = self.get_cmd_output_now("ip netns")
    +        ip_netns = self.exec_cmd("ip netns")
    
    -            "ntpq -c as"
    ..
    -        ids = self.get_command_output('ntpq -c as')
    +        ids = self.exec_cmd('ntpq -c as')
    
    -        self.domain_config_dir = self.get_cmd_output_now(
    +        self.domain_config_dir = self.exec_cmd(
                    "crudini --get /etc/keystone/keystone.conf "
                    "identity domain_config_dir")
    
    -            self.add_cmd_output('%s %s-list' % (cmd, k))
    -            k_list = self.get_command_output('%s %s-list' % (cmd, k))
    ..
    +            k_list = self.exec_cmd('%s %s-list' % (cmd, k))


Commands newly stored in archive:
    -            result = self.call_ext_prog(dlm_tool)
    +    result = self.collect_cmd_output(dlm_tool)
    
    
    -        show_ioas = self.call_ext_prog("iprconfig -c show-ioas")
    +        show_ioas = self.collect_cmd_output("iprconfig -c show-ioas")
    
    -        show_config = self.call_ext_prog("iprconfig -c show-config")
    +        show_config = self.collect_cmd_output("iprconfig -c show-config")
    
            cmd = 'kata-runtime --kata-show-default-config-paths'
    -        configs = self.get_command_output(cmd)
    +        configs = self.collect_cmd_output(cmd)
    
    -        kn = self.get_command_output('%s get namespaces' % self.kube_cmd)
    +        kn = self.collect_cmd_output('%s get namespaces' % self.kube_cmd)
    
    -        user_cache = self.get_command_output("npm cache ls", chroot=False)
    +        user_cache = self.collect_cmd_output("npm cache ls", chroot=False)
    
    -            stacks = self.call_ext_prog(get_stacks)['output']
    +            stacks = self.collect_cmd_output(get_stacks)['output']
    
    -        uuids_result = self.call_ext_prog('openstack baremetal node list '
    -                                          '-f value -c UUID')
    +        uuids_result = self.collect_cmd_output(
    +            'openstack baremetal node list -f value -c UUID'
    +        )
    
    -        br_list_result = self.call_ext_prog("ovs-vsctl list-br")
    +        br_list_result = self.collect_cmd_output("ovs-vsctl list-br")
    
    -        br_list_result = self.call_ext_prog("ovs-vsctl -t 5 list-br")
    +        br_list_result = self.collect_cmd_output("ovs-vsctl -t 5 list-br")
    
    -            res = self.call_ext_prog(
    +            res = self.collect_cmd_output(
                    'vdsm-client Host getConnectedStoragePools'
                )
    
    -            res = self.call_ext_prog('vdsm-client Host getStorageDomains')
    +            res = self.collect_cmd_output('vdsm-client Host getStorageDomains')
    
    -        zpools = self.call_ext_prog("zpool list -H -o name")
    +        zpools = self.collect_cmd_output("zpool list -H -o name")


I did not revert back the "newly stored commands" as that isnt a regression. If either command is stored redundantly, let me know and I can change it.

**Comment by bmr-cymru** [comment]
I've added the first patch as a change to the (now merged) ebpf plugin:

```
commit 310fc9064928502847d2e95d88c785fa9cb94bae (HEAD -> bmr-merge)
Author: Bryn M. Reeves <bmr@redhat.com>
Date:   Fri Feb 14 18:33:06 2020 +0000

    [ebpf] Collect bpftool [map|prog] list in both formats
    
    Collect and store both maps and progs list in both human readable
    and JSON formats.
    
    Resolves: #1923
    
    Suggested-by: Pavel Moravec <pmoravec@redhat.com>
    Signed-off-by: Bryn M. Reeves <bmr@redhat.com>
```

**Comment by bmr-cymru** [comment]
And I've cherry-picked the 2nd part from your branch:

```
commit a9bb1cc4bebb82d862b3d3312b74cb9d05f2e605 (HEAD -> bmr-merge)
Author: Pavel Moravec <pmoravec@redhat.com>
Date:   Tue Jan 21 14:44:20 2020 +0100

    [plugins] collect missing command outputs from e51d3e6
    
    Commit e51d3e6 caused some commands are called but not further
    stored in an sosreport archive. This fixes that regression.
    
    Related to / extends: #1923
    
    Signed-off-by: Pavel Moravec <pmoravec@redhat.com>
```

**Pull request closed without merging**
