### PR TITLE
[openstack_octavia] Stop collecting Loadbalancer details

### PR DESCRIPTION
**Pull request by pmannidi**
Currently, we're collecting loadbalancer details from nodes by running
specific commands irrespective of whether octavia client package is
installed or OS_* env variables are set required for collecting
LoadBalancer or its associated subcommands information.

This patch adds a check for both environment variables and whether
octavia package is installed.

Resolves: #2670

Signed-off-by: Purandhar Sairam Mannidi <pmannidi@redhat.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [X] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?

### CODE REVIEW

**Review by pmoravec — APPROVED** [review]

**Comment by pmoravec** [comment]
ACK to the change itself, just please fix the `pycodestyle` issues:

    sos/report/plugins/openstack_octavia.py:82:32: E128 continuation line under-indented for visual indent
    sos/report/plugins/openstack_octavia.py:98:24: E122 continuation line missing indentation or outdented
    sos/report/plugins/openstack_octavia.py:110:20: E122 continuation line missing indentation or outdented

(one can run `pycodestyle sos/report/plugins/openstack_octavia.py` locally to verify it)

**Comment by pmannidi** [comment]
recheck

**Review by pmoravec — APPROVED** [review]
The failed test/check https://github.com/sosreport/sos/pull/2675/checks?check_run_id=3530660443 is irelevant to the PR; `logs` plugin timeouted while the changes were in a different independent plugin.

Ack to the PR, thanks!

**Comment by pmoravec** [comment]
There must be some avocado testing / CI infra issue as we have same errors elsewhere. That erro can be ignored in this PR.

**Review by TurboTurtle — CHANGES_REQUESTED** [review]
Code changes LGTM, however, please squash your fixup commits as we do not allow fixup commits in `main`.

**Comment by pmannidi** [comment]
> Code changes LGTM, however, please squash your fixup commits as we do not allow fixup commits in `main`.

Done

**Review by TurboTurtle — APPROVED** [review]

**Pull request merged**
