### PR TITLE
[plugins/juju] Added the generate-bundle option for generating a YAML bundle.

### PR DESCRIPTION
**Pull request by niedbalski**
- Added the generate-bundle option for generating a YAML bundle.
- Tested with 'sudo sosreport -o juju -a'

Signed-off-by: Jorge Niedbalski <jnr@metaklass.org>

### CODE REVIEW

**Comment by bmr-cymru** [comment]
Can we use a shorter commit subject? They should be < 72 chars - there's no need to mention juju-deployerizer at that level (put it in the commit body if it's really useful info).

**Comment by battlemidget** [comment]
> This is likely not acceptable:
> 
> + if not self.check_ext_prog(program):
> + self.call_ext_prog("pip install --system juju-deployerizer")

Agreed, @niedbalski the user will have to have the juju-deployerizer installed prior to running sosreport and we check that the application exists.

**Comment by niedbalski** [comment]
@battlemidget @bmr-cymru I updated the proposal for addressing the comments.
Please review.

**Comment by battlemidget** [comment]
@bmr-cymru looks OK to me, what do you think about the logging statements?

**Comment by bmr-cymru** [comment]
I'm not wildly keen (in that historically we treat command collection as opportunistic and grab what's there while silently ignoring what isn't).

In this case there is an option to enable it so I am a bit more on the fence about it; is this data collection slow/expensive or otherwise not recommended for default collection?

From a general point of view I'd almost prefer no option and no log message but I am not on the hook for Juju support so I'll defer to folks who do.

**Comment by karibou** [comment]
Let me look into that

**Comment by karibou** [comment]
Hi,

Le 19/03/2015 11:24, Bryn M. Reeves a écrit :
> I'm not wildly keen (in that historically we treat command collection as opportunistic and grab what's there while silently ignoring what isn't).
> 
> In this case there is an option to enable it so I am a bit more on the fence about it; is this data collection slow/expensive or otherwise not recommended for default collection?
> 
> From a general point of view I'd almost prefer no option and no log message but I am not on the hook for Juju support so I'll defer to folks who do. 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sosreport/sos/pull/528#issuecomment-83492387
> 

I do agree that log message about the fact that juju-deployerizer is missing
should be avoided.

I suggest to add "(requires juju-deployerizer)" to the option doc string so the
user is aware of the requirement and silently ignore the option if it is not there.

juju-deployerizer installation requires sufficient sysadmin interaction and
context knowledge that we don't have to be explicit about it at runtime.

Kind regards,

..Louis

-- 
Louis Bouchard
Software engineer, Cloud & Sustaining eng.
Canonical Ltd
Ubuntu developer                       Debian Maintainer
GPG : 429D 7A3B DD05 B6F8 AF63  B9C4 8B3D 867C 823E 7A61

**Comment by niedbalski** [comment]
Hello

Thanks for the reviews. At this point I am thinking that just ask the user for gathering the command output by directly running this command is enough.

I am closing this proposal until I can get a clearer use case.

Thanks

**Pull request closed without merging**
