### PR TITLE
[drbd] Add drbd-utils to the package triggering list

### PR DESCRIPTION
**Pull request by slashdd**
Closes: #2169

Signed-off-by: Eric Desrochers <eric.desrochers@canonical.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [x] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [x] Is the subject and message clear and concise?
- [x] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [x] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [x] If this commit closes an existing issue, is the line `Closes: #ISSUENUMBER` included in an independent line?
- [x] If this commit resolves an existing pull request, is the line `Resolves: #PRNUMBER` included in an independent line?

### CODE REVIEW

**Comment by TurboTurtle** [comment]
What about correcting the regex to make the version optional in the package name? E.G. `drbd(.*)?-utils`

**Comment by slashdd** [comment]
I have explored the exact same regex `drbd(.*)?-utils` without sucess. I'll try to explore some more regexp pattern.

**Comment by slashdd** [comment]
Look like `packages =` doesn't support regex but `verify_packages = `does.

**Comment by slashdd** [comment]
With d853f4a, the drbd plugin now gets executed:

```
# ls -altr sos_commands/drbd/
total 20
-rw-r--r--  1 root root   68 Jul 30 20:40 drbdadm_dump-xml
-rw-r--r--  1 root root 1508 Jul 30 20:40 drbdsetup_status
drwx------  2 root root 4096 Jul 30 20:40 .
-rw-r--r--  1 root root 1508 Jul 30 20:40 drbdsetup_show
drwxr-xr-x 49 root root 4096 Jul 30 20:40 ..
```

**Comment by TurboTurtle** [comment]
Oh, it looks like we are ultimately calling `PackageManager.pkg_by_name()` which in turn uses `all_pkgs_by_name()` instead of `all_pkgs_by_name_regex()`. The former of which uses `fnmatch.filter()`, which uses Unix shell-style wildcards but not actual regexes.

So, in lieu of changing what `pkg_by_name()` calls (I'll make note to investigate that), we should be fine with simply changing the `.*` to `*`, e.g.:

```python
packages = ('drbd*-utils',)
```

**Comment by slashdd** [comment]
yep it did the trick.

**Pull request closed without merging**
