### PR TITLE
[x11] Add clinfo and vulkaninfo

### PR DESCRIPTION
**Pull request by BryanQuigley**
We should collect clinfo and vulkaninfo like we do
for glxinfo.

Signed-off-by: Bryan Quigley <bryan.quigley@canonical.com>

### CODE REVIEW

**Comment by bmr-cymru** [comment]
These are not part of X11 and don't really belong in that plugin: really glxinfo is pushing it but on Linux distributions using XFree86/Xorg it is so closely linked to the X stack as to be tolerable.

These new 3d and compute layers are completely independent however and should not be lumped in with basic X11 data - for one they will have very specific package triggers that won't match X11 - but also in terms of finding the data.

**Comment by bmr-cymru** [comment]
I'd be happy with either new plugins for these or if there's any shared/common infrastructure involved a single plugin that handled both.

**Comment by BryanQuigley** [comment]
I was thinking about moving glxinfo and these two to maybe a new gpu accel plugin?

**Comment by bmr-cymru** [comment]
That doesn't really work either - there's nothing in common (upstream source, packages, files, executables) between them - these are the things to consider for structuring plugins. As a rule of thumb, if the pieces have different trigger conditions, then they probably belong in separate plugins.

**Comment by bmr-cymru** [comment]
pep8...

**Comment by BryanQuigley** [comment]
Well, all three are implemented in mesa for various drivers.  Intel has Vulkan in mesa and AMD has OpenCL in mesa.

Really if the commands exist, we want them run and the information is the same kind of information in all three cases.  

If we wanted to go more in-depth on GPUs we would make a separate plugin for each type (for example the Intel one could check beignet specifics), but that seems unnecessary at this point.

**Comment by bmr-cymru** [comment]
> Well, all three are implemented in mesa for various drivers. Intel has Vulkan in mesa and AMD has 
> OpenCL in mesa.

The library that implements the interface isn't really interesting for sos's use - it's the packages that provide the binaries we call (or that provide or generate the files we collect) that really matter.

The way to handle this today is with profiles: create a  new plugin for each separate type (OpenCl and Vulkan), and define a new profile in those plugins that encompasses the new category, add it to the existing `desktop` profile, or even to a new `x11` profile (`desktop` is not a great name for these lower-level gpu plumbing bits).

That way the file and command collection is enabled only when the package really is present and we reduce log noise and overheads on systems where they are not installed.

**Comment by bmr-cymru** [comment]
> If we wanted to go more in-depth on GPUs we would make a separate plugin for each type (for example 
> the Intel one could check beignet specifics), but that seems unnecessary at this point.

This is all the more reason to split them: if there are other type-specific bits we may want to add in future we might as well split them now and avoid inflicting more change on data users down the line.

**Comment by BryanQuigley** [comment]
The check for these packages isn't deterministic to if the underlying technology is installed (OpenGL, OpenCL, Vulkan).  They can all be installed even if none of the info commands are available.

So for example, I could make 3 separate plugins, but all they would ever do would be:
check for mesa-utils:
run glxinfo

check for clinfo package:
run clinfo

check for vulkan-utils package:
run vulkaninfo

Or one, gpu plugin that just tries to run all of these (like soundcard plugin).  I don't expect any of the above to ever grow in a way that wouldn't make sense for all gpus. 

If Intel GPUs need a bit more, they can just add their own plugin gpu_intel.

**Comment by bmr-cymru** [comment]
> So for example, I could make 3 separate plugins, but all they would ever do would be:
> check for mesa-utils:
> run glxinfo
>
> check for clinfo package:
> run clinfo
>
> check for vulkan-utils package:
> run vulkaninfo

That's exactly what I am saying. I'd rather maintain a dozen "one-liner" plugins like this than a single complex hairball like the `soundcard` plugin - this is actually a great example as it's already a mess and has one glaring bug as a result (it only collects pulse data on Debian right now).

Why?

It's trying to be both an `alsa` plugin and a `pulseaudio` plugin at the same time.

Ironically the only thing it _doesn't_ currently collect is anything about the physical sound cards in the system (only the resulting ALSA PCM devices), so even its name is misleading.

This isn't really up for debate: this is the direction sos plugin organisation has been moving in for a long time now and there's been no justification in this pull request as to why these GPU bits should not follow that.

**Comment by BryanQuigley** [comment]
>That's exactly what I am saying. I'd rather maintain a dozen "one-liner" plugins like this than a single complex hairball like the soundcard plugin - this is actually a great example as it's already a mess and has one glaring bug as a result (it only collects pulse data on Debian right now).

Fair enough, I'll do them that way.  Thanks for discussing!

**Pull request closed without merging**
