### PR TITLE
[docker] Fix deprecated Ubuntu workaround for docker.io binary

### PR DESCRIPTION
**Pull request by davecore82**
Signed-off-by: David Coronel <david.coronel@canonical.com>

### CODE REVIEW

**Comment by davecore82** [comment]
Removed the workaround put in place earlier which used binary docker.io instead of docker:

docker.io (1.3.1~dfsg1-2) unstable; urgency=medium
   * Remove deprecated /usr/bin/docker.io symlink
     - added as a temporary shim in 1.0.0~dfsg1-1 (13 Jun 2014)
     - unused by package-installed files in 1.2.0~dfsg1-1 (13 Sep 2014)
  -- Tianon Gravi <admwiggin@gmail.com>  Fri, 07 Nov 2014 13:11:34 -0700

The above come from debian/changelog from Ubuntu Xenial/16.04 (LTS)

The docker.io package used to have a docker.io binary but this was reverted in the changelog above. The Docker Community and Enterprise Editions (docker-ce and docker-ee packages) also use the plain docker binary and this change is necessary to make sosreport work with these packages.

**Comment by davecore82** [comment]
I pushed a second commit by mistake to add a new feature for support for docker-ce and docker-ee packages. I reverted it and pushed the original one again.

**Comment by bmr-cymru** [comment]
👍

**Comment by slashdd** [comment]
FYI, It seems like there was already a PR for the same topic.

PR
`https://github.com/sosreport/sos/pull/1009`

Commit
`https://github.com/sosreport/sos/pull/1009/files/f8a939d792d8ac683f341458b8cf77a35c4db929`

**Comment by battlemidget** [comment]
Closing this one in favor of https://github.com/sosreport/sos/pull/1009 as it contains some additional collection paths

**Pull request closed without merging**
