### PR TITLE
packaging.version related changes: chatch the proper exception and switch the priority

### PR DESCRIPTION
**Pull request by hroncok**
I am sending this as a draft as I won't be able to finish the checklist right away. Please do let me know if this seems OK to you and if so, I can amend the magical phrase to commit messages and rewrap them at 72 characters.

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [x] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [x] Is the subject and message clear and concise?
- [ ] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [x] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [ ] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?

### CODE REVIEW

**Comment by arif-ali** [comment]
This was discussed in #3126, and the preference of using `pkg_resources`, as it causes cross repo dependency in RHEL

**Comment by hroncok** [comment]
I actually want to get rid of setuptools from BaseOS in RHEL 10+.

**Comment by arif-ali** [comment]
> I actually want to get rid of setuptools from BaseOS in RHEL 10+.

OK, we at @canonical will need to be aware of this change, so that the relevant changes can be made too for Ubuntu OSs too. We have `pythnon3-packaging` already available in `main` repo, which is typically the requirement for dependencies, going back to 20.04. So, from our perspective, I don't think it will cause an issue

**Comment by pmoravec** [comment]
Generally ACK, just unsure about the flake failure (https://github.com/sosreport/sos/pull/3383/checks?check_run_id=17680606514):

    sos/utilities.py:28:5: F401 'pkg_resources.parse_version' imported but unused

Technically the error is right, practically `utilities` imports a Python class in some way, and that is used later at other places (https://github.com/search?q=repo%3Asosreport%2Fsos%20parse_version&type=code).

`Utilities` should be loaded prior any call of `parse_version` either way, but.. still I think it would be safer to keep the original `utilities`' method `parse_version` (calling *some* imported method of same name)..?

**Comment by hroncok** [comment]
I've added a commit to please the linter int he way I consider "proper".  If you do not like that, I can remove the two commits an leave the function definition as it was, because that's now what I came here to do anyway.

**Comment by hroncok** [comment]
Rebased, hopefully, the commit snow adhere to the rules.

**Review by pmoravec — APPROVED** [review]

**Review by TurboTurtle — APPROVED** [review]
Ack, though I should note that we were indeed seeing `SyntaxError` previously.

For future contributions, please note that we prefer `[tags]` in the commit title, as it makes groking through the git history much easier, but this change I'm not going to be a stickler about it.

**Pull request merged**
