### PR TITLE
[block] collect whole /sys/block

### PR DESCRIPTION
**Pull request by pmoravec**
To collect block devices information like iostats, geometry or alignment

Closes: #889.

Signed-off-by: Pavel Moravec <pmoravec@redhat.com>

### CODE REVIEW

**Comment by pmoravec** [comment]
It is possible the directory - on some systems or distros - can contain some files that should be skipped - please @bmr-cymru and @battlemidget let me know if you find such file to exclude.

**Comment by bmr-cymru** [comment]
Nack for the time being. As per our discussion this needs significant testing; I definitely can't merge it without at least testing feedback from all of the actively maintained distros.

**Comment by bmr-cymru** [comment]
I'm curious whether this was tested at all?

```
# sosreport -v --batch --debug --build -o block

sosreport (version 3.3)

[...]

sosreport build tree is located at : /var/tmp/sosreport-dhcp-24-182.fab.redhat.com-20161101105412

# ls -l /var/tmp/sosreport-dhcp-24-182.fab.redhat.com-20161101105412/sys/block/
total 4
lrwxrwxrwx. 1 root root 29 Nov  1 10:54 dm-0 -> ../devices/virtual/block/dm-0
lrwxrwxrwx. 1 root root 29 Nov  1 10:54 dm-1 -> ../devices/virtual/block/dm-1
lrwxrwxrwx. 1 root root 30 Nov  1 10:54 dm-15 -> ../devices/virtual/block/dm-15
lrwxrwxrwx. 1 root root 29 Nov  1 10:54 dm-2 -> ../devices/virtual/block/dm-2
lrwxrwxrwx. 1 root root 29 Nov  1 10:54 dm-3 -> ../devices/virtual/block/dm-3
lrwxrwxrwx. 1 root root 29 Nov  1 10:54 dm-4 -> ../devices/virtual/block/dm-4
lrwxrwxrwx. 1 root root 29 Nov  1 10:54 dm-5 -> ../devices/virtual/block/dm-5
lrwxrwxrwx. 1 root root 29 Nov  1 10:54 dm-6 -> ../devices/virtual/block/dm-6
lrwxrwxrwx. 1 root root 29 Nov  1 10:54 dm-7 -> ../devices/virtual/block/dm-7
lrwxrwxrwx. 1 root root 29 Nov  1 10:54 dm-8 -> ../devices/virtual/block/dm-8
lrwxrwxrwx. 1 root root 29 Nov  1 10:54 dm-9 -> ../devices/virtual/block/dm-9
lrwxrwxrwx. 1 root root 75 Nov  1 10:54 sda -> ../devices/pci0000:00/0000:00:17.0/ata1/host0/target0:0:0/0:0:0:0/block/sda
# ls -l /var/tmp/sosreport-dhcp-24-182.fab.redhat.com-20161101105412/sys/devices
ls: cannot access '/var/tmp/sosreport-dhcp-24-182.fab.redhat.com-20161101105412/sys/devices': No such file or directory
```

So this is pretty useless right now...

**Comment by bmr-cymru** [comment]
If I also add `/sys/devices`, so that the symlinks in `/sys/block` point somewhere, on my laptop I see the runtime for the plugin go from under 2s to around a minute:

```
# time sosreport --batch --debug -o block
[...]
real	0m2.155s
user	0m1.800s
sys	0m0.362s
```

vs.

```
# time sosreport --batch --debug -o block
[...]
real	0m59.131s
user	0m27.755s
sys	0m29.044s
```

And this is just on a little laptop system.. I don't think we can safely merge this without a lot more testing & ideally finding a more efficient way to collect these directories.

**Comment by pmoravec** [comment]
I agree, this is not worth merging.

**Comment by bmr-cymru** [comment]
It's almost tolerable on a small host, but it worries me what would happen on a large server with 1000s of paths...

**Comment by pmoravec** [comment]
These stats are sufficient instead of whole /sys/block:

    /sys/block/*/alignment_offset
    /sys/block/*/discard_alignment
    /sys/block/*/queue/*

**Comment by bmr-cymru** [comment]
Sufficient in what sense?

**Comment by jcastill** [comment]
Pavel, isn't what you are asking for in this PR already covered with my patch for lsblk in PR#1065 ?

**Comment by bmr-cymru** [comment]
Compared to the `lsblk` change in #1065 this PR also collects the full set of queue attributes and the `discard_alignment` attribute.

The discard information can be added by either adding `lsblk -D` output, or by changing the existing `lsblk -t` to `lsblk -tD`.

Since we are including `-t` I'm somewhat inclined to carry on with that route but we've had numerous requests also for more of the raw `/sys` data.

I'd be much more comfortable merging both and giving users the flexibility to choose if we could get some timing figures for systems with very large numbers of devices.

**Comment by bmr-cymru** [comment]
Ping, any progress on the timing figures for large machines? @pmoravec ?

**Comment by pmoravec** [comment]
Due to the above tests results and facts there are systems with thousands of block devices, the original scope is limited just to collecting capabilities only - `lsblk -t` newly called with `-D`.

(a small test showed that `lsblk -t` with 5k block devices took 1.8s and `lsblk -tD` took there 2.6s - un-noticeably small difference)

**Comment by pmoravec** [comment]
Already resolved by commit d5f8300.

**Pull request closed without merging**
