### PR TITLE
[filesys] show filesystem type in df command

### PR DESCRIPTION
**Pull request by NitinYewale**
---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X ] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X ] Is the subject and message clear and concise?
- [ X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X ] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [X ] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?
- [X ] Are all passwords or private data gathered by this PR [obfuscated](https://github.com/sosreport/sos/wiki/How-to-Write-a-Plugin#how-to-prevent-collecting-passwords)?

### CODE REVIEW

**Comment by NitinYewale** [comment]
This has come as a proposal from our team. We are aware that file system type is available in `blkid` command.

**Comment by pmoravec** [comment]
There might be some analytical tooling over sosreport that can rely on the well-known command output. I am checking if this would affect Red Hat, cc @arif-ali for the same at Canonical.

Up to that potential concern, OK.

**Comment by arif-ali** [comment]
> There might be some analytical tooling over sosreport that can rely on the well-known command output. I am checking if this would affect Red Hat, cc @arif-ali for the same at Canonical.

looking at the tool we use, it does parse the `df` from the `root_symlink`, so I will do some tests and get back on that one

**Review by arif-ali — APPROVED** [review]
all good from our end

**Comment by jcastill** [comment]
What about adding an extra line instead of modifying the current 'df'? I.e.:

        self.add_cmd_output("df -al -x autofs", root_symlink="df",
                            tags='df__al')
        self.add_cmd_output("df -alT -x autofs", root_symlink="df",
                            tags='df__alT')

Or even adding it to the other df a bit below that one:

        self.add_cmd_output([
            "df -ali -x autofs",

And make it:

        self.add_cmd_output([
            "df -aliT -x autofs",

**Comment by NitinYewale** [comment]
> What about adding an extra line instead of modifying the current 'df'? I.e.:
> 
> ```
>     self.add_cmd_output("df -al -x autofs", root_symlink="df",
>                         tags='df__al')
>     self.add_cmd_output("df -alT -x autofs", root_symlink="df",
>                         tags='df__alT')
> ```
> 
> Or even adding it to the other df a bit below that one:
> 
> ```
>     self.add_cmd_output([
>         "df -ali -x autofs",
> ```
> 
> And make it:
> 
> ```
>     self.add_cmd_output([
>         "df -aliT -x autofs",
> ```

okay, I will do the necessary changes and resubmit.

Thank you all for reviewing.

**Review by jcastill — APPROVED** [review]

**Review by arif-ali — APPROVED** [review]

**Review by pmoravec — APPROVED** [review]

**Pull request merged**
