### PR TITLE
Openstack_glance, openstack_heat and openstack_neutron no longer ignore 'log' option when deciding whether to dump logs

### PR DESCRIPTION
**Pull request by w-miller**

### CODE REVIEW

**Comment by battlemidget** [comment]
@w-miller Hi, thanks for the submission, first thing that stands out is this does not follow our https://github.com/sosreport/sos/wiki/Contribution-Guidelines, also you could just squash those 3 commits and force push. Please get those addressed so we can review it

Thanks!

**Comment by lyarwood** [comment]
@w-miller Thanks for the submission! I'm actually trying to work through a backlog of issues raised a while ago regarding general log collection in the plugins. 

bb7996737902db is an example of this for Nova. Can you break this single commit into one per plugin using the --all-logs and --log-size options? These should address issues #648, #442 and #443.

**Comment by bmr-cymru** [comment]
:+1: to @lyarwood and @battlemidget's comments.

**Comment by lyarwood** [comment]
@w-miller #657 should cover this now, if you get a chance can you review and ACK/NACK as required?

**Comment by bmr-cymru** [comment]
@lyarwood assuming we can close this out with the merge for #657?

**Comment by lyarwood** [comment]
@bmr-cymru yup

**Comment by bmr-cymru** [comment]
Closing with the merge for #657.

**Pull request closed without merging**
