### PR TITLE
Make add_copy_spec_limit understand lists of copyspecs

### PR DESCRIPTION
**Pull request by obnoxxx**
This is  substituting add_copy_spec with add_copy_spec_limit. Steps:

- a few cleanups and improvements of existing plugin tests
- teach add_copy_spec_limit() to understand lists of copyspecs
- add tests for the new mode of add_copy_spec_limit
- let add_copy_spec be implemented by calling add_copy_spec_limit()
- change all plugins to use add_copy_spec_only
- change tests to use add_copy_spec only and remove redundant tests
- remove add_copy_spec_limit()

### CODE REVIEW

**Comment by obnoxxx** [comment]
@bmr-cymru This is as we discussed on irc.

**Comment by obnoxxx** [comment]
@bmr-cymru as discussed on IRC, I updated the patchset to remove add_copy_spec_limit() altogether.

**Comment by obnoxxx** [comment]
I guess this closes issue #476 ?!

**Comment by obnoxxx** [comment]
@bmr-cymru ping, any comments? :-)

**Comment by bmr-cymru** [comment]
It's in my current queue - I'm just deciding whether to pull this one in in order (it's next in sequence), or to get all the other little bits and pieces done first and then consider this one.

There hasn't been much change in `Plugin` lately, so I don't expect it to be a complicated rebase, either way.

**Comment by bmr-cymru** [comment]
And yes, this will indeed close #476 (and there will be much rejoicing \o/).

**Comment by obnoxxx** [comment]
@bmr-cymru any way you like. If other merges create rebase conflict, I'll happily resolve and update.

**Comment by obnoxxx** [comment]
@bmr-cymru ping :-)

**Comment by bmr-cymru** [comment]
Not forgotten - just had quite a big backlog to review for 3.4. We want to have this in that release (this month), so this will get reviewed & merged before then.

**Comment by obnoxxx** [comment]
Alright, thanks @bmr-cymru . Just let me know when you'd like me to do some rebasing etc.

**Comment by bmr-cymru** [comment]
OK, all the BZ-related pulls are merged now. I've got this on a local branch, rebased to today's master. It was pretty thoroughly reviewed and discussed back at the end of last year, so assuming I don't hit any nasty problems during testing this should make 3.4.

**Comment by bmr-cymru** [comment]
Rebased and merged beginning with commit e12cc14c9bd8af5c03050de6c1934d52c566958f, thanks for working on this!

There are a few additional follow-up patches, switching out `add_copy_spec_limit` in plugins that were added or changed after your PR was submitted.

**Comment by obnoxxx** [comment]
Thanks @bmr-cymru ! :-)

**Comment by bmr-cymru** [comment]
np! 👍

**Comment by bmr-cymru** [comment]
Thanks for working on this & being patient with us - it's great to see `add_copy_spec_limit()` finally die :-)

**Pull request closed without merging**
