### PR TITLE
[policies] Add policy for TencentOS

### PR DESCRIPTION
**Pull request by ZoeDong**
---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [x] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [x] Is the subject and message clear and concise?
- [x] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [x] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [x] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?

### CODE REVIEW

**Review by jcastill — APPROVED** [review]

**Review by arif-ali — APPROVED** [review]

**Comment by TurboTurtle** [comment]
I'm going to raise the [same concerns I have raised previously](https://github.com/sosreport/sos/pull/3296#issuecomment-1669616400) about the recent trend of adding policy support for RHEL clones and then nothing else being done with them, and the distro in question seemingly going silent not too long after.

**Comment by arif-ali** [comment]
> I'm going to raise the [same concerns I have raised previously](https://github.com/sosreport/sos/pull/3296#issuecomment-1669616400) about the recent trend of adding policy support for RHEL clones and then nothing else being done with them, and the distro in question seemingly going silent not too long after.

Ah, yes, we discussed on IRC on this too; most of the policies are extending `RedHatPolicy` other then `ubuntu`, `suse` and `debian`. and they have limited input other than branding, like you suggested in the above comment.

Does that mean, we want to de-brand, and get rid of some of the policies?

**Comment by TurboTurtle** [comment]
> Does that mean, we want to de-brand, and get rid of some of the policies?

Not so much that, but moreso that I think we should be a bit more particular about what policies get added - what's already in the tree is already there however.

So, for instance if a new distro wants to add an sos policy and has a new/different package manager (or combination of package managers) then that makes sense to me. Or if there's a new distro with professional support offerings. Or one that is trying to carve out a name in the OSS community. Or a distro needs specific changes to collections for certain plugins (i.e. a new tagging class is needed). Etc, etc..

What I don't want to encourage though is collecting a bunch of policies that are all clones of $some_other_distro and the only the difference is the branding and the website printed in our disclaimer. Especially if the plugins have no difference between these distros (e.g. no need for different tagging classes), or if we'll never see any further contributions to upstream from them because there's only a single entity using such an in-house distribution.

**Comment by ZoeDong** [comment]
My original intention is to provide basic distro information when using sos. We will consider providing more support. Before that, I will close this PR. Thanks for your reply.

**Pull request closed without merging**
