### PR TITLE
ostree: Collect logs from ostree-finalize-staged in particular

### PR DESCRIPTION
**Pull request by cgwalters**
See https://github.com/ostreedev/ostree/pull/2589 for rationale;
this is a key systemd unit and we always want its full logs.

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [x] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [x] Is the subject and message clear and concise?
- [x] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [x] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [x] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?

### CODE REVIEW

**Review by TurboTurtle — APPROVED** [review]

**Review by pmoravec — APPROVED** [review]

**Comment by TurboTurtle** [comment]
@cgwalters we were just talking about this - it may be better to stick those units in the `services` tuple for the plugin enablement trigger.

This would mean not only would we get the journals, but we'd also get the service status and have a way to enable the plugin if something has gone completely off the rails and `/ostree` is missing or in some way not detected.

**Comment by TurboTurtle** [comment]
Cycling around on this - ping @cgwalters - see comment above.

**Comment by cgwalters** [comment]
> @cgwalters we were just talking about this - it may be better to stick those units in the services tuple for the plugin enablement trigger.

Since you know this code base and I don't, do you mind force-pushing any changes on top of my commit?

**Comment by TurboTurtle** [comment]
> > @cgwalters we were just talking about this - it may be better to stick those units in the services tuple for the plugin enablement trigger.
> 
> Since you know this code base and I don't, do you mind force-pushing any changes on top of my commit?

Ack, sure thing. I'll get to that in a bit if I can.

For reference, the change would just be adding `services = ($serv1, $serv2)` to the class constructor (similar to the `files` tuple) instead of adding the changes to `setup()`.

**Comment by TurboTurtle** [comment]
I haven't forgotten about this, but I've been having problems force-pushing over this branch. I'll push a separate PR shortly rather than continue fighting with GH over this.

**Pull request closed without merging**
