### PR TITLE
[lxd] Add check for the presence of lxd package

### PR DESCRIPTION
**Pull request by slashdd**
Closes: #1306

Signed-off-by: Eric Desrochers <eric.desrochers@canonical.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?

### CODE REVIEW

**Comment by bmr-cymru** [comment]
Thanks!

**Comment by slashdd** [comment]
Note that lxd is also available as a snap in recent Ubuntu release. `packages = ('lxd',)` will only cover the case of lxd being installed the deb way. What if we add `files = ('/snap/bin/lxd',)` so that the plugin detect both scenario (deb package and snap)

**Comment by bmr-cymru** [comment]
Should we think about adding support for triggering on snaps? Either as a new `snaps` member to `Plugin`, or as an extension to the Ubuntu policies to allow these to be recognised as packages (i.e. `PackageManager` will merge the two sources of package data).

**Comment by slashdd** [comment]
Yeah, integrating into the current Ubuntu policies would make sense to me. I'll report a new issue about that topic and will leave that PR as is for now.

**Pull request closed without merging**
