### PR TITLE
Gather OVS database in 'list' format

### PR DESCRIPTION
**Pull request by eprasad**
This changes database dump collection format to 'list' which is a more readable and easy to parse.

Signed-off-by: Prasad Mukhedkar <eprasad96@gmail.com>

### CODE REVIEW

**Comment by bmr-cymru** [comment]
Why can't this transformation be done on the analysis host? Afaik the current default is the 'canonical' format for this information and so the expected input format for other tools.

You also need to follow the [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines) when submitting pull requests (esp. commit message format, subject, and Signed-off-by).

**Comment by eprasad** [comment]
The format transformation cannot be done on the analysis host becuase to do that you need connectivity to the database, In case of openvswitch that is  provided by ovsdb-server's JSON-RPC interface. 

The default output format for ovsdb-client is table (2-D text tables with aligned columns) which is good for reading info on the console but for small amount of data only, Not for entire db dump. If I am not wrong table formatting is not canonical representation, The data collected in table format cannot be input for other tools as its not standard and strctured like json,ymal.

Although "ovsdb-client" supprts output in canonical formats like csv, json.  I strongly belive having it collected in "list" format (A  list  with one column per line and rows separated by a blank line) is most optimal option  for sosreport. List format is very easy to read and you can get needed information very quickly. I deal with openvswitch related issues frequenly and Its my experince. 

bmr-cymru thanks for the guideline link. Will follow it whenever commiting any changes in the future.

**Comment by bmr-cymru** [comment]
Patch still needs to be reformatted to meet the guidelines (subject & signed-off-by). I also need another ack from someone with an OVS background before we merge this, @lyarwood could you take a look?

**Comment by lyarwood** [comment]
LGTM, @fleitner added the original dump call in f9220549, Flavio any objections to using the list format here?

**Comment by fleitner** [comment]
@lyarwood I chose simple dump because that is what we usually see when using the tool in the console, but yeah, I agree that dumping using list format is better for review and for other tools to parse.

You have my ACK if that matters.
Thanks!

**Comment by lyarwood** [comment]
Thanks @fleitner! 

@eprasad can you amend your commit subject and msg so we can merge this? Force pushing that commit back to your branch will update the commit in this PR once you have made these changes. 

@bmr-cymru random thought, would it be useful to have CI fail if a Signed-off-by line isn't present in commit(s)?

**Comment by bmr-cymru** [comment]
@lyarwood probably although offhand I'm not sure the best way to do it - on developer systems we enforce that kind of thing via pre-commit hooks however its not really an effective means for policing pull requests since if people don't know about the commit formatting they almost certainly won't be using our hook scripts.

Doing it on the Travis side is trickier since we don't run any shell code there - just the couple of commands (pep8 + nosetests) for each python version so we'd need to add python cases to the test suite that does some sort of git operation to verify that. But then that's kinda an abuse of python-nose since it really isn't a unit test at that point...

Other projects seem to deal with this via bots that auto-comment on the issues when rule checks fail. The general consensus seems to be that these are really super-annoying and I don't think anyone wants to either maintain one, or deal with the spam, for sos.

I'm kinda fine with pointing this out when it comes up - most contributors are really quick to fix things up when they are pointed out and this seems to work OK. For the cases where people disappear I am happy to edit patches and fix them if needed (the only /real/ problem imho is large patches that are a substantial piece of work and where the author didn't give a Signed-off-by - thankfully that's a pretty rare occurrence).

**Comment by bmr-cymru** [comment]
@eprasad it's been nearly a month now so I'm just going to go ahead and fix up your commits - in future please stick to the guidelines so that we can merge stuff quickly!

Cheers,

**Pull request closed without merging**
