### PR TITLE
[Policy] Break up monolithic policy into more organized pieces

### PR DESCRIPTION
**Pull request by TurboTurtle**
2-commit patchset that simply moves `InitSystem`, `ContainerRuntime`, and their related subclasses out of `sos/policies/__init__.py` and into their own files.

Just a bit of housekeeping to better organize.

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [x] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [x] Is the subject and message clear and concise?
- [x] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [x] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [] If this commit closes an existing issue, is the line `Closes: #ISSUENUMBER` included in an independent line?
- [x] If this commit resolves an existing pull request, is the line `Resolves: #PRNUMBER` included in an independent line?

### CODE REVIEW

**Comment by BryanQuigley** [comment]
+1 makes it nicer to understand how things are organized.

I don't think it will have any negative impacts today, but this means runtime and init_system are iterated through potentially as part of the check what policy to use (line 50 policies/__init__.py).

**Comment by TurboTurtle** [comment]
That's a good point actually that I hadn't considered, and we should avoid that.

Curious if we should place these in something like `sos/policies/runtimes/...` or somewhere else in the tree entirely?

**Comment by BryanQuigley** [comment]
In one of my redo os detection attempts.  I had considered moving the os policies to their own os directory.

**Comment by TurboTurtle** [comment]
So something like this then?

```
sos/
    - policies/
        - __init__.py
        - os/
            - redhat.py
            - ubuntu.py
        - runtimes/
            - podman.py
        - initsystems/
            - systemd.py
```

At first grok that looks good to me, and it'd make it easier to organize policy utilities (e.g. `load()`) without circling back to where we are today with a bloated `sos/policies/__init__.py`.

**Comment by BryanQuigley** [comment]
That structure LGTM

**Comment by pmoravec** [comment]
+1 for the proposal re-organized to the new directory structure.

**Comment by TurboTurtle** [comment]
Well that certainly spread out more than I thought it would.

I've updated this branch to:

* Split out `ContainerRuntime` under `sos/policies/runtimes` with distinct `docker` and `podman` subclasses in that dir
* Split out `InitSystem` under `sos/policies/init_systems` with a distinct `systemd` subclass
* Split out `PackageManager` under `sos/policies/package_managers` and *added* subclasses for `dpkg` and `rpm`, and then updated the policies as needed
* Moved the actual policy classes under `sos/policies/distros`. Using `sos/policies/os` ended up with a name conflict with the regular `os` module unfortunately.
* Split out `PresetDefaults` under `sos/presets`. Then moved the RH-family presets defined in the policy under `sos/presets/redhat`, and imported those back into the policy. I think this will allow us to have better organized presets in the future, with an easier time of sharing and/or separating presets among distributions

**Review by BryanQuigley — APPROVED** [review]

**Comment by pmoravec** [comment]
Browsing source code for leftovers:

We need to update https://github.com/sosreport/sos/blob/master/sos/report/plugins/python.py#L45 (and maybe the `import` line there?).

Not sure if some change should be done to https://github.com/sosreport/sos/blob/master/docs/policies.rst and/or https://github.com/sosreport/sos/blob/master/setup.py#L100

**Comment by pmoravec** [comment]
Commit https://github.com/sosreport/sos/pull/2349/commits/746ba6261045d0525f149eabd26c785bbeb07a4d) merges changes on different places (rpm and SuSe, here), but I would let it be..

Otherwise ACK.

**Pull request closed without merging**
