### PR TITLE
[subscription_manager] collect list --available

### PR DESCRIPTION
**Pull request by wbclark**
Collect `subscription-manager list --available`

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?

### CODE REVIEW

**Comment by TurboTurtle** [comment]
I can see this being useful to collect, however there is definitely some info in this output that would need to be scrubbed. I image at a minimum, account number and pool IDs would need to be scrubbed. @pmoravec anything else?

**Comment by wbclark** [comment]
@TurboTurtle the output fields collected (including account number, pool IDs, etc) are the same as for e.g. `subscription-manager list --consumed` which isn't currently being scrubbed in any way. So if this is indeed an issue it would need to be resolved for all the `subscription-manager list` output collected by this plugin.

**Comment by TurboTurtle** [comment]
Good catch. Thinking more on it, maybe pool IDs don't need to be scrubbed, but I think account numbers certainly should be. I'll defer to Pavel on this one.

**Comment by pmoravec** [comment]
I see account numbers as sort of login - why to obfuscate them in sosreport? This info can be valuable in some specific situations (to identify if wrong account is used to register a system). So if the info can sometimes help and it needs additional work to hide the info (and I am not aware of mis-using the info), why to scrub it?

Despite my background is in system management, I am not deep expert on this so I might missed something..?

**Comment by pmoravec** [comment]
Pool IDs are definitely useful to collect (and not scrub) - esp. for Satellite / candlepin client systems, this can help to identify particular subscriptions o the RHSM server.

**Comment by bmr-cymru** [comment]
Please use the `[component] brief description of change` format for patch subjects, e.g. `[subscription_manager] collect list --available`. You can use `git rebase` or `commit --amend` to modify the branch and update with `git push --force`.

**Comment by bmr-cymru** [comment]
I don't think there's anything here that we'd normally remove in `sos` postprocessing (afaik `soscleaner` doesn't handle this data specially either).

**Comment by wbclark** [comment]
@bmr-cymru updated commit message, thanks.

**Comment by wbclark** [comment]
@bmr-cymru Hi Bryn, sorry about that! I've removed the redundant line and signed off on the commit.

**Pull request closed without merging**
