### PR TITLE
[procenv] Add environment variables from all processes

### PR DESCRIPTION
**Pull request by BryanQuigley**
This should let us see the environment variables for all processes.

### CODE REVIEW

**Comment by bmr-cymru** [comment]
I'm going to NACK this for now - we cannot keep on adding more and more `ps` captures in a zillion different formats. For one it's just not a good way to expose the data (I want this from this file, that from that file, those from the other...), but it's also crazily inefficient - we are walking `/proc` over and over opening, reading, closing, ... I cannot believe that at some point we do not run into the same scaling problems that the naive python "grab all /proc" implementation hits.

What I'm interested in is structured capture of this data in a way that's going to be:

* efficient
* useful
* extensible

I suspect this would amount to a few weeks worth of work at least (for a first cut): first to build an efficient `/proc` (and `/sys`) capture mechanism and then to add the various specific information sources that we need (files).

The structure could be the structure of `/proc` itself or some other structure (e.g. JSON) - currently `ps` does not support an alternate `/proc` location to read from which makes preserving the fs structure less interesting but this may be easier to change than to add some other back-end format parser.

You can kinda trick `ps` into using an archive now by running it in a `chroot` with a fake `/proc` but it's far from convenient.

**Comment by BryanQuigley** [comment]
Systemctl show actually shows this and a lot more context, and in a structured way.

**Comment by bmr-cymru** [comment]
`systemctl show-environment` or another command?

**Comment by BryanQuigley** [comment]
Well.. I'm wrong it doesn't provide the environment variable unless it's part of the command.. But that's the one I happened to care about.
Specifically I find systemctl show servicename to be more useful for my purposes.

**Pull request closed without merging**
