### PR TITLE
[general|host|date] Break up general into other plugins

### PR DESCRIPTION
**Pull request by TurboTurtle**
Removes the old archaic collection points noted in #314 (the last RHEL distro to use `up2date` was RHEL 4 as far as I know) and adds `date --utc` as requested in #408.

Additionally, merge the `system` and `lsbrelease` plugins into general. The `system` plugin only served to capture `/proc/sys/` and the `lsbrelease` plugin only served to run `lsb_release` and had a duplicate call to copy `/etc/lsb-release` - in either case these seem very "general" to me since they aren't distro or (realistically) component specific. 

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [x] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [x] Is the subject and message clear and concise?
- [x] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [x] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?

### CODE REVIEW

**Comment by bmr-cymru** [comment]
Nack to the merging: this is going in the wrong direction. The `general` plugin is an ancient relic that's always been a mish-mash of unrelated bits - we've made various efforts to split things out of it and to improve granularity and cohesiveness of the plugin set.

What do you see as the benefit to users or analysts of having these in a single plugin?

**Comment by TurboTurtle** [comment]
When I was looking at 314, the thought crossed my mind about what the functional difference between "general" and "core" system information actually was in the context of sos - semantic to be sure but that's where it came from.  

Part of my reasoning for merging system was that it seemed a bit odd to have a plugin whose only purpose is to collect `/proc/sys`, while another (general) collects `/proc/stat`, with neither of these being the process plugin, but still having the general plugin collect system and component independent information (which both of those are). For lsbrelease, general already captured `/etc/lsb-release` (at least for Debian systems), and moving that to a collection of all things `/etc/*-release` made the call in lsbrelease redundant. For the output of the `lsb_release` it again just seemed "generic" on it's own.

I did see about moving stuff _out_ of general and into other plugins (for example, both `/proc/` collections into process), but I found it harder to find a new home for the other items general collects. 

In the end I didn't see this so much as about end users or analysts, but moreso about consolidating similar items for easier upkeep.

I'm happy to drop the merges from the PR if you want, or take another stab at moving stuff out of general if that's what you meant by going in the wrong direction.

**Comment by TurboTurtle** [comment]
@bmr-cymru per our IRC chat, I've updated the PR to break the general plugin out into others. Moved some bits into `process` and `system`, while creating the new `date` plugin to handle non-ntp/chrony time bits (couldn't call it time due to a conflict with the standard library) and the new `host` plugin to handle host identification.

**Comment by bmr-cymru** [comment]
:+1:

**Pull request closed without merging**
