### PR TITLE
[openstack_sahara] capture logs and packages in split mode

### PR DESCRIPTION
**Pull request by poornimakshirsagar**
Adding two services openstack-sahara-api and openstack-sahara-engine 
with the required packages

### CODE REVIEW

**Comment by bmr-cymru** [comment]
Please respond to the questions raised earlier in the PR and also please fix the commit tag for the 1st commit- it should be "[openstack_swift]". Thanks!

**Comment by lyarwood** [comment]
:+1:

**Comment by bmr-cymru** [comment]
Ping: would be good to have this in in time for 3.3: please respond to the earlier points.

**Comment by poornimakshirsagar** [comment]
@bmr-cymru already fixed raised earlier in the PR and modified the commit message https://github.com/poornimakshirsagar/sos/commit/bf9aaaa6fbdd280090e846d729247964c60d1aa9.

Let me know what else need to fix here 
Thanks!

**Comment by pmoravec** [comment]
Just to clarify the current status: the 1st commit is already pushed (887fc720db5eb980088f771187311e85e04598f9). Just the 2nd one is the key one.

It seems to me the PR is confusing: for fixing #641, just the 2nd commit is relevant. But the PR contains a commit for another issue. Maybe worth rebasing the branch to have there just the 2nd commit?

**Comment by poornimakshirsagar** [comment]
@pmoravec @bmr-cymru : I had rebase the changes here

**Comment by bmr-cymru** [comment]
@poornimakshirsagar I think you have *merged* other changes rather than *rebasing* onto it - if you rebase then you should not have any merge commits (we do not allow merge commits in master in sos so you'll need to rebase again to remove it).

**Comment by poornimakshirsagar** [comment]
@bmr-cymru  how to get rid of other changes  here in this commit message. 
rebase shows no changes required on this branch.

**Comment by bmr-cymru** [comment]
You are probably better off *saving your work* (e.g. make a new branch as back up) and then `git reset --hard` back to a common point between your branch and upstream and then either re-apply *only* the changes you do want, or use `git cherry-pick` to pick them off the branch if they are in separate commits. Then you can `git push --force` to update the remote branch.

**Comment by poornimakshirsagar** [comment]
@bmr-cymru @pmoravec did "git push --force now" I see single 5ea5083 commit here on this branch .
does that solves the purpose

**Pull request closed without merging**
