### PR TITLE
[aap_receptor] Add receptor status output

### PR DESCRIPTION
**Pull request by thom-at-redhat**
---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [X] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?
- [X] Are all passwords or private data gathered by this PR [obfuscated](https://github.com/sosreport/sos/wiki/How-to-Write-a-Plugin#how-to-prevent-collecting-passwords)?

### CODE REVIEW

**Review by arif-ali — APPROVED** [review]

**Review by pmoravec — APPROVED** [review]
Assuming there is no sensitive information, ACK.

**Comment by TurboTurtle** [comment]
> Assuming there is no sensitive information, ACK.

Yeah, this would be my question - what is expected in the `*/stdout` files for example?

**Comment by thom-at-redhat** [comment]
> > Assuming there is no sensitive information, ACK.
> 
> Yeah, this would be my question - what is expected in the `*/stdout` files for example?

Relaying query to support team

**Comment by thom-at-redhat** [comment]
> > > Assuming there is no sensitive information, ACK.
> > 
> > 
> > Yeah, this would be my question - what is expected in the `*/stdout` files for example?
> 
> Relaying query to support team

Reverted stdout from sosreport unless all concerns are met.  Thanks to all for the thoughtful feedback!

**Comment by jcastill** [comment]
@thom-at-redhat can you squash these two commits into one?

**Comment by thom-at-redhat** [comment]
@jcastill done

**Review by TurboTurtle — APPROVED** [review]

**Pull request merged**
