### PR TITLE
[openstack_nova] remove too restrictive check_enabled

### PR DESCRIPTION
**Pull request by pmoravec**
Enable the plugin just based on package presence.

Resolves: #1411

Signed-off-by: Pavel Moravec <pmoravec@redhat.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?

### CODE REVIEW

**Comment by bmr-cymru** [comment]
It's a bit more than this unfortunately - I think we'll need to consider a workaround for Red Hat for now (checking for `openstack-selinux` seems the best suggestion), and then consider some better mechanism for detecting these containerised installations.

**Comment by bmr-cymru** [comment]
In so far as the `check_enabled()` bugs go, the patch is fine - although it should also delete the bogus `nova` member from each class.

The problem is that on containerised deployments it will still evaulate `False` since those packages are not in the host package manager's list.

**Comment by pmoravec** [comment]
OK, all openstack_* plugins updated such that each (and only) RedHatPlugin is enabled by `openstack-selinux` package only. Verifying packages is preserved against the same original sets of packages.

**Comment by bmr-cymru** [comment]
I am also wondering if it's even possible for us to verify these leaf packages in the plugin with our current infrastructure? Wouldn't these require us to run the `rpm` commands in the container namespace (or against the container's RPMDB if it is accessible from the host fs)?

**Comment by pmoravec** [comment]
OK, minimalistic version of the patch - `--verify` option will verify only `openstack-selinux` package, then.

**Pull request closed without merging**
