### PR TITLE
[multipath] collect host and storage target's wwnn and wwpn data through multipat…

### PR DESCRIPTION
**Pull request by Nitn-Yewale**
…hd command

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X ] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [ X] Is the subject and message clear and concise?
- [x] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X ] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [ X] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?

### CODE REVIEW

**Review by pmoravec — APPROVED** [review]
ACK from "let collect a command".

Just asking @jcastill for a review if we dont collect the same data already in some different command output..?

**Comment by jcastill** [comment]
I don't think we collect the output like this, together, and I can see it as being very useful. But I'd like to see an example of the command captured, if possible. @NitinYewale can you paste here the result of the command?

**Comment by Nitn-Yewale** [comment]
We get the output such as 

 #multipathd show paths format '%m %i %N %n %R %r %a %M %P'
multipath hcil       host WWNN          target WWNN                                    host WWPN          target WWPN        host adapter marginal_st protocol   
mpathb    1:0:0:0    0x2000040973bf10ce 0x208000c0ff43b303                             0x1000040973bf10ce 0x247000c0ff43b303 0000:11:00.0 normal      scsi:fcp   
mpathl    1:0:0:1    0x2000040973bf10ce 0x208000c0ff43b303                             0x1000040973bf10ce 0x247000c0ff43b303 0000:11:00.0 normal      scsi:fcp   
mpatha    1:0:0:2    0x2000040973bf10ce 0x208000c0ff43b303                             0x1000040973bf10ce 0x247000c0ff43b303 0000:11:00.0 normal      scsi:fcp 

[... ]
mpaths    5:0:0:0    [undef]            iqn.2015-11.com.hpe:storage.msa2050.184843b303 [undef]            [undef]            10.65.210.79 normal      scsi:iscsi 
mpathq    5:0:0:1    [undef]            iqn.2015-11.com.hpe:storage.msa2050.184843b303 [undef]            [undef]            10.65.210.79 normal      scsi:iscsi 
mpathr    5:0:0:2    [undef]            iqn.2015-11.com.hpe:storage.msa2050.184843b303 [undef]            [undef]            10.65.210.79 normal      scsi:iscsi 

and from another system for nvmeoTCP devices we see : 

nvme0n2   0:0:1   tcp:traddr=192.168.1.51,trsvcid=4420  n/a         tcp:traddr=192.168.1.51,trsvcid=4420  n/a         n/a          n/a         n/a     
nvme0n2   0:1:1   tcp:traddr=192.168.1.105,trsvcid=4420 n/a         tcp:traddr=192.168.1.105,trsvcid=4420 n/a         n/a          n/a         n/a     
nvme0n2   0:2:1   tcp:traddr=192.168.1.106,trsvcid=4420 n/a         tcp:traddr=192.168.1.106,trsvcid=4420 n/a         n/a          n/a         n/a     
nvme0n2   0:3:1   tcp:traddr=192.168.1.107,trsvcid=4420 n/a         tcp:traddr=192.168.1.107,trsvcid=4420 n/a         n/a          n/a         n/a     
nvme0n4   0:0:1   tcp:traddr=192.168.1.51,trsvcid=4420  n/a         tcp:traddr=192.168.1.51,trsvcid=4420  n/a         n/a          n/a         n/a    

Not available nvmeoFC to test as of now.

Thank you,

**Comment by Nitn-Yewale** [comment]
$ sudo multipath -ll mpathb
mpathb (3600c0ff00043aeb8b08e875f01000000) dm-6 HPE,MSA 2050 SAN
size=34G features='1 queue_if_no_path' hwhandler='1 alua' wp=rw
`-+- policy='round-robin 0' prio=50 status=active
  |- 1:0:0:0    sdd      8:48   active ready running
  `- 4:0:0:0    sdm      8:192  active ready running

$ sudo multipathd show paths format '%m %i %N %n %R %r %a %M %P' |grep mpathb
mpathb    1:0:0:0    0x2000040973bf10ce 0x208000c0ff43b303                             0x1000040973bf10ce 0x247000c0ff43b303 0000:11:00.0 normal      scsi:fcp   
mpathb    4:0:0:0    0x2000040973bf10cf 0x208000c0ff43b303                             0x1000040973bf10cf 0x247000c0ff43b303 0000:11:00.0 normal      scsi:fcp   

both paths appear separately with different host WWPN.

**Review by pmoravec — APPROVED** [review]
ACK, just please follow https://github.com/sosreport/sos/wiki/Contribution-Guidelines (shorten commit Subject and add "Resolved: #2198" or "Closing: #3198" or similar to the commit message).

Thanks for the PR!

**Pull request closed without merging**
