### PR TITLE
[instack] getting a copy of tripleo-config

### PR DESCRIPTION
**Pull request by valleedelisle**
When troubleshooting containerized OOO Deployments,
it can help a lot to have the tripleo-config files
on the overcloud nodes.

Signed-off-by: David Vallee Delisle <dvd@redhat.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?

### CODE REVIEW

**Comment by pmoravec** [comment]
Lab usually runs a smaller deployment than some real production site, anyway `json` configs and/or puppet classes shall not be huge for sosreport. +1

**Comment by bmr-cymru** [comment]
This pull request **introduces 1 alert** when merging b30088442b7849b694810e43b28c524c56bfd883 into 1b9c2032149488a2372d188a8ed3251e364f41cf - [view on LGTM.com](https://lgtm.com/projects/g/sosreport/sos/rev/pr-4d31f7c8401294121ac7c096401c1b919aa41efc)

**new alerts:**

* 1 for Implicit string concatenation in a list

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by bmr-cymru** [comment]
I'm seeing "Unknown Repository" in the branch for this pull request - has the original been removed?

**Comment by valleedelisle** [comment]
The branch was nuked a while back. I apologize for this. I've created #1760 that will supersedes this one.

**Pull request closed without merging**
