### PR TITLE
[openstack_nova] Replaced nova-manage with nova commands

### LINKED ISSUE #646: [openstack_nova] replace `nova-manage` with `openstack` or `nova` commands.
The following commands (or using the unified `openstack` command line tool) would be useful for example :

`nova agent-list`
`nova service-list`
`nova host-list`
`nova version-list`

### PR DESCRIPTION
**Pull request by Akasurde**
Fixes #646 

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

### CODE REVIEW

**Comment by bmr-cymru** [comment]
@lyarwood can you chime in on this for the OpenStack side?

**Comment by lyarwood** [comment]
@bmr-cymru  `nova` should be available in all supported (up and downstream) versions and distros so using it here is fine. The only issue I've had with switching to it and the other python clients in Openstack is how the user needs to provide valid credentials before we get anything useful from them. 

https://github.com/openstack/python-novaclient#command-line-api

For now we can just assume the user is using the environment variable approach. In the longer term would you have any objections to allowing these to be passed into sos as plugin options?

There's also a unified `openstack` client being worked on at the moment so we could potentially drop these commands in the future and throw everything into an openstack_client.py plugin.

**Comment by bmr-cymru** [comment]
Thanks Lee :+1:

**Comment by bmr-cymru** [comment]
> would you have any objections to allowing these to be passed into sos as plugin options?

No - remember the case with `postgresql` and RHEV - we cannot use command-line options to pass credentials since they are exposed in process listings (technically identities are fine but passwords/tokens are not).

If these are expected to be set in the environment we will use them. We can also add some kind of a warning if they are unset when we expect them to be.

**Comment by lyarwood** [comment]
Cool, so this LGTM once we've added the warning about missing OS_USERNAME, OS_PASSWORD and OS_TENANT env vars and added more details to the commit message.

**Comment by Akasurde** [comment]
@lyarwood I will add this is warning message and ping you back.

**Comment by Akasurde** [comment]
ping

**Comment by lyarwood** [comment]
:+1: LGTM

**Pull request closed without merging**
