### PR TITLE
Don't try to overwrite dangling symlinks

### PR DESCRIPTION
**Pull request by jan-grant**
Fix for bug #660

### CODE REVIEW

**Comment by jan-grant** [comment]
Excuse the duplicate; I don't drive github often.

**Comment by bmr-cymru** [comment]
Thanks for the PR but please see the [Contributor Guidelines](http://github.com/sosreport/sos/wiki/Contribution-Guidelines) for the preferred commit format. Specifically:

* Need a DCO (Signed-off-by) line for each contribution
* Subject format is "[subsystem] <description>"

E.g. `[archive] don't try to overwrite dangling symlinks`

An amend and forced push is fine - there's no need for a new PR.

**Comment by jan-grant** [comment]
No worries. Er - *who* gets to sign this off?

**Comment by bmr-cymru** [comment]
A DCO or "Signed-off-by" is just a declaration by the author of a change that it is their own work and that they have authorization to submit it to the project (for example, through the license of another project from which the change is derived, or from an employer who has funded or sponsored the work).

DCOs started with the Linux kernel about 10 years ago but are common in Open Source projects today - Docker, Open WebOS, Samba, Offlineimap, and many other projects require them for submissions.

We use a version based on the kernel's DCO 1.1:

```
        Developer's Certificate of Origin 1.1

        By making a contribution to this project, I certify that:

        (a) The contribution was created in whole or in part by me and I
            have the right to submit it under the open source license
            indicated in the file; or

        (b) The contribution is based upon previous work that, to the best
            of my knowledge, is covered under an appropriate open source
            license and I have the right under that license to submit that
            work with modifications, whether created in whole or in part
            by me, under the same open source license (unless I am
            permitted to submit under a different license), as indicated
            in the file; or

        (c) The contribution was provided directly to me by some other
            person who certified (a), (b) or (c) and I have not modified
            it.

        (d) I understand and agree that this project and the contribution
            are public and that a record of the contribution (including all
            personal information I submit with it, including my sign-off) is
            maintained indefinitely and may be redistributed consistent with
            this project or the open source license(s) involved.
```

See also [developercertificate.org](developercertificate.org).

**Comment by bmr-cymru** [comment]
Thanks! Will be in the next merge batch.

**Pull request closed without merging**
