### PR TITLE
[docs] Add missing target install

### PR DESCRIPTION
**Pull request by fleitner**
The ''make rpm'' breaks without target install.

### CODE REVIEW

**Comment by bmr-cymru** [comment]
We conventionally use `[docs]` for commits to the documentation. I know it seems picky but it's useful when filtering commits to have an exact string to look for. The tag is needed on the commit subject (and ideally the PR or issue it relates to).

**Comment by fleitner** [comment]
Sure. I've fixed that.

**Comment by fleitner** [comment]
Ok, this version installs everything built.
Thanks for your help!

**Comment by bmr-cymru** [comment]
Awesome, thanks for working on this! I'll try to get some testing in today/tomorrow and merge this shortly - it would be good to have it in the next release.

**Comment by bmr-cymru** [comment]
Merged, thanks!

**Pull request closed without merging**
