### PR TITLE
[debian] Remove the debian specific directory

### PR DESCRIPTION
**Pull request by karibou**
From now on, debian packaging specific files will be maintained
separately from the upstream project.

This is meant to avoid pull requests to upstream when debian-only
changes are required.

The debian packaging files along with a pristine copy of upstream
files will now reside at the following git repository :

  * http://anonscm.debian.org/cgit/collab-maint/sosreport.git/

Signed-off-by: Louis Bouchard <louis.bouchard@ubuntu.com>

### CODE REVIEW

**Comment by karibou** [comment]
Any chance to get some attention on this ? I'm waiting on this to complete the migration to Debian git repo

**Comment by battlemidget** [comment]
So what was wrong with keeping the directory in the same tree as the code?

**Comment by karibou** [comment]
Everytime the debian maintainer needs to change some debian specific packaging element, it requires  an upstream ack/merge which can take time. For the moment, the Debian Maintainer is also part of the upstream team (i.e. me) but this may change.

**Comment by battlemidget** [comment]
im ok with this then

**Comment by karibou** [comment]
Hi @bmr-cymru ,

Can I have you +1 on this so I can proceed to sync with the debian repository ?

TIA,

Kind regards,

...Louis

**Comment by bmr-cymru** [comment]
You sure can :)

**Comment by bmr-cymru** [comment]
Merged in commit 098d19684456eceb6bc2cea094b30effa19c37fc

**Pull request closed without merging**
