### PR TITLE
Options to reduce size of sar data collected

### PR DESCRIPTION
**Pull request by portante**
Red Hat, Inc. would like to considerably reduce the size of the sar data collected. We present two options, "skip_sar_reports", where no sar?? files are collected, or .xml files generated, and "data_file_limit", which places a cap on the number of raw sa?? data files collected in the report.

This request also fixes the hard-coded /var/log/sa references.

### CODE REVIEW

**Comment by portante** [comment]
@bmr-cymru, this has languished now for a while.  It still seems that adding options to enable folks to use them for their situation is useful. I agree with you that folks often take only the defaults, and that we should be working to make the defaults as reasonable as possible.  But in certain cases, and this is one of them, it would be a big help to reduce the size of the reports.

BTW, I have create https://github.com/distributed-system-analysis/satools to start to solve the problem of not having the proper version of sysstat when working sa data files.

**Comment by bmr-cymru** [comment]
@portante completely agree: I've had to put sos on the back burner for a few months to press on with other projects so this has stalled (as it wasn't ready for our last distro updates): the dmstats stuff [has just gone upstream](https://git.fedorahosted.org/cgit/lvm2.git/commit/?id=d62a8d2f1535468c75379b877844bdb7666c8c9e) so once the dust has settled a bit I will be able to get back to this.

It's still flaged for 3.3 which we should be releasing very soon now.

**Comment by battlemidget** [comment]
@bmr-cymru @portante ping just getting a status update on this PR

**Comment by portante** [comment]
@battlemidget, this change is well over 18 months old.  I would still like to see it merged, but it will take a rebase to do so, and I don't have the time right now to tend to this.

Perhaps we should close this for now, as I can always re-open this PR when I get a chance to update it.

**Comment by bmr-cymru** [comment]
I'm happy to either re-open it or move it to an issue. It's useful as a record of the problem & discussions to date (although I can't promise I'll have time to work on it seriously soon either).

It would be good to sit down with some of the performance tools stakeholders and have a general discussion about perf data collection in sos. While we can't force configurations on our users we can suggest and recommend them and help vendors and distributions to document them.

**Pull request closed without merging**
