### PR TITLE
[testing] Update Ubuntu images

### PR DESCRIPTION
**Pull request by arif-ali**
* Update to latest images from GCE for Ubuntu distros
* Update ubuntu_latest to be now 24.10, which was released recently
* Drop 18.04, now we want to start using python 3.8
* Update deb packaging to use latest ubuntu (24.10)
* Test ubuntu latest also using the snap
* Fix `msr` load issue, and update predicate to also include 22.04

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [x] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [x] Is the subject and message clear and concise?
- [x] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [x] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [ ] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?
- [ ] Are all passwords or private data gathered by this PR [obfuscated](https://github.com/sosreport/sos/wiki/How-to-Write-a-Plugin#how-to-prevent-collecting-passwords)?

### CODE REVIEW

**Comment by arif-ali** [comment]
Will do the 25.04 dev release add later, once that is in GCE. This was holding back #3811

**Review by TurboTurtle — APPROVED** [review]

**Pull request merged**
