### PR TITLE
Update default value provided in interactive mode when --name or --ticket-number is provided

### PR DESCRIPTION
**Pull request by pmoravec**
Pull request for #485

### CODE REVIEW

**Comment by bmr-cymru** [comment]
We've got some little pep8 problems here:

```
2.08s$ pep8 sos
sos/policies/__init__.py:406:1: E101 indentation contains mixed spaces and tabs
sos/policies/__init__.py:406:1: W191 indentation contains tabs
sos/policies/__init__.py:407:1: W191 indentation contains tabs
sos/policies/__init__.py:408:1: W191 indentation contains tabs
sos/policies/__init__.py:411:1: E101 indentation contains mixed spaces and tabs
```

There are vim modelines in all sources that apply the correct tab settings - if you use a different editor and are interested in adding similar support for e.g. emacs or an IDE I would be very happy to merge that (see Issue #243).

The patch header should also be in the format:

```
[plugin,or,module] brief subject line description

Something, something, something, dark side. Something, something
something, complete!

Signed-off-by: Emperor Palpatine <palpatine@deathstar.com>
```

With a hard wrap at 72 chars.

**Comment by bmr-cymru** [comment]
You can fix this up with a:

```
$ git add sos/policies/__init__.py
$ git commit --amend
$ git push --force
```

This will rewrite history on your branch but preserve the GitHub merge request info (so it'll recognise it as closed when I merge the changes to master).

**Comment by pmoravec** [comment]
Updated, sorry for not following pep8 and pull request rules :(

**Comment by bmr-cymru** [comment]
No problem, thanks for working on this!

**Comment by bmr-cymru** [comment]
WorksForMe(TM):

```
# sosreport -v --name=Palpatine --ticket-number=sith12345

sosreport (version 3.2)

This command will collect system configuration and diagnostic
information from this Fedora system. An archive containing the collected
information will be generated in /var/tmp.

For more information on the Fedora Project visit:

  https://fedoraproject.org/

The generated archive may contain data considered sensitive and its
content should be reviewed by the originating organization before being
passed to any third party.

No changes will be made to system configuration.

Press ENTER to continue, or CTRL-C to quit.

Please enter your first initial and last name [Palpatine]: 
Please enter the case id that you are generating this report for [sith12345]: 
```

Will rebase to current master & merge (commit ID will change).

**Comment by bmr-cymru** [comment]
Merged as commit 75901ef7906690aadaabc8925ac9a2e8523ed1a3:

```
commit 75901ef7906690aadaabc8925ac9a2e8523ed1a3
Author: Pavel Moravec <pmoravec@redhat.com>
Date:   Sun Feb 1 13:40:18 2015 +0100

    [general] Better handling --name and --ticket-number in interactive mode
    
    Carry forward values from the CLI options into the interactive mode,
    resolves #485
    
    Signed-off-by: Pavel Moravec <pmoravec@redhat.com>
```

**Pull request closed without merging**
