### PR TITLE
[policies] add openeuler policy support

### PR DESCRIPTION
**Pull request by marsCatXdu**
Signed-off-by: lijingwei <lijingwei@uniontech.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [ ] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?

### CODE REVIEW

**Review by TurboTurtle — COMMENTED** [review]
The policy by itself looks fine. However, are the existing plugins sufficient for the needs of openEuler?

With the current setup, openEuler systems will run `RedHatPlugin` tagged plugins - which is fine, especially since the policy inherits from `RedHatPolicy` - but this assumes that any configuration files/layouts, package names, etc... are all the same.

If there are instances where package names, directory layouts, config file paths, log paths, etc... differ, then we'd likely want to add a new `OpenEulerPlugin` tagging class as well to be able to define the differences in how plugins should run on these systems.

**Review by pmoravec — APPROVED** [review]
Likewise what Jake said. Policy itself fine, worth to identify if/when it differs from `RedHatPolicy`.

**Comment by marsCatXdu** [comment]
> The policy by itself looks fine. However, are the existing plugins sufficient for the needs of openEuler?
> 
> With the current setup, openEuler systems will run `RedHatPlugin` tagged plugins - which is fine, especially since the policy inherits from `RedHatPolicy` - but this assumes that any configuration files/layouts, package names, etc... are all the same.
> 
> If there are instances where package names, directory layouts, config file paths, log paths, etc... differ, then we'd likely want to add a new `OpenEulerPlugin` tagging class as well to be able to define the differences in how plugins should run on these systems.

Well... I wanted to make my first contribution simple. I would make a further look around writing the plugin these days and try to make one.

So, should I close this pull request?

**Review by pmoravec — APPROVED** [review]
Sounds good then (wrt explanation of no real diff from `RedHatPolicy` for now).

**Comment by TurboTurtle** [comment]
> 
> Well... I wanted to make my first contribution simple. I would make a further look around writing the plugin these days and try to make one.
> 
It's fine to add the tagging class later as we need to with any new plugins or changes to existing ones. I was just highlighting it here in case there were any known plugins that you or other openEuler users may have planned to submit contributions for later on.

> So, should I close this pull request?

No, we can take this as is.

**Review by TurboTurtle — APPROVED** [review]

**Pull request merged**
