### PR TITLE
[npm] collect modules from user's npm cache

### PR DESCRIPTION
**Pull request by jpopelka**
I cherry-picked @TomasTomecek's commit from https://github.com/sosreport/sos/pull/879 which hasn't been merged yet, because it tries to scan `~/.npm/` of all users on system.

I've added one commit on top. It parses output of `npm cache ls` which lists data in user's npm cache directory.

I can squash the commits, but I'd rather leave the Tomas` commit there if we ever wanted to return to his approach to build upon it.

### CODE REVIEW

**Comment by bmr-cymru** [comment]
I'll need a DCO (Signed-off-by), or permission to add one, in order to merge this - see the [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines) for more details on `sos` patch and commit message content & formatting.

**Comment by jpopelka** [comment]
Rebased and added Signed-off-by

**Comment by bmr-cymru** [comment]
Thanks!

**Comment by bmr-cymru** [comment]
Subject line fixed & merged, thanks

**Pull request closed without merging**
