### PR TITLE
[plugin] Master log format

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by mulkieran** [comment]
I have a feeling that the precise order of the options are part of the public interface, since that is how the names of the files are generated. This set of patches does change the order in which options are passed to journalctl. So, maybe there is a problem there.

**Comment by bmr-cymru** [comment]
They do to an extent however everything beyond the command name (and possibly a sub-command / verb) is somewhat subject to change - consumers of the data are expected to use patterns or heuristics to find the data regardless of sos version or system configuration.

We consider parsers that depend on e.g. option ordering to be fragile (again: we'd like to provide our own interfaces to the data to avoid problems of this nature but that work is somewhat stalled right now).

I need to think about some of these changes and how they fit in with our long-term plans. I like the idea of switching everything over to JSON but I'm concerned that consumers won't be ready for it (I think this is a bigger deal than command path names within the archive).

On a related note I'm also concerned about the current proliferation of journalctl invocations around the tree; there are at least 8 default calls at the moment and they all seem to be quite costly. If we could address this by collecting $EVERYTHING in JSON as well as a less verbose text summary I think this would be a good direction.

**Comment by bmr-cymru** [comment]
Minor pep8 failure in the build - Travis enforces the "two blank lines between class definitions" rule (line 76).

**Comment by mulkieran** [comment]
Ok. Here's my new attempt, which unifies handling of journalctl calls as much as seems possible within the current system. Let me know what you think of it.

**Comment by mulkieran** [comment]
Rebased.

**Comment by battlemidget** [comment]
First glance looks OK to me

**Comment by battlemidget** [comment]
Conflicts now with master, please fix commit so we can review

**Comment by bmr-cymru** [comment]
This slipped off my list while we were finishing 3.3 up. I'll try to look over it again in the next week (although it will need some changes to combine the `journal_commands` work with `add_journal()`).

**Comment by bmr-cymru** [comment]
This pull somewhat fell of the radar as we were getting ready for a RHEL update: I've flagged it for the next release, as I think the idea is still worth pursuing, and will try to get a rebased branch pushed in the next week or to for further review. Thanks for your patience!

**Comment by pmoravec** [comment]
How much yet relevant the PR is? We have plugin's `add_journal` method that basically implements this stuff be similar way.

**Comment by TurboTurtle** [comment]
Closing for two reasons:

1. The `add_journal()` method has been available for quite some time now and I don't believe we're missing anything in the current implementation that would be added with this.

2. This PR has been inactive for over 4 years at this point.


If there are ways to extend or improve `add_journal()` functionality, please open a new PR for those.

**Pull request closed without merging**
