### PR TITLE
[openvswitch] dump and capture the db and the logs

### PR DESCRIPTION
**Pull request by fleitner**
The database is essential to understand the vswitch configuration and the logs are useful for troubleshooting.

### CODE REVIEW

**Comment by bmr-cymru** [comment]
Please make sure commit messages follow the [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines) for subject line & message formatting.

Assuming there's nothing untoward in the database dumps the patches themselves look fine - just do an interactive rebase to edit the commit messages to have an `[openvswitch]` tag and then `git push --force` to update the branch and pull request.

**Comment by fleitner** [comment]
Hi Bryn,
Anything else needed here?
Thanks

**Comment by pmoravec** [comment]
PR sounds fine, until ovsdb-client dump can collect some password worth to be obfuscated.

**Comment by bmr-cymru** [comment]
Not afaik - just awaiting merge (i.e. it's stuck in my queue :-) ).

**Comment by bmr-cymru** [comment]
Merged as commit 21aff64a58a3e0f3fc5065b2e18ca3d489e16a51 and commit f92205495113a8403066e911baeb4f5ee59c2101, thanks!

I added a small patch on top to consolidate the add_cmd_output calls - no functional change, just a tidy-up.

**Pull request closed without merging**
