### PR TITLE
[ipmitool] Add ipmi Network and Users status

### PR DESCRIPTION
**Pull request by Saruspete**
Add details of the BMC Network (ip, mask, gw, vlan) and users basic info
(name, id, enabled, access level).

Signed-off-by: Adrien Mahieux <adrien@mahieux.net>

### CODE REVIEW

**Comment by bmr-cymru** [comment]
The LAN configuration is fine I think but we generally do not retrieve user data in `sos` since organisations frequently consider it sensitive (e.g. our default policies would redact the name and access level, as well as possibly the enablement state - there doesn't seem much use in collecting just IDs!).

**Comment by Saruspete** [comment]
Ok, so how about an option switch to enable it, but disabled by default ?

**Comment by bmr-cymru** [comment]
We don't have any mechanism to warn the user that an option will cause us to break the commitment we make in the disclaimer text: to make a feature like this work you would need to consider problems like that and find solutions for them.

It might also help if you explained your use-cases for this data: while `ipmitool` and related host-side utilities are provided by most Linux distributions, the task of configuring IPMI-capable devices (e.g. BMCs, infrastructure devices etc.) is typically out of scope for those distro's support offerings.

**Comment by bmr-cymru** [comment]
And looking at the current plugin, it actually appears to be broken anyway (it works, but the variable name used for the USB detection is quite misleading):

```python
        result = self.get_command_output("ipmitool -I usb mc info")
        have_usbintf = result['status']

        if not have_usbintf:
            cmd = "ipmitool -I usb"
        else:
            cmd = "ipmitool"
```

So `have_usbintf` is assigned the exit status of the command: it will be `0` (false) for success or `1` (true) for failure.

It would be a lot more readable as something like:

```python
    have_usbintf = True if result['status'] == 0 else False
```

**Comment by Saruspete** [comment]
The goal for this reporting is to know the currently configured users (from a security view) and for configuration automation (when discovering hardware, and knowing which credentials to use).

When working with hardware manufacturers (dell, hp, ibm, ami...) it's another source of data for them to ensure the bmc (ilo, idrac, asmb...) is correctly configured, at least the user has enough rights to execute the commands.

For example : 
<details>
sudo ipmitool user list 1
ID  Name	     Callin  Link Auth	IPMI Msg   Channel Priv Limit
2   root             true    false      true       ADMINISTRATOR
3   admin            true    false      true       ADMINISTRATOR
</details>

To me, this kind of knowledge is at the same criticity state as data from plugins "process", "ipa" or "ds". With the additional security these remote-console networks are often disconnected from "standard" network.

Should I remove it totally ?

**Comment by bmr-cymru** [comment]
> this kind of knowledge is at the same criticity state as data from plugins "process", "ipa" or "ds"

Unfortunately it's not a view shared by many enterprise end-users: we try to strike a good balance between redaction and collecting useful data but it can be difficult to find a sweet spot that is appropriate for all types of user.

I can see the use for the cases that you describe and I'm open to finding ways to make this work - possibly introducing a new global option that would enable collection of "account" type data: this might involve adding a mechanism to alter part of the standard disclaimer template or possibly just amending it to encompass this collection (we try to avoid changing it too often, as it has to go through a legal review process).

Unfortunately many user organisations are very protective of details they consider "internal": we've been asked to elide IP addresses, host names, account names appearing in `syslog` or `journald` logs - even in some cases UIDs/GIDs etc. - for the most part we turn these down and point concerned users to projects like [soscleaner](https://github.com/RedHatGov/soscleaner/) that implement greater redaction at the expense of destroying some support data (e.g. network address relationships).

**Comment by Saruspete** [comment]
In all financial institutions I've been and currently working in, we're covered by NDA to simplify the support and exchange of data (with RH, Dell, HP, Cisco...). 
Neverheard of soscleaner, but it's indeed good to know (I expected to see it in sosreport too).

What would be the best directive to you ? Include as much useful data as possible in sosreport, and integrate a soscleaner option to strip sensitive data should user want to ?

**Comment by bmr-cymru** [comment]
> In all financial institutions I've been and currently working in, we're covered by NDA to simplify the support 
> and exchange of data (with RH, Dell, HP, Cisco...).

That must be helpful but it is far from universal: in the thirteen years I've worked at Red Hat I have encountered many organisations who are reluctant to share the kind of data that we're discussing - worse - past experience with tools that collect excessive information, or data that is rightly considered secret has a poisoning effect: we have had customers refuse to run `sosreport` for many years on the basis of a prior bad experience.

Contractual assurances are one thing, but they cannot create confidence in the tooling.

> What would be the best directive to you ? Include as much useful data as possible in sosreport, and 
> integrate a soscleaner option to strip sensitive data should user want to ?

I'd be happy to merge functionality like that provided by `soscleaner` - but the standard we expect is that it does not destroy support data (e.g. when obfuscating IP addresses). I've told the maintainers of `soscleaner` that I'd be happy to integrate it once those problems have been addressed (I believe there's even a library with Python bindings that can automate some of that processing).

But for the specific case of account data, and the `ipmitool` plugin enhancements you've proposed it's really what I said earlier: It needs to accommodate the needs of the disclaimer text (either by changing it or making parts of it dynamic), and to have a clearly documented global setting to request this additional collection.

**Comment by Saruspete** [comment]
ack, I'll work on it :)

**Comment by bmr-cymru** [comment]
Grand - keep us informed, if you have any patches or even just sketches to share. You're welcome to keep this PR open and just re-push to the branch as things develop.

**Comment by bmr-cymru** [comment]
No further comment on the user problem - can we split this into the network parts and get that merged?

**Comment by bmr-cymru** [comment]
@Saruspete ?

**Comment by bmr-cymru** [comment]
No update: moving out to 3.7.

**Comment by bmr-cymru** [comment]
Bump to 3.8.

**Comment by pmoravec** [comment]
Some update, @Saruspete, please ?

**Comment by Saruspete** [comment]
Hello,

Deeply sorry for the long blackout :( Especially for such a quick & trivial change.
Force pushed to the latest version. Is that ok ?

For the soscleaner integration, it seems hard to integrate fully inside sosreport. Would instead an external call to it with special options to disable unwanted cleanup be better ?

**Comment by Saruspete** [comment]
I've also cleaned the usb interface test as proposed.

**Comment by pmoravec** [comment]
> For the soscleaner integration, it seems hard to integrate fully inside sosreport. Would instead an external call to it with special options to disable unwanted cleanup be better ?

What type of data needs to be scrubbed? Some that cant be provided any time (passwords, SSL private keys,..)? Then sosreport should scrub them like https://github.com/sosreport/sos/blob/master/sos/plugins/ldap.py#L24 or https://github.com/sosreport/sos/blob/master/sos/plugins/kubernetes.py#L177 for SSL certs.

Or just data like IP addresses or similar that are concern for some customer only? Then let raise PR against sos cleaner.

**Comment by bmr-cymru** [comment]
There's a discussion currently ongoing about merging the functionality `soscleaner` provides into `sos` itself for the next major release - this would give us another option for handling this for organisations that consider it sensitive info.

**Comment by TurboTurtle** [comment]
@Saruspete can you rebase on current `master` if this is still desired? For reference, obfuscation like `soscleaner` is now implemented in the sos project via calling `sos clean` or `sos report --clean` to be able to obfuscate IP addresses, hostnames, and the like.

**Comment by Saruspete** [comment]
Just did the rebase. Do you think we should add again the user listing + grants in the list if it's easily cleanable ?

**Comment by TurboTurtle** [comment]
Oh right, I spaced over the fact that it's user data here that needs to be obfuscated, instead of network. It depends. Right now username cleaning in sos is limited to UIDs between 1000-60000 as reported by `lastlog`. If the username does not appear there, we won't scrub it. 

Also, you'll need to drop the merge commit - we don't allow those in `master` - the two commits in this PR will need to apply cleanly to latest master.

**Pull request closed without merging**
