### PR TITLE
[kernel] Print human-readable timestamps with dmesg command in kernel

### PR DESCRIPTION
**Pull request by NitinYewale**
plugin

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [ X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X ] Is the subject and message clear and concise?
- [X ] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [ X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [ X] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?
- [X ] Are all passwords or private data gathered by this PR [obfuscated](https://github.com/sosreport/sos/wiki/How-to-Write-a-Plugin#how-to-prevent-collecting-passwords)?

### CODE REVIEW

**Comment by NitinYewale** [comment]
There are other placed where we could add "-T" to `dmesg` command.. example :

gcp.py:47:        dmesg = self.exec_cmd("dmesg")
xen.py:77:                "xm dmesg",

Please suggest if these needs to be changed.

**Review by TurboTurtle — APPROVED** [review]
Makes sense to me.

The flake8 job failure seems unrelated to this change and appears to come from `tox`.

**Comment by TurboTurtle** [comment]
> There are other placed where we could add "-T" to `dmesg` command.. example :
> 
> gcp.py:47: dmesg = self.exec_cmd("dmesg") xen.py:77: "xm dmesg",
> 
> Please suggest if these needs to be changed.

The `gcp` plugin usage is around finding if the GCP specific entry in dmesg is present to enable the plugin (come to think of it, is there a better approach here?), so timestamps wouldn't matter there (we also don't hold on to that output).

**Review by pmoravec — APPROVED** [review]

**Comment by NitinYewale** [comment]
Thank you @TurboTurtle @pmoravec

**Comment by bmr-cymru** [comment]
Bear in mind the warning from the `dmesg` man page:

```
       -T, --ctime
           Print human-readable timestamps.

           Be aware that the timestamp could be inaccurate! The time source used for the logs is not updated
           after system SUSPEND/RESUME. Timestamps are adjusted according to current delta between
           boottime and monotonic clocks, this works only for messages printed after last resume.
```

**Pull request merged**
