### PR TITLE
[pmem] Updated for ipmctl v2.x

### PR DESCRIPTION
**Pull request by sscargal**
ipmctl version 2.x introduces new commands and options.
It also deprecates some older commands.

Signed-off-by: Steve Scargall <steve.scargall@intel.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [] If this commit closes an existing issue, is the line `Closes: #ISSUENUMBER` included in an independent line?
- [] If this commit resolves an existing pull request, is the line `Resolves: #PRNUMBER` included in an independent line?

### CODE REVIEW

**Comment by TurboTurtle** [comment]
Does version 1.x still ship on modern distributions?

If not, then it's fine to drop the older commands, but if version 1 is still present on current RHEL/Ubuntu/etc versions, then we'll need to keep the older commands. Perhaps we can do a version check and call the version-specific commands based on that.

**Comment by sscargal** [comment]
@TurboTurtle Version 1 was never shipped in the package repos. It has to be built manually. Version 2 is available in most Linux package repos. If you can point me to an example of supporting multiple binary versions, I'll implement it as I believe it's the cleanest solution.

**Comment by TurboTurtle** [comment]
Generally version checks are done via some package manager checks, e.g. the `etcd` plugin:

```python
ver = self.policy.package_manager.get_pkg_list()['etcd']
ver = ver['version'][0]
```

**Comment by TurboTurtle** [comment]
Cycling around on this as we're aiming to close 4.0 in about 11 days.

Since version 1 was never formally packaged, I'm not opposed to keeping PR as it is. I'll leave it up to you if you want to include the version 1 commands.

**Comment by TurboTurtle** [comment]
Cycling around on this. @sscargal - any desire for updating this for both versions, or do you prefer to keep it as-is?

**Comment by sscargal** [comment]
@TurboTurtle - We can use this version. Version 1.x of ipmctl never shipped and won't ship. It was only ever available if people built it from the source. I'll implement support for multiple versions when v3.x ships.

**Review by pmoravec — APPROVED** [review]

**Pull request closed without merging**
