### PR TITLE
[doc] Add notification that "--verify" must be specified in order for

### PR DESCRIPTION
**Pull request by badone**
rpm.rpmva option to be executed.

Fixes: #735

Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

### CODE REVIEW

**Comment by bmr-cymru** [comment]
I'm in two minds on this; the `--verify` switch is supposed to control _global_ verification:

```
       --verify
              Instructs  plugins  to  perform  plugin-specific verification during
              data collection. This may include package manager verification,
              log integrity testing or other plugin defined behaviour. Use of
              --verify may cause the time taken to generate a report to be
             considerably longer.
```

Perhaps we should change that to say "Instructs _all_ plugins".

I don't think there's any problem from a UI point of view with having rpm.rpmva imply the effects of `--verify` solely for the rpm plugin: in some ways what we have now was a slightly wonky attempt to accommodate the historical rpmva behaviour along with the new global `--verify` - I think in this case we got that wrong and it causes less confusion to amend the behaviour than to expect users to note this from the documentation.

**Comment by pmoravec** [comment]
Thinking on the topic more and more, I am in favour of `rpm.rpmva` overriding the global `--verify`. Since the logic is `--verify` to *enable* some checks globally, while `rpm.rpmva` does so locally. It makes sense to have an enabling feature fine-tuned.

I.e. if `rpm.rpmva` is set, use its value. Otherwise use `--verify` value.

**Comment by bmr-cymru** [comment]
:+1:

**Comment by bmr-cymru** [comment]
If we wanted to get really fancy we could define a new global plugin option `plugin.verify` to enable this on a per-plugin basis. I don't see any hugely important use cases for that right now but it may be another step we can take to improve the consistency and granularity of verification support.

**Comment by bmr-cymru** [comment]
Will fix this shortly via the behaviour change discussed here: setting `rpm.rpmva` alone will now cause that verification to take place (but does not affect any other plugin that checks for `--verify`).

**Pull request closed without merging**
