### PR TITLE
[scsi-block-nvme] move per device data to subdirectories

### PR DESCRIPTION
**Pull request by Nitn-Yewale**
---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [ X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X ] Is the subject and message clear and concise?
- [ X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [ X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [ ] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?

### CODE REVIEW

**Comment by Nitn-Yewale** [comment]
Keeping the last row unchecked, I am trying to understand that workflow. Sorry.

**Comment by Nitn-Yewale** [comment]
Through this patch, I would lile to propose moving data collected  for "per device" to sub directories. With 100s of devices, single directory gets cluttered and it takes time to search the appropriate commands. With this patch, tried naming the sub directories based on command output they collect OR as logically as possible. Also data collected looks more neat and commands are easy to use.

Thank you,

**Comment by Nitn-Yewale** [comment]
Please ignore.. this breaks some standards.. I shall submit the new PR.

sos/report/plugins/nvme.py:48:80: E501 line too long (86 > 79 characters)

**Comment by pmoravec** [comment]
No need to close PR and delete the branch - you can update your branch by altering your git history (of your branch), e.g. via https://stackoverflow.com/questions/1186535/how-do-i-modify-a-specific-commit (with `got push --force` at the end, to forcefully push the local branches to github).

**Pull request closed without merging**
