### PR TITLE
[ctdb] Improve CTDB plugin

### PR DESCRIPTION
**Pull request by anoopcs9**
* Include main CTDB configuration and additional files
* Include list of enabled legacy event scripts

Resolves: #1894 

Signed-off-by: Anoop C S <anoopcs@redhat.com>

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [X] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [X] Is the subject and message clear and concise?
- [X] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [ ] If this commit closes an existing issue, is the line `Closes: #ISSUENUMBER` included in an independent line?
- [x] If this commit resolves an existing pull request, is the line `Resolves: #PRNUMBER` included in an independent line?

### CODE REVIEW

**Comment by anoopcs9** [comment]
> ACK.
> 
> It would be great to amend commit message by adding "Resolves: #1894".

Updated.

**Comment by pmoravec** [comment]
Thanks!

**Comment by TurboTurtle** [comment]
Code change looks OK - but are there any sensitive data points in `ctdb.conf` or the `*.options` files? Passwords of any kind, certificate contents, etc...?

**Comment by anoopcs9** [comment]
> Code change looks OK - but are there any sensitive data points in `ctdb.conf` or the `*.options` files? Passwords of any kind, certificate contents, etc...?

I don't think we have anything sensitive in nature inside ctdb.conf or *.options files under /etc/ctdb/. But I will let @amitay or @martin-schwenke have a comment before we approve this change.

**Comment by gd** [comment]
Yeah, also can't think of any sensitive data at all in these files.

**Comment by martin-schwenke** [comment]
At the moment there is nothing sensitive in the configuration files.

In the future we have vague plans to add support for a shared secret (or similar) that will be used to authenticate connections between nodes.  We can obviously put this secret in a different file.

**Comment by pmoravec** [comment]
> At the moment there is nothing sensitive in the configuration files.
> 
> In the future we have vague plans to add support for a shared secret (or similar) that will be used to authenticate connections between nodes. We can obviously put this secret in a different file.

I see few options here:

- if you know the format / name of that option already (I dont expect so), we can start obfuscating it even now
- once you start having the secret in this file (or know the format/name of the option), we can amend the plugin to obfuscate it
- or leave the secret in a different file

**Comment by TurboTurtle** [comment]
LGTM, thanks for the sensitive data check.

Like @pmoravec mentions, we can always add postprocessing to the plugin for when secrets might be added to these files.

**Comment by anoopcs9** [comment]
Is there any pending task that needs to be completed here?

**Pull request closed without merging**
